drop table if exists people cascade;
drop table if exists companies cascade;
drop table if exists majors cascade;
drop table if exists education cascade;
drop table if exists contacts cascade;
drop table if exists roles cascade;
drop table if exists work_place cascade;
drop table if exists jobs cascade;
drop table if exists recommendations cascade;