insert into companies (id, company_name, main_country, annual_revenue) values (0, 'Exxon Mobil', 'United States', 6807.6347);
insert into companies (id, company_name, main_country, annual_revenue) values (1, 'Wal-Mart Stores', 'Namibia', 45209.4141);
insert into companies (id, company_name, main_country, annual_revenue) values (2, 'Chevron', 'Burundi', 54106.2691);
insert into companies (id, company_name, main_country, annual_revenue) values (3, 'ConocoPhillips', 'Qatar', 85257.6203);
insert into companies (id, company_name, main_country, annual_revenue) values (4, 'General Motors', 'Guatemala', 12647.9786);
insert into companies (id, company_name, main_country, annual_revenue) values (5, 'General Electric', 'Slovenia', 40396.8032);
insert into companies (id, company_name, main_country, annual_revenue) values (6, 'Berkshire Hathaway', 'Turkmenistan', 50552.2344);
insert into companies (id, company_name, main_country, annual_revenue) values (7, 'Fannie Mae', 'United Arab Emirates', 74598.5301);
insert into companies (id, company_name, main_country, annual_revenue) values (8, 'Ford Motor', 'San Marino', 71891.4193);
insert into companies (id, company_name, main_country, annual_revenue) values (9, 'Hewlett-Packard', 'Vanuatu', 78177.8636);
insert into companies (id, company_name, main_country, annual_revenue) values (10, 'AT&T', 'Georgia', 1655.4542);
insert into companies (id, company_name, main_country, annual_revenue) values (11, 'Valero Energy', 'Ivory Coast', 15934.3805);
insert into companies (id, company_name, main_country, annual_revenue) values (12, 'Bank of America Corp.', 'Sudan', 31331.236);
insert into companies (id, company_name, main_country, annual_revenue) values (13, 'McKesson', 'Somalia', 49984.3573);
insert into companies (id, company_name, main_country, annual_revenue) values (14, 'Verizon Communications', 'Madagascar', 84918.7775);
insert into companies (id, company_name, main_country, annual_revenue) values (15, 'J.P. Morgan Chase & Co.', 'Uruguay', 54538.3492);
insert into companies (id, company_name, main_country, annual_revenue) values (16, 'Apple', 'Cape Verde', 20474.9083);
insert into companies (id, company_name, main_country, annual_revenue) values (17, 'CVS Caremark', 'Costa Rica', 99689.56);
insert into companies (id, company_name, main_country, annual_revenue) values (18, 'International Business Machines', 'China', 38632.1532);
insert into companies (id, company_name, main_country, annual_revenue) values (19, 'Citigroup', 'Sri Lanka', 88743.3636);
insert into companies (id, company_name, main_country, annual_revenue) values (20, 'Cardinal Health', 'United States', 4214.337);
insert into companies (id, company_name, main_country, annual_revenue) values (21, 'UnitedHealth Group', 'Liberia', 16557.2064);
insert into companies (id, company_name, main_country, annual_revenue) values (22, 'Kroger', 'Chad', 43883.6362);
insert into companies (id, company_name, main_country, annual_revenue) values (23, 'Costco Wholesale', 'Congo', 12071.3698);
insert into companies (id, company_name, main_country, annual_revenue) values (24, 'Freddie Mac', 'Comoros', 5983.0982);
insert into companies (id, company_name, main_country, annual_revenue) values (25, 'Wells Fargo', 'Mozambique', 10552.1699);
insert into companies (id, company_name, main_country, annual_revenue) values (26, 'Procter & Gamble', 'Chile', 42036.0026);
insert into companies (id, company_name, main_country, annual_revenue) values (27, 'Archer Daniels Midland', 'Haiti', 79769.3471);
insert into companies (id, company_name, main_country, annual_revenue) values (28, 'AmerisourceBergen', 'Vanuatu', 67258.2703);
insert into companies (id, company_name, main_country, annual_revenue) values (29, 'INTL FCStone', 'Sudan', 46876.5862);
insert into companies (id, company_name, main_country, annual_revenue) values (30, 'Marathon Petroleum', 'Madagascar', 78801.8157);
insert into companies (id, company_name, main_country, annual_revenue) values (31, 'Walgreen', 'Sri Lanka', 38722.8152);
insert into companies (id, company_name, main_country, annual_revenue) values (32, 'American International Group', 'Trinidad & Tobago', 80176.5223);
insert into companies (id, company_name, main_country, annual_revenue) values (33, 'MetLife', 'Congo {Democratic Rep}', 81438.2853);
insert into companies (id, company_name, main_country, annual_revenue) values (34, 'Home Depot', 'Liechtenstein', 62654.5234);
insert into companies (id, company_name, main_country, annual_revenue) values (35, 'Medco Health Solutions', 'Mauritius', 43582.9639);
insert into companies (id, company_name, main_country, annual_revenue) values (36, 'Microsoft', 'Ecuador', 53470.8591);
insert into companies (id, company_name, main_country, annual_revenue) values (37, 'Target', 'Canada', 95910.5703);
insert into companies (id, company_name, main_country, annual_revenue) values (38, 'Boeing', 'Myanmar, {Burma}', 52507.2017);
insert into companies (id, company_name, main_country, annual_revenue) values (39, 'Pfizer', 'Iraq', 98272.9618);
insert into companies (id, company_name, main_country, annual_revenue) values (40, 'PepsiCo', 'Bolivia', 36211.0894);
insert into companies (id, company_name, main_country, annual_revenue) values (41, 'Johnson & Johnson', 'Mauritania', 73481.3846);
insert into companies (id, company_name, main_country, annual_revenue) values (42, 'State Farm Insurance Cos.', 'Ukraine', 62864.1701);
insert into companies (id, company_name, main_country, annual_revenue) values (43, 'Dell', 'Belgium', 91250.6669);
insert into companies (id, company_name, main_country, annual_revenue) values (44, 'WellPoint', 'Togo', 23228.6856);
insert into companies (id, company_name, main_country, annual_revenue) values (45, 'Caterpillar', 'Malawi', 4990.3144);
insert into companies (id, company_name, main_country, annual_revenue) values (46, 'Dow Chemical', 'Saudi Arabia', 55389.6535);
insert into companies (id, company_name, main_country, annual_revenue) values (47, 'United Technologies', 'Trinidad & Tobago', 96911.2008);
insert into companies (id, company_name, main_country, annual_revenue) values (48, 'Comcast', 'Equatorial Guinea', 63455.3206);
insert into companies (id, company_name, main_country, annual_revenue) values (49, 'Kraft Foods', 'Serbia', 42885.4669);
insert into companies (id, company_name, main_country, annual_revenue) values (50, 'Intel', 'Croatia', 34138.8501);
insert into companies (id, company_name, main_country, annual_revenue) values (51, 'United Parcel Service', 'Belarus', 14725.9924);
insert into companies (id, company_name, main_country, annual_revenue) values (52, 'Best Buy', 'Thailand', 25266.4466);
insert into companies (id, company_name, main_country, annual_revenue) values (53, 'Lowes', 'Samoa', 17181.4552);
insert into companies (id, company_name, main_country, annual_revenue) values (54, 'Prudential Financial', 'Guyana', 53964.7774);
insert into companies (id, company_name, main_country, annual_revenue) values (55, 'Amazon.com', 'Uganda', 96729.5945);
insert into companies (id, company_name, main_country, annual_revenue) values (56, 'Merck', 'Latvia', 64391.9121);
insert into companies (id, company_name, main_country, annual_revenue) values (57, 'Lockheed Martin', 'Suriname', 41895.9307);
insert into companies (id, company_name, main_country, annual_revenue) values (58, 'Coca-Cola', 'Luxembourg', 78239.7623);
insert into companies (id, company_name, main_country, annual_revenue) values (59, 'Express Scripts Holding', 'Ukraine', 22397.8924);
insert into companies (id, company_name, main_country, annual_revenue) values (60, 'Sunoco', 'Seychelles', 97483.5833);
insert into companies (id, company_name, main_country, annual_revenue) values (61, 'Enterprise Products Partners', 'Italy', 91552.3363);
insert into companies (id, company_name, main_country, annual_revenue) values (62, 'Safeway', 'Malawi', 20614.8978);
insert into companies (id, company_name, main_country, annual_revenue) values (63, 'Cisco Systems', 'Spain', 27935.7071);
insert into companies (id, company_name, main_country, annual_revenue) values (64, 'Sears Holdings', 'Afghanistan', 63966.6789);
insert into companies (id, company_name, main_country, annual_revenue) values (65, 'Walt Disney', 'Armenia', 329.0613);
insert into companies (id, company_name, main_country, annual_revenue) values (66, 'Johnson Controls', 'Sri Lanka', 55977.1114);
insert into companies (id, company_name, main_country, annual_revenue) values (67, 'Morgan Stanley', 'Benin', 30088.7875);
insert into companies (id, company_name, main_country, annual_revenue) values (68, 'Sysco', 'San Marino', 84143.1443);
insert into companies (id, company_name, main_country, annual_revenue) values (69, 'FedEx', 'Turkey', 16365.5343);
insert into companies (id, company_name, main_country, annual_revenue) values (70, 'Abbott Laboratories', 'Dominica', 12229.9319);
insert into companies (id, company_name, main_country, annual_revenue) values (71, 'DuPont', 'China', 22380.2838);
insert into companies (id, company_name, main_country, annual_revenue) values (72, 'Google', 'Iran', 82125.4757);
insert into companies (id, company_name, main_country, annual_revenue) values (73, 'Hess', 'Kenya', 3100.9244);
insert into companies (id, company_name, main_country, annual_revenue) values (74, 'Supervalu', 'Chad', 3665.3745);
insert into companies (id, company_name, main_country, annual_revenue) values (75, 'United Continental Holdings', 'Antigua & Deps', 74892.755);
insert into companies (id, company_name, main_country, annual_revenue) values (76, 'Honeywell International', 'Yemen', 47049.369);
insert into companies (id, company_name, main_country, annual_revenue) values (77, 'CHS', 'Malta', 80669.2273);
insert into companies (id, company_name, main_country, annual_revenue) values (78, 'Humana', 'Honduras', 13171.3423);
insert into companies (id, company_name, main_country, annual_revenue) values (79, 'Goldman Sachs Group', 'Uganda', 53162.8188);
insert into companies (id, company_name, main_country, annual_revenue) values (80, 'Ingram Micro', 'Nauru', 93072.4677);
insert into companies (id, company_name, main_country, annual_revenue) values (81, 'Oracle', 'United Arab Emirates', 17163.9637);
insert into companies (id, company_name, main_country, annual_revenue) values (82, 'Delta Air Lines', 'Iraq', 76252.0951);
insert into companies (id, company_name, main_country, annual_revenue) values (83, 'Liberty Mutual Insurance Group', 'Vanuatu', 58116.5237);
insert into companies (id, company_name, main_country, annual_revenue) values (84, 'World Fuel Services', 'Yemen', 4087.0054);
insert into companies (id, company_name, main_country, annual_revenue) values (85, 'New York Life Insurance', 'Lesotho', 71165.1775);
insert into companies (id, company_name, main_country, annual_revenue) values (86, 'Plains All American Pipeline', 'Burkina', 83044.0758);
insert into companies (id, company_name, main_country, annual_revenue) values (87, 'TIAA-CREF', 'Benin', 85027.7383);
insert into companies (id, company_name, main_country, annual_revenue) values (88, 'Aetna', 'Sri Lanka', 46063.7875);
insert into companies (id, company_name, main_country, annual_revenue) values (89, 'Sprint Nextel', 'Ireland {Republic}', 3682.9887);
insert into companies (id, company_name, main_country, annual_revenue) values (90, 'News Corp.', 'Nicaragua', 11074.3667);
insert into companies (id, company_name, main_country, annual_revenue) values (91, 'General Dynamics', 'Palau', 85870.2283);
insert into companies (id, company_name, main_country, annual_revenue) values (92, 'Allstate', 'Mexico', 2237.833);
insert into companies (id, company_name, main_country, annual_revenue) values (93, 'HCA Holdings', 'Netherlands', 2708.3296);
insert into companies (id, company_name, main_country, annual_revenue) values (94, 'American Express', 'Colombia', 66710.3043);
insert into companies (id, company_name, main_country, annual_revenue) values (95, 'Tyson Foods', 'Belarus', 86234.8722);
insert into companies (id, company_name, main_country, annual_revenue) values (96, 'Deere', 'Burkina', 39466.1546);
insert into companies (id, company_name, main_country, annual_revenue) values (97, 'Murphy Oil', 'Sudan', 68925.9371);
insert into companies (id, company_name, main_country, annual_revenue) values (98, 'Philip Morris International', 'Georgia', 25654.1138);
insert into companies (id, company_name, main_country, annual_revenue) values (99, 'Nationwide', 'Armenia', 35385.7849);
insert into companies (id, company_name, main_country, annual_revenue) values (100, 'Tesoro', 'Spain', 12868.5128);
insert into companies (id, company_name, main_country, annual_revenue) values (101, '3M', 'Taiwan', 28755.7151);
insert into companies (id, company_name, main_country, annual_revenue) values (102, 'Time Warner', 'Djibouti', 40210.6259);
insert into companies (id, company_name, main_country, annual_revenue) values (103, 'Northrop Grumman', 'Tanzania', 97498.0478);
insert into companies (id, company_name, main_country, annual_revenue) values (104, 'DirecTV', 'Afghanistan', 89431.1174);
insert into companies (id, company_name, main_country, annual_revenue) values (105, 'Publix Super Markets', 'Suriname', 74121.5505);
insert into companies (id, company_name, main_country, annual_revenue) values (106, 'McDonalds', 'Turkey', 39136.9829);
insert into companies (id, company_name, main_country, annual_revenue) values (107, 'Avnet', 'Djibouti', 75680.5215);
insert into companies (id, company_name, main_country, annual_revenue) values (108, 'Tech Data', 'Guyana', 70950.1203);
insert into companies (id, company_name, main_country, annual_revenue) values (109, 'Macys', 'Vatican City', 23535.418);
insert into companies (id, company_name, main_country, annual_revenue) values (110, 'International Paper', 'Uzbekistan', 92788.9295);
insert into companies (id, company_name, main_country, annual_revenue) values (111, 'Travelers Cos.', 'Gabon', 94624.3752);
insert into companies (id, company_name, main_country, annual_revenue) values (112, 'Rite Aid', 'Singapore', 73566.9639);
insert into companies (id, company_name, main_country, annual_revenue) values (113, 'Staples', 'Bahrain', 26640.7364);
insert into companies (id, company_name, main_country, annual_revenue) values (114, 'Alcoa', 'Sao Tome & Principe', 67309.6155);
insert into companies (id, company_name, main_country, annual_revenue) values (115, 'Northwestern Mutual', 'Grenada', 13409.1859);
insert into companies (id, company_name, main_country, annual_revenue) values (116, 'Raytheon', 'Vanuatu', 21641.5983);
insert into companies (id, company_name, main_country, annual_revenue) values (117, 'Halliburton', 'Botswana', 66216.0467);
insert into companies (id, company_name, main_country, annual_revenue) values (118, 'Eli Lilly', 'Jordan', 68938.495);
insert into companies (id, company_name, main_country, annual_revenue) values (119, 'Emerson Electric', 'Hungary', 75893.3083);
insert into companies (id, company_name, main_country, annual_revenue) values (120, 'Massachusetts Mutual Life Insurance', 'Kazakhstan', 13260.3904);
insert into companies (id, company_name, main_country, annual_revenue) values (121, 'Occidental Petroleum', 'Iceland', 60040.5696);
insert into companies (id, company_name, main_country, annual_revenue) values (122, 'AMR', 'Australia', 88242.4336);
insert into companies (id, company_name, main_country, annual_revenue) values (123, 'Fluor', 'St Lucia', 71981.0397);
insert into companies (id, company_name, main_country, annual_revenue) values (124, 'TJX', 'Taiwan', 81674.3733);
insert into companies (id, company_name, main_country, annual_revenue) values (125, 'Goodyear Tire & Rubber', 'Philippines', 5993.3657);
insert into companies (id, company_name, main_country, annual_revenue) values (126, 'Xerox', 'Costa Rica', 854.3936);
insert into companies (id, company_name, main_country, annual_revenue) values (127, 'Aflac', 'Zimbabwe', 10819.523);
insert into companies (id, company_name, main_country, annual_revenue) values (128, 'Manpower', 'Germany', 55234.4055);
insert into companies (id, company_name, main_country, annual_revenue) values (129, 'Cigna', 'Libya', 12362.8324);
insert into companies (id, company_name, main_country, annual_revenue) values (130, 'Hartford Financial Services Group', 'China', 64723.1085);
insert into companies (id, company_name, main_country, annual_revenue) values (131, 'U.S. Bancorp', 'Grenada', 52520.1881);
insert into companies (id, company_name, main_country, annual_revenue) values (132, 'Arrow Electronics', 'Macedonia', 59368.8115);
insert into companies (id, company_name, main_country, annual_revenue) values (133, 'Bristol-Myers Squibb', 'New Zealand', 68822.5986);
insert into companies (id, company_name, main_country, annual_revenue) values (134, 'Freeport-McMoRan Copper & Gold', 'Barbados', 73751.4099);
insert into companies (id, company_name, main_country, annual_revenue) values (135, 'Nike', 'Armenia', 88192.0573);
insert into companies (id, company_name, main_country, annual_revenue) values (136, 'Kimberly-Clark', 'Maldives', 52999.6855);
insert into companies (id, company_name, main_country, annual_revenue) values (137, 'Nucor', 'Montenegro', 80756.5239);
insert into companies (id, company_name, main_country, annual_revenue) values (138, 'EMC', 'Bahamas', 80554.7372);
insert into companies (id, company_name, main_country, annual_revenue) values (139, 'United States Steel', 'Malta', 23028.5255);
insert into companies (id, company_name, main_country, annual_revenue) values (140, 'Baker Hughes', 'Antigua & Deps', 60485.1949);
insert into companies (id, company_name, main_country, annual_revenue) values (141, 'Time Warner Cable', 'Niger', 28311.8419);
insert into companies (id, company_name, main_country, annual_revenue) values (142, 'Union Pacific', 'Luxembourg', 40661.3946);
insert into companies (id, company_name, main_country, annual_revenue) values (143, 'United Services Automobile Assn.', 'Taiwan', 50068.3349);
insert into companies (id, company_name, main_country, annual_revenue) values (144, 'Exelon', 'Papua New Guinea', 24518.7158);
insert into companies (id, company_name, main_country, annual_revenue) values (145, 'Kohls', 'Cyprus', 70757.1653);
insert into companies (id, company_name, main_country, annual_revenue) values (146, 'Whirlpool', 'Honduras', 39456.8335);
insert into companies (id, company_name, main_country, annual_revenue) values (147, 'Capital One Financial', 'Kenya', 65600.8979);
insert into companies (id, company_name, main_country, annual_revenue) values (148, 'Illinois Tool Works', 'Guatemala', 65476.2739);
insert into companies (id, company_name, main_country, annual_revenue) values (149, 'Cummins', 'Jamaica', 21714.1544);
insert into companies (id, company_name, main_country, annual_revenue) values (150, 'AES', 'Cuba', 70906.3228);
insert into companies (id, company_name, main_country, annual_revenue) values (151, 'Southern', 'Paraguay', 55085.304);
insert into companies (id, company_name, main_country, annual_revenue) values (152, 'J.C. Penney', 'Slovakia', 50769.1567);
insert into companies (id, company_name, main_country, annual_revenue) values (153, 'Apache', 'Syria', 11888.5104);
insert into companies (id, company_name, main_country, annual_revenue) values (154, 'Colgate-Palmolive', 'Oman', 76998.5346);
insert into companies (id, company_name, main_country, annual_revenue) values (155, 'Altria Group', 'South Africa', 26365.4299);
insert into companies (id, company_name, main_country, annual_revenue) values (156, 'Jabil Circuit', 'Georgia', 36080.257);
insert into companies (id, company_name, main_country, annual_revenue) values (157, 'Danaher', 'Cambodia', 59034.1824);
insert into companies (id, company_name, main_country, annual_revenue) values (158, 'Paccar', 'Libya', 99379.4877);
insert into companies (id, company_name, main_country, annual_revenue) values (159, 'FirstEnergy', 'Burkina', 35352.4301);
insert into companies (id, company_name, main_country, annual_revenue) values (160, 'TRW Automotive Holdings', 'Chad', 31621.3526);
insert into companies (id, company_name, main_country, annual_revenue) values (161, 'Computer Sciences', 'Palau', 6396.2856);
insert into companies (id, company_name, main_country, annual_revenue) values (162, 'Eaton', 'Kuwait', 85594.8661);
insert into companies (id, company_name, main_country, annual_revenue) values (163, 'Medtronic', 'Sierra Leone', 31484.5054);
insert into companies (id, company_name, main_country, annual_revenue) values (164, 'PNC Financial Services Group', 'El Salvador', 66129.4088);
insert into companies (id, company_name, main_country, annual_revenue) values (165, 'Bank of New York Mellon Corp.', 'Zambia', 95137.2565);
insert into companies (id, company_name, main_country, annual_revenue) values (166, 'Southwest Airlines', 'Romania', 19928.0516);
insert into companies (id, company_name, main_country, annual_revenue) values (167, 'Amgen', 'Antigua & Deps', 27645.9629);
insert into companies (id, company_name, main_country, annual_revenue) values (168, 'Progressive', 'Iceland', 70999.5276);
insert into companies (id, company_name, main_country, annual_revenue) values (169, 'HollyFrontier', 'Cameroon', 49542.0066);
insert into companies (id, company_name, main_country, annual_revenue) values (170, 'CenturyLink', 'Belarus', 75254.7665);
insert into companies (id, company_name, main_country, annual_revenue) values (171, 'NextEra Energy', 'Seychelles', 25412.7345);
insert into companies (id, company_name, main_country, annual_revenue) values (172, 'Marathon Oil', 'Afghanistan', 79020.4603);
insert into companies (id, company_name, main_country, annual_revenue) values (173, 'L-3 Communications', 'Uganda', 65986.9314);
insert into companies (id, company_name, main_country, annual_revenue) values (174, 'Oneok', 'Cuba', 43767.1708);
insert into companies (id, company_name, main_country, annual_revenue) values (175, 'American Electric Power', 'Kazakhstan', 99872.4892);
insert into companies (id, company_name, main_country, annual_revenue) values (176, 'Viacom', 'Qatar', 21844.8664);
insert into companies (id, company_name, main_country, annual_revenue) values (177, 'Qualcomm', 'Guyana', 37446.7614);
insert into companies (id, company_name, main_country, annual_revenue) values (178, 'PG&E Corp.', 'Indonesia', 98048.2409);
insert into companies (id, company_name, main_country, annual_revenue) values (179, 'PPG Industries', 'Hungary', 5879.0653);
insert into companies (id, company_name, main_country, annual_revenue) values (180, 'General Mills', 'Samoa', 70758.3049);
insert into companies (id, company_name, main_country, annual_revenue) values (181, 'Global Partners', 'Turkmenistan', 3811.5626);
insert into companies (id, company_name, main_country, annual_revenue) values (182, 'Dollar General', 'Fiji', 17289.1331);
insert into companies (id, company_name, main_country, annual_revenue) values (183, 'National Oilwell Varco', 'Namibia', 54599.0656);
insert into companies (id, company_name, main_country, annual_revenue) values (184, 'Gap', 'Palau', 92288.6006);
insert into companies (id, company_name, main_country, annual_revenue) values (185, 'Duke Energy', 'Burundi', 91089.5005);
insert into companies (id, company_name, main_country, annual_revenue) values (186, 'Dominion Resources', 'Italy', 55550.1424);
insert into companies (id, company_name, main_country, annual_revenue) values (187, 'CBS', 'Ghana', 38604.181);
insert into companies (id, company_name, main_country, annual_revenue) values (188, 'Lear', 'Laos', 96767.0975);
insert into companies (id, company_name, main_country, annual_revenue) values (189, 'Loews', 'Bulgaria', 81335.6977);
insert into companies (id, company_name, main_country, annual_revenue) values (190, 'DISH Network', 'Slovenia', 74835.4488);
insert into companies (id, company_name, main_country, annual_revenue) values (191, 'Anadarko Petroleum', 'Cyprus', 74175.5986);
insert into companies (id, company_name, main_country, annual_revenue) values (192, 'Navistar International', 'United Kingdom', 72944.5759);
insert into companies (id, company_name, main_country, annual_revenue) values (193, 'Toys "R" Us', 'Guinea-Bissau', 2106.374);
insert into companies (id, company_name, main_country, annual_revenue) values (194, 'Baxter International', 'Egypt', 96810.0642);
insert into companies (id, company_name, main_country, annual_revenue) values (195, 'Omnicom Group', 'Albania', 80685.1012);
insert into companies (id, company_name, main_country, annual_revenue) values (196, 'AutoNation', 'Cape Verde', 79390.5307);
insert into companies (id, company_name, main_country, annual_revenue) values (197, 'Community Health Systems', 'Pakistan', 1083.8973);
insert into companies (id, company_name, main_country, annual_revenue) values (198, 'Constellation Energy', 'Slovakia', 72478.2408);
insert into companies (id, company_name, main_country, annual_revenue) values (199, 'Texas Instruments', 'Trinidad & Tobago', 62208.5316);
insert into companies (id, company_name, main_country, annual_revenue) values (200, 'Ally Financial', 'Ivory Coast', 84494.3487);
insert into companies (id, company_name, main_country, annual_revenue) values (201, 'Chubb', 'Finland', 60593.9577);
insert into companies (id, company_name, main_country, annual_revenue) values (202, 'Waste Management', 'Sudan', 52452.6106);
insert into companies (id, company_name, main_country, annual_revenue) values (203, 'Aramark', 'Austria', 62682.1494);
insert into companies (id, company_name, main_country, annual_revenue) values (204, 'Kellogg', 'Solomon Islands', 56209.5131);
insert into companies (id, company_name, main_country, annual_revenue) values (205, 'Motorola Mobility Holdings', 'Kenya', 63654.4442);
insert into companies (id, company_name, main_country, annual_revenue) values (206, 'Dean Foods', 'Liechtenstein', 85565.1133);
insert into companies (id, company_name, main_country, annual_revenue) values (207, 'US Airways Group', 'Mozambique', 19692.4727);
insert into companies (id, company_name, main_country, annual_revenue) values (208, 'Consolidated Edison', 'Suriname', 31463.5939);
insert into companies (id, company_name, main_country, annual_revenue) values (209, 'Land OLakes', 'Philippines', 93256.7145);
insert into companies (id, company_name, main_country, annual_revenue) values (210, 'Edison International', 'Palau', 93258.8451);
insert into companies (id, company_name, main_country, annual_revenue) values (211, 'PPL', 'Gabon', 95215.0309);
insert into companies (id, company_name, main_country, annual_revenue) values (212, 'Yum Brands', 'Zimbabwe', 59275.1934);
insert into companies (id, company_name, main_country, annual_revenue) values (213, 'Genuine Parts', 'Russian Federation', 66738.1348);
insert into companies (id, company_name, main_country, annual_revenue) values (214, 'ConAgra Foods', 'Korea North', 18391.0006);
insert into companies (id, company_name, main_country, annual_revenue) values (215, 'Parker Hannifin', 'Nepal', 93850.1738);
insert into companies (id, company_name, main_country, annual_revenue) values (216, 'Marriott International', 'Palau', 57434.3399);
insert into companies (id, company_name, main_country, annual_revenue) values (217, 'Smithfield Foods', 'Tuvalu', 43970.8106);
insert into companies (id, company_name, main_country, annual_revenue) values (218, 'Coventry Health Care', 'Paraguay', 65471.0521);
insert into companies (id, company_name, main_country, annual_revenue) values (219, 'Sara Lee', 'Afghanistan', 91730.0763);
insert into companies (id, company_name, main_country, annual_revenue) values (220, 'Health Net', 'Peru', 21842.3296);
insert into companies (id, company_name, main_country, annual_revenue) values (221, 'Penske Automotive Group', 'Philippines', 11140.5048);
insert into companies (id, company_name, main_country, annual_revenue) values (222, 'Icahn Enterprises', 'Canada', 24558.9009);
insert into companies (id, company_name, main_country, annual_revenue) values (223, 'Monsanto', 'Hungary', 50526.7698);
insert into companies (id, company_name, main_country, annual_revenue) values (224, 'Thermo Fisher Scientific', 'Lithuania', 57883.1477);
insert into companies (id, company_name, main_country, annual_revenue) values (225, 'CSX', 'Turkey', 70235.4017);
insert into companies (id, company_name, main_country, annual_revenue) values (226, 'Starbucks', 'Venezuela', 16265.9263);
insert into companies (id, company_name, main_country, annual_revenue) values (227, 'eBay', 'Guatemala', 98088.5804);
insert into companies (id, company_name, main_country, annual_revenue) values (228, 'Chesapeake Energy', 'Lithuania', 48590.469);
insert into companies (id, company_name, main_country, annual_revenue) values (229, 'Liberty Interactive', 'Poland', 10450.0475);
insert into companies (id, company_name, main_country, annual_revenue) values (230, 'Marsh & McLennan', 'Rwanda', 19844.4536);
insert into companies (id, company_name, main_country, annual_revenue) values (231, 'Devon Energy', 'Spain', 7347.6021);
insert into companies (id, company_name, main_country, annual_revenue) values (232, 'Office Depot', 'Algeria', 60196.5418);
insert into companies (id, company_name, main_country, annual_revenue) values (233, 'Avon Products', 'Saudi Arabia', 82800.7668);
insert into companies (id, company_name, main_country, annual_revenue) values (234, 'Aon', 'India', 25485.1461);
insert into companies (id, company_name, main_country, annual_revenue) values (235, 'Textron', 'Kiribati', 60223.2931);
insert into companies (id, company_name, main_country, annual_revenue) values (236, 'Huntsman', 'Chad', 55343.5536);
insert into companies (id, company_name, main_country, annual_revenue) values (237, 'Praxair', 'Russian Federation', 34316.5411);
insert into companies (id, company_name, main_country, annual_revenue) values (238, 'Entergy', 'Venezuela', 52421.8204);
insert into companies (id, company_name, main_country, annual_revenue) values (239, 'Public Service Enterprise Group', 'Chad', 22974.861);
insert into companies (id, company_name, main_country, annual_revenue) values (240, 'Norfolk Southern', 'Bangladesh', 75352.4171);
insert into companies (id, company_name, main_country, annual_revenue) values (241, 'Nordstrom', 'Bahrain', 27132.2194);
insert into companies (id, company_name, main_country, annual_revenue) values (242, 'First Data', 'Slovakia', 82643.8277);
insert into companies (id, company_name, main_country, annual_revenue) values (243, 'H.J. Heinz', 'Kenya', 81937.2064);
insert into companies (id, company_name, main_country, annual_revenue) values (244, 'SAIC', 'Monaco', 31202.9411);
insert into companies (id, company_name, main_country, annual_revenue) values (245, 'Xcel Energy', 'Ethiopia', 6141.3676);
insert into companies (id, company_name, main_country, annual_revenue) values (246, 'Lincoln National', 'St Kitts & Nevis', 65403.36);
insert into companies (id, company_name, main_country, annual_revenue) values (247, 'Ameriprise Financial', 'Guinea', 59629.7874);
insert into companies (id, company_name, main_country, annual_revenue) values (248, 'R.R. Donnelley & Sons', 'Bolivia', 53696.7134);
insert into companies (id, company_name, main_country, annual_revenue) values (249, 'Guardian Life Ins. Co. of America', 'Azerbaijan', 21833.3414);
insert into companies (id, company_name, main_country, annual_revenue) values (250, 'Applied Materials', 'Japan', 20222.0946);
insert into companies (id, company_name, main_country, annual_revenue) values (251, 'Stanley Black & Decker', 'Laos', 97175.3505);
insert into companies (id, company_name, main_country, annual_revenue) values (252, 'Synnex', 'Vatican City', 78662.7941);
insert into companies (id, company_name, main_country, annual_revenue) values (253, 'Jacobs Engineering Group', 'Barbados', 88969.4468);
insert into companies (id, company_name, main_country, annual_revenue) values (254, 'Peter Kiewit Sons', 'India', 68676.5299);
insert into companies (id, company_name, main_country, annual_revenue) values (255, 'Limited Brands', 'Australia', 93102.0294);
insert into companies (id, company_name, main_country, annual_revenue) values (256, 'Newmont Mining', 'Venezuela', 40272.3598);
insert into companies (id, company_name, main_country, annual_revenue) values (257, 'Genworth Financial', 'Zambia', 81631.3067);
insert into companies (id, company_name, main_country, annual_revenue) values (258, 'C.H. Robinson Worldwide', 'Czech Republic', 65648.1095);
insert into companies (id, company_name, main_country, annual_revenue) values (259, 'Unum Group', 'Honduras', 42144.2925);
insert into companies (id, company_name, main_country, annual_revenue) values (260, 'Liberty Global', 'Tunisia', 49514.8695);
insert into companies (id, company_name, main_country, annual_revenue) values (261, 'State Street Corp.', 'Mexico', 56600.4159);
insert into companies (id, company_name, main_country, annual_revenue) values (262, 'EOG Resources', 'Tuvalu', 82473.0068);
insert into companies (id, company_name, main_country, annual_revenue) values (263, 'Whole Foods Market', 'Cape Verde', 33552.7322);
insert into companies (id, company_name, main_country, annual_revenue) values (264, 'Air Products & Chemicals', 'Samoa', 87580.1252);
insert into companies (id, company_name, main_country, annual_revenue) values (265, 'Sempra Energy', 'Saudi Arabia', 5131.1003);
insert into companies (id, company_name, main_country, annual_revenue) values (266, 'BB&T Corp.', 'Vietnam', 94531.6492);
insert into companies (id, company_name, main_country, annual_revenue) values (267, 'Mosaic', 'Bolivia', 81303.8338);
insert into companies (id, company_name, main_country, annual_revenue) values (268, 'Automatic Data Processing', 'Swaziland', 59312.5066);
insert into companies (id, company_name, main_country, annual_revenue) values (269, 'CDW', 'Ivory Coast', 65774.3347);
insert into companies (id, company_name, main_country, annual_revenue) values (270, 'SunTrust Banks', 'Luxembourg', 99963.9439);
insert into companies (id, company_name, main_country, annual_revenue) values (271, 'Tenet Healthcare', 'Laos', 52636.4239);
insert into companies (id, company_name, main_country, annual_revenue) values (272, 'GameStop', 'Hungary', 40837.5635);
insert into companies (id, company_name, main_country, annual_revenue) values (273, 'Motorola Solutions', 'Afghanistan', 26913.979);
insert into companies (id, company_name, main_country, annual_revenue) values (274, 'URS', 'Bolivia', 46649.3889);
insert into companies (id, company_name, main_country, annual_revenue) values (275, 'Western Digital', 'Indonesia', 12219.9546);
insert into companies (id, company_name, main_country, annual_revenue) values (276, 'VF', 'Mauritania', 44300.9453);
insert into companies (id, company_name, main_country, annual_revenue) values (277, 'Las Vegas Sands', 'Oman', 49498.4562);
insert into companies (id, company_name, main_country, annual_revenue) values (278, 'CarMax', 'Belarus', 65239.7513);
insert into companies (id, company_name, main_country, annual_revenue) values (279, 'KBR', 'Trinidad & Tobago', 83977.978);
insert into companies (id, company_name, main_country, annual_revenue) values (280, 'Visa', 'Korea South', 33736.0638);
insert into companies (id, company_name, main_country, annual_revenue) values (281, 'Enbridge Energy Partners', 'St Kitts & Nevis', 91941.879);
insert into companies (id, company_name, main_country, annual_revenue) values (282, 'BlackRock', 'Sao Tome & Principe', 39697.4021);
insert into companies (id, company_name, main_country, annual_revenue) values (283, 'NRG Energy', 'Ireland {Republic}', 65910.8289);
insert into companies (id, company_name, main_country, annual_revenue) values (284, 'Western Refining', 'Chile', 96679.7442);
insert into companies (id, company_name, main_country, annual_revenue) values (285, 'Progress Energy', 'Armenia', 44541.0364);
insert into companies (id, company_name, main_country, annual_revenue) values (286, 'DTE Energy', 'Ethiopia', 79199.543);
insert into companies (id, company_name, main_country, annual_revenue) values (287, 'Caesars Entertainment', 'Costa Rica', 88415.8715);
insert into companies (id, company_name, main_country, annual_revenue) values (288, 'Reinsurance Group of America', 'Togo', 63226.2741);
insert into companies (id, company_name, main_country, annual_revenue) values (289, 'Estée Lauder', 'France', 56373.6668);
insert into companies (id, company_name, main_country, annual_revenue) values (290, 'Micron Technology', 'Solomon Islands', 98659.5061);
insert into companies (id, company_name, main_country, annual_revenue) values (291, 'AGCO', 'East Timor', 63905.9335);
insert into companies (id, company_name, main_country, annual_revenue) values (292, 'Sherwin-Williams', 'Romania', 13514.1854);
insert into companies (id, company_name, main_country, annual_revenue) values (293, 'Bed Bath & Beyond', 'Syria', 40160.1685);
insert into companies (id, company_name, main_country, annual_revenue) values (294, 'Principal Financial', 'Afghanistan', 36737.239);
insert into companies (id, company_name, main_country, annual_revenue) values (295, 'Crown Holdings', 'United States', 10628.2335);
insert into companies (id, company_name, main_country, annual_revenue) values (296, 'Ball', 'Kenya', 38862.0952);
insert into companies (id, company_name, main_country, annual_revenue) values (297, 'Owens & Minor', 'Bahrain', 96593.5777);
insert into companies (id, company_name, main_country, annual_revenue) values (298, 'Ross Stores', 'Ecuador', 99601.3637);
insert into companies (id, company_name, main_country, annual_revenue) values (299, 'Discover Financial Services', 'Spain', 99092.9184);
insert into companies (id, company_name, main_country, annual_revenue) values (300, 'Family Dollar Stores', 'Azerbaijan', 55018.2163);
insert into companies (id, company_name, main_country, annual_revenue) values (301, 'Reynolds American', 'Palau', 43455.7775);
insert into companies (id, company_name, main_country, annual_revenue) values (302, 'Henry Schein', 'Panama', 61251.2717);
insert into companies (id, company_name, main_country, annual_revenue) values (303, 'Dover', 'Brunei', 77786.5033);
insert into companies (id, company_name, main_country, annual_revenue) values (304, 'CenterPoint Energy', 'Georgia', 55515.8096);
insert into companies (id, company_name, main_country, annual_revenue) values (305, 'Gilead Sciences', 'Lebanon', 2052.6769);
insert into companies (id, company_name, main_country, annual_revenue) values (306, 'Ashland', 'Ghana', 58997.2188);
insert into companies (id, company_name, main_country, annual_revenue) values (307, 'Stryker', 'Egypt', 93101.0839);
insert into companies (id, company_name, main_country, annual_revenue) values (308, 'Hertz Global Holdings', 'Somalia', 437.067);
insert into companies (id, company_name, main_country, annual_revenue) values (309, 'Assurant', 'Finland', 97012.2038);
insert into companies (id, company_name, main_country, annual_revenue) values (310, 'Kinder Morgan', 'Mauritius', 25445.7929);
insert into companies (id, company_name, main_country, annual_revenue) values (311, 'Energy Transfer Equity', 'Namibia', 18732.8463);
insert into companies (id, company_name, main_country, annual_revenue) values (312, 'Autoliv', 'Taiwan', 22644.9205);
insert into companies (id, company_name, main_country, annual_revenue) values (313, 'Republic Services', 'Tonga', 22658.9739);
insert into companies (id, company_name, main_country, annual_revenue) values (314, 'Reliance Steel & Aluminum', 'Finland', 53519.5841);
insert into companies (id, company_name, main_country, annual_revenue) values (315, 'Peabody Energy', 'Gambia', 31559.9162);
insert into companies (id, company_name, main_country, annual_revenue) values (316, 'Great Atlantic & Pacific Tea', 'Zambia', 59078.2396);
insert into companies (id, company_name, main_country, annual_revenue) values (317, 'W.W. Grainger', 'Ireland {Republic}', 5175.2551);
insert into companies (id, company_name, main_country, annual_revenue) values (318, 'Goodrich', 'Kosovo', 29102.468);
insert into companies (id, company_name, main_country, annual_revenue) values (319, 'AutoZone', 'Kosovo', 52970.3453);
insert into companies (id, company_name, main_country, annual_revenue) values (320, 'Visteon', 'Brunei', 77321.2333);
insert into companies (id, company_name, main_country, annual_revenue) values (321, 'AECOM Technology', 'Micronesia', 72675.4125);
insert into companies (id, company_name, main_country, annual_revenue) values (322, 'Steel Dynamics', 'Turkey', 34049.9551);
insert into companies (id, company_name, main_country, annual_revenue) values (323, 'Coca-Cola Enterprises', 'Norway', 23214.1101);
insert into companies (id, company_name, main_country, annual_revenue) values (324, 'Williams', 'Trinidad & Tobago', 17127.0513);
insert into companies (id, company_name, main_country, annual_revenue) values (325, 'Commercial Metals', 'Guatemala', 90192.1042);
insert into companies (id, company_name, main_country, annual_revenue) values (326, 'Hormel Foods', 'Montenegro', 19066.7504);
insert into companies (id, company_name, main_country, annual_revenue) values (327, 'Corning', 'Spain', 69411.4261);
insert into companies (id, company_name, main_country, annual_revenue) values (328, 'TravelCenters of America', 'Sri Lanka', 10221.9329);
insert into companies (id, company_name, main_country, annual_revenue) values (329, 'Sonic Automotive', 'Togo', 87067.0996);
insert into companies (id, company_name, main_country, annual_revenue) values (330, 'MGM Resorts International', 'Micronesia', 20638.5166);
insert into companies (id, company_name, main_country, annual_revenue) values (331, 'Thrivent Financial for Lutherans', 'Madagascar', 61257.1895);
insert into companies (id, company_name, main_country, annual_revenue) values (332, 'Becton Dickinson', 'Canada', 23957.3129);
insert into companies (id, company_name, main_country, annual_revenue) values (333, 'Campbell Soup', 'Germany', 89611.064);
insert into companies (id, company_name, main_country, annual_revenue) values (334, 'Boston Scientific', 'Cyprus', 53498.1556);
insert into companies (id, company_name, main_country, annual_revenue) values (335, 'Dana Holding', 'Cameroon', 27830.5655);
insert into companies (id, company_name, main_country, annual_revenue) values (336, 'Oshkosh', 'Benin', 26357.8514);
insert into companies (id, company_name, main_country, annual_revenue) values (337, 'Masco', 'Uganda', 92343.6042);
insert into companies (id, company_name, main_country, annual_revenue) values (338, 'Universal Health Services', 'Peru', 70087.2375);
insert into companies (id, company_name, main_country, annual_revenue) values (339, 'Ameren', 'Cambodia', 33349.7486);
insert into companies (id, company_name, main_country, annual_revenue) values (340, 'Quest Diagnostics', 'Israel', 24842.589);
insert into companies (id, company_name, main_country, annual_revenue) values (341, 'Darden Restaurants', 'China', 53122.9476);
insert into companies (id, company_name, main_country, annual_revenue) values (342, 'Regions Financial', 'Gambia', 2832.9276);
insert into companies (id, company_name, main_country, annual_revenue) values (343, 'Broadcom', 'Malawi', 83589.4147);
insert into companies (id, company_name, main_country, annual_revenue) values (344, 'Owens-Illinois', 'Antigua & Deps', 46502.8349);
insert into companies (id, company_name, main_country, annual_revenue) values (345, 'Eastman Chemical', 'Andorra', 96791.3776);
insert into companies (id, company_name, main_country, annual_revenue) values (346, 'Pantry', 'Eritrea', 24273.0706);
insert into companies (id, company_name, main_country, annual_revenue) values (347, 'Cablevision Systems', 'Guatemala', 92175.2891);
insert into companies (id, company_name, main_country, annual_revenue) values (348, 'Dole Food', 'Swaziland', 96415.5636);
insert into companies (id, company_name, main_country, annual_revenue) values (349, 'Tenneco', 'Liberia', 95456.6957);
insert into companies (id, company_name, main_country, annual_revenue) values (350, 'Charter Communications', 'Chile', 97922.5926);
insert into companies (id, company_name, main_country, annual_revenue) values (351, 'Spectrum Group International', 'Macedonia', 63824.1178);
insert into companies (id, company_name, main_country, annual_revenue) values (352, 'Franklin Resources', 'Central African Rep', 75307.1076);
insert into companies (id, company_name, main_country, annual_revenue) values (353, 'OfficeMax', 'Solomon Islands', 14077.3576);
insert into companies (id, company_name, main_country, annual_revenue) values (354, 'BorgWarner', 'Kyrgyzstan', 10918.3733);
insert into companies (id, company_name, main_country, annual_revenue) values (355, 'Alpha Natural Resources', 'Bahrain', 19119.4303);
insert into companies (id, company_name, main_country, annual_revenue) values (356, 'Energy Future Holdings', 'Lebanon', 34957.1869);
insert into companies (id, company_name, main_country, annual_revenue) values (357, 'Interpublic Group', 'Niger', 51294.4176);
insert into companies (id, company_name, main_country, annual_revenue) values (358, 'DaVita', 'Congo {Democratic Rep}', 49483.1159);
insert into companies (id, company_name, main_country, annual_revenue) values (359, 'Barnes & Noble', 'Liberia', 58172.9367);
insert into companies (id, company_name, main_country, annual_revenue) values (360, 'Targa Resources', 'Argentina', 82132.1224);
insert into companies (id, company_name, main_country, annual_revenue) values (361, 'Cameron International', 'Bosnia Herzegovina', 35166.7653);
insert into companies (id, company_name, main_country, annual_revenue) values (362, 'Winn-Dixie Stores', 'Italy', 49265.5807);
insert into companies (id, company_name, main_country, annual_revenue) values (363, 'Calpine', 'Taiwan', 29499.2085);
insert into companies (id, company_name, main_country, annual_revenue) values (364, 'Ecolab', 'Madagascar', 1232.8767);
insert into companies (id, company_name, main_country, annual_revenue) values (365, 'Cliffs Natural Resources', 'Vanuatu', 86633.9179);
insert into companies (id, company_name, main_country, annual_revenue) values (366, 'Avery Dennison', 'Zimbabwe', 90034.4415);
insert into companies (id, company_name, main_country, annual_revenue) values (367, 'Celanese', 'China', 46158.6905);
insert into companies (id, company_name, main_country, annual_revenue) values (368, 'NII Holdings', 'Brunei', 93116.9056);
insert into companies (id, company_name, main_country, annual_revenue) values (369, 'MasterCard', 'Venezuela', 18660.5356);
insert into companies (id, company_name, main_country, annual_revenue) values (370, 'Jarden', 'Philippines', 10288.3415);
insert into companies (id, company_name, main_country, annual_revenue) values (371, 'Fifth Third Bancorp', 'Bosnia Herzegovina', 73929.5934);
insert into companies (id, company_name, main_country, annual_revenue) values (372, 'Dollar Tree', 'Ethiopia', 98588.0107);
insert into companies (id, company_name, main_country, annual_revenue) values (373, 'Weyerhaeuser', 'Samoa', 97197.0846);
insert into companies (id, company_name, main_country, annual_revenue) values (374, 'Agilent Technologies', 'Honduras', 47040.5626);
insert into companies (id, company_name, main_country, annual_revenue) values (375, 'Sanmina-SCI', 'United States', 95703.9132);
insert into companies (id, company_name, main_country, annual_revenue) values (376, 'NuStar Energy', 'Bhutan', 17846.3946);
insert into companies (id, company_name, main_country, annual_revenue) values (377, 'Advanced Micro Devices', 'Venezuela', 69540.041);
insert into companies (id, company_name, main_country, annual_revenue) values (378, 'Terex', 'Denmark', 85374.7957);
insert into companies (id, company_name, main_country, annual_revenue) values (379, 'CMS Energy', 'India', 76871.3015);
insert into companies (id, company_name, main_country, annual_revenue) values (380, 'AK Steel Holding', 'Colombia', 61405.2665);
insert into companies (id, company_name, main_country, annual_revenue) values (381, 'American Family Insurance Group', 'Gambia', 31144.272);
insert into companies (id, company_name, main_country, annual_revenue) values (382, 'Dillards', 'Congo', 29577.9199);
insert into companies (id, company_name, main_country, annual_revenue) values (383, 'McGraw-Hill', 'Kenya', 87862.2472);
insert into companies (id, company_name, main_country, annual_revenue) values (384, 'Amerigroup', 'Zimbabwe', 6008.2774);
insert into companies (id, company_name, main_country, annual_revenue) values (385, 'Anixter International', 'Tunisia', 4804.5598);
insert into companies (id, company_name, main_country, annual_revenue) values (386, 'Precision Castparts', 'Tajikistan', 94589.1015);
insert into companies (id, company_name, main_country, annual_revenue) values (387, 'Mattel', 'Japan', 13869.2536);
insert into companies (id, company_name, main_country, annual_revenue) values (388, 'Omnicare', 'Laos', 39619.2621);
insert into companies (id, company_name, main_country, annual_revenue) values (389, 'Corn Products International', 'Eritrea', 40277.7818);
insert into companies (id, company_name, main_country, annual_revenue) values (390, 'Symantec', 'Solomon Islands', 99353.9551);
insert into companies (id, company_name, main_country, annual_revenue) values (391, 'Advance Auto Parts', 'Mozambique', 63084.7985);
insert into companies (id, company_name, main_country, annual_revenue) values (392, 'Core-Mark Holding', 'Nepal', 95862.8471);
insert into companies (id, company_name, main_country, annual_revenue) values (393, 'CC Media Holdings', 'Korea South', 16137.2836);
insert into companies (id, company_name, main_country, annual_revenue) values (394, 'Expeditors International of Washington', 'Cuba', 98542.4368);
insert into companies (id, company_name, main_country, annual_revenue) values (395, 'Mylan', 'Fiji', 93016.4559);
insert into companies (id, company_name, main_country, annual_revenue) values (396, 'Wesco International', 'Slovenia', 97732.3613);
insert into companies (id, company_name, main_country, annual_revenue) values (397, 'Cognizant Technology Solutions', 'Spain', 47550.0521);
insert into companies (id, company_name, main_country, annual_revenue) values (398, 'Consol Energy', 'Madagascar', 40342.5009);
insert into companies (id, company_name, main_country, annual_revenue) values (399, 'PetSmart', 'Turkmenistan', 63631.17);
insert into companies (id, company_name, main_country, annual_revenue) values (400, 'WellCare Health Plans', 'Slovenia', 61349.9853);
insert into companies (id, company_name, main_country, annual_revenue) values (401, 'CF Industries Holdings', 'Japan', 2971.7992);
insert into companies (id, company_name, main_country, annual_revenue) values (402, 'UGI', 'Iran', 2867.1074);
insert into companies (id, company_name, main_country, annual_revenue) values (403, 'Hershey', 'Cameroon', 45924.6601);
insert into companies (id, company_name, main_country, annual_revenue) values (404, 'Group 1 Automotive', 'Bhutan', 87397.1242);
insert into companies (id, company_name, main_country, annual_revenue) values (405, 'MeadWestvaco', 'Morocco', 58988.3765);
insert into companies (id, company_name, main_country, annual_revenue) values (406, 'Ryder System', 'Peru', 66565.6457);
insert into companies (id, company_name, main_country, annual_revenue) values (407, 'Eastman Kodak', 'Denmark', 99394.4475);
insert into companies (id, company_name, main_country, annual_revenue) values (408, 'NiSource', 'Jordan', 67452.196);
insert into companies (id, company_name, main_country, annual_revenue) values (409, 'Rockwell Automation', 'Vatican City', 49353.5138);
insert into companies (id, company_name, main_country, annual_revenue) values (410, 'Mutual of Omaha Insurance', 'Austria', 71204.2578);
insert into companies (id, company_name, main_country, annual_revenue) values (411, 'Shaw Group', 'Ireland {Republic}', 87037.7431);
insert into companies (id, company_name, main_country, annual_revenue) values (412, 'Harris', 'Moldova', 84699.9044);
insert into companies (id, company_name, main_country, annual_revenue) values (413, 'Newell Rubbermaid', 'Ukraine', 77345.6016);
insert into companies (id, company_name, main_country, annual_revenue) values (414, 'Pepco Holdings', 'Qatar', 16865.7212);
insert into companies (id, company_name, main_country, annual_revenue) values (415, 'CBRE Group', 'Belize', 95161.6599);
insert into companies (id, company_name, main_country, annual_revenue) values (416, 'Dr Pepper Snapple Group', 'Ghana', 43567.1192);
insert into companies (id, company_name, main_country, annual_revenue) values (417, 'Avis Budget Group', 'Iceland', 1077.3731);
insert into companies (id, company_name, main_country, annual_revenue) values (418, 'PVH', 'Barbados', 55056.7155);
insert into companies (id, company_name, main_country, annual_revenue) values (419, 'Pacific Life', 'Angola', 86163.4956);
insert into companies (id, company_name, main_country, annual_revenue) values (420, 'General Cable', 'Suriname', 87965.8509);
insert into companies (id, company_name, main_country, annual_revenue) values (421, 'Exelis', 'Libya', 54739.305);
insert into companies (id, company_name, main_country, annual_revenue) values (422, 'Health Management Associates', 'Lithuania', 92736.7699);
insert into companies (id, company_name, main_country, annual_revenue) values (423, 'OReilly Automotive', 'Yemen', 33339.4231);
insert into companies (id, company_name, main_country, annual_revenue) values (424, 'Fidelity National Information Services', 'San Marino', 61602.4263);
insert into companies (id, company_name, main_country, annual_revenue) values (425, 'SLM', 'Central African Rep', 55290.5752);
insert into companies (id, company_name, main_country, annual_revenue) values (426, 'Seaboard', 'Uruguay', 43991.8857);
insert into companies (id, company_name, main_country, annual_revenue) values (427, 'Emcor Group', 'United Kingdom', 8818.6586);
insert into companies (id, company_name, main_country, annual_revenue) values (428, 'Auto-Owners Insurance', 'Uruguay', 47681.8803);
insert into companies (id, company_name, main_country, annual_revenue) values (429, 'SanDisk', 'Somalia', 55224.8313);
insert into companies (id, company_name, main_country, annual_revenue) values (430, 'Ralph Lauren', 'Congo', 20211.6385);
insert into companies (id, company_name, main_country, annual_revenue) values (431, 'Mohawk Industries', 'Bosnia Herzegovina', 29776.3842);
insert into companies (id, company_name, main_country, annual_revenue) values (432, 'Sealed Air', 'Libya', 88272.6584);
insert into companies (id, company_name, main_country, annual_revenue) values (433, 'Starwood Hotels & Resorts', 'Thailand', 91923.5419);
insert into companies (id, company_name, main_country, annual_revenue) values (434, 'Foot Locker', 'Switzerland', 2018.9032);
insert into companies (id, company_name, main_country, annual_revenue) values (435, 'Domtar', 'Chile', 94972.7768);
insert into companies (id, company_name, main_country, annual_revenue) values (436, 'St. Jude Medical', 'Georgia', 53673.2808);
insert into companies (id, company_name, main_country, annual_revenue) values (437, 'Spectra Energy', 'Cyprus', 33553.8948);
insert into companies (id, company_name, main_country, annual_revenue) values (438, 'Booz Allen Hamilton Holding', 'Tonga', 65809.3048);
insert into companies (id, company_name, main_country, annual_revenue) values (439, 'CH2M Hill', 'Somalia', 77573.695);
insert into companies (id, company_name, main_country, annual_revenue) values (440, 'Kelly Services', 'Oman', 29784.6648);
insert into companies (id, company_name, main_country, annual_revenue) values (441, 'Avaya', 'Honduras', 89233.0416);
insert into companies (id, company_name, main_country, annual_revenue) values (442, 'Laboratory Corp. of America', 'Cameroon', 32084.6179);
insert into companies (id, company_name, main_country, annual_revenue) values (443, 'Kindred Healthcare', 'Bulgaria', 54378.1143);
insert into companies (id, company_name, main_country, annual_revenue) values (444, 'Western Union', 'Croatia', 90770.692);
insert into companies (id, company_name, main_country, annual_revenue) values (445, 'SPX', 'Italy', 19598.712);
insert into companies (id, company_name, main_country, annual_revenue) values (446, 'NCR', 'Senegal', 68527.7198);
insert into companies (id, company_name, main_country, annual_revenue) values (447, 'Allergan', 'United States', 79818.0879);
insert into companies (id, company_name, main_country, annual_revenue) values (448, 'Rock-Tenn', 'Guinea', 15171.5522);
insert into companies (id, company_name, main_country, annual_revenue) values (449, 'Live Nation Entertainment', 'Jamaica', 71186.2957);
insert into companies (id, company_name, main_country, annual_revenue) values (450, 'Graybar Electric', 'Israel', 53960.0758);
insert into companies (id, company_name, main_country, annual_revenue) values (451, 'Momentive Specialty Chemicals', 'Belize', 55716.4342);
insert into companies (id, company_name, main_country, annual_revenue) values (452, 'Centene', 'Tanzania', 59133.5154);
insert into companies (id, company_name, main_country, annual_revenue) values (453, 'Owens Corning', 'Indonesia', 7857.0307);
insert into companies (id, company_name, main_country, annual_revenue) values (454, 'Catalyst Health Solutions', 'Denmark', 67855.78);
insert into companies (id, company_name, main_country, annual_revenue) values (455, 'Clorox', 'Vietnam', 61000.4647);
insert into companies (id, company_name, main_country, annual_revenue) values (456, 'Bemis', 'Brazil', 97830.6342);
insert into companies (id, company_name, main_country, annual_revenue) values (457, 'Harley-Davidson', 'Bolivia', 58064.2929);
insert into companies (id, company_name, main_country, annual_revenue) values (458, 'Con-way', 'Switzerland', 74097.5738);
insert into companies (id, company_name, main_country, annual_revenue) values (459, 'Insight Enterprises', 'Germany', 39016.5611);
insert into companies (id, company_name, main_country, annual_revenue) values (460, 'Pitney Bowes', 'Croatia', 98468.1669);
insert into companies (id, company_name, main_country, annual_revenue) values (461, 'Wynn Resorts', 'Venezuela', 87053.6055);
insert into companies (id, company_name, main_country, annual_revenue) values (462, 'BrightPoint', 'Pakistan', 34519.1767);
insert into companies (id, company_name, main_country, annual_revenue) values (463, 'Frontier Communications', 'Bangladesh', 93665.2012);
insert into companies (id, company_name, main_country, annual_revenue) values (464, 'Gannett', 'Sweden', 93873.7053);
insert into companies (id, company_name, main_country, annual_revenue) values (465, 'Dicks Sporting Goods', 'Uzbekistan', 41548.5119);
insert into companies (id, company_name, main_country, annual_revenue) values (466, 'Big Lots', 'Mauritania', 1012.8359);
insert into companies (id, company_name, main_country, annual_revenue) values (467, 'Allegheny Technologies', 'Algeria', 43759.7425);
insert into companies (id, company_name, main_country, annual_revenue) values (468, 'Telephone & Data Systems', 'Armenia', 24796.7384);
insert into companies (id, company_name, main_country, annual_revenue) values (469, 'Timken', 'Kenya', 59834.7472);
insert into companies (id, company_name, main_country, annual_revenue) values (470, 'W.R. Berkley', 'Latvia', 16763.8967);
insert into companies (id, company_name, main_country, annual_revenue) values (471, 'Fidelity National Financial', 'Tuvalu', 54152.4813);
insert into companies (id, company_name, main_country, annual_revenue) values (472, 'Caseys General Stores', 'Micronesia', 60106.6957);
insert into companies (id, company_name, main_country, annual_revenue) values (473, 'NetApp', 'Australia', 47848.6594);
insert into companies (id, company_name, main_country, annual_revenue) values (474, 'FMC Technologies', 'Saint Vincent & the Grenadines', 83504.4109);
insert into companies (id, company_name, main_country, annual_revenue) values (475, 'Biogen Idec', 'Swaziland', 37138.0562);
insert into companies (id, company_name, main_country, annual_revenue) values (476, 'CVR Energy', 'Jamaica', 56149.9268);
insert into companies (id, company_name, main_country, annual_revenue) values (477, 'United Stationers', 'Nigeria', 1352.6829);
insert into companies (id, company_name, main_country, annual_revenue) values (478, 'Host Hotels & Resorts', 'Jamaica', 59339.5293);
insert into companies (id, company_name, main_country, annual_revenue) values (479, 'SunGard Data Systems', 'United Arab Emirates', 85499.5022);
insert into companies (id, company_name, main_country, annual_revenue) values (480, 'Meritor', 'Austria', 85314.4298);
insert into companies (id, company_name, main_country, annual_revenue) values (481, 'Western & Southern Financial Group', 'Korea South', 39776.4583);
insert into companies (id, company_name, main_country, annual_revenue) values (482, 'Yahoo', 'Korea North', 91994.0039);
insert into companies (id, company_name, main_country, annual_revenue) values (483, 'Vanguard Health Systems', 'Albania', 93021.6518);
insert into companies (id, company_name, main_country, annual_revenue) values (484, 'Charles Schwab', 'Trinidad & Tobago', 18510.9388);
insert into companies (id, company_name, main_country, annual_revenue) values (485, 'Susser Holdings', 'Russian Federation', 12915.6924);
insert into companies (id, company_name, main_country, annual_revenue) values (486, 'YRC Worldwide', 'Chile', 93113.6551);
insert into companies (id, company_name, main_country, annual_revenue) values (487, 'El Paso', 'Czech Republic', 54161.6637);
insert into companies (id, company_name, main_country, annual_revenue) values (488, 'CIT Group', 'Benin', 27117.1257);
insert into companies (id, company_name, main_country, annual_revenue) values (489, 'MetroPCS Communications', 'Iran', 84594.8771);
insert into companies (id, company_name, main_country, annual_revenue) values (490, 'Alliant Techsystems', 'Iran', 25826.5171);
insert into companies (id, company_name, main_country, annual_revenue) values (491, 'Celgene', 'Somalia', 93030.7946);
insert into companies (id, company_name, main_country, annual_revenue) values (492, 'MRC Global', 'Palau', 75316.2151);
insert into companies (id, company_name, main_country, annual_revenue) values (493, 'Aleris', 'Iraq', 35295.1509);
insert into companies (id, company_name, main_country, annual_revenue) values (494, 'J.M. Smucker', 'Armenia', 73922.9406);
insert into companies (id, company_name, main_country, annual_revenue) values (495, 'Rockwell Collins', 'South Africa', 1900.7544);
insert into companies (id, company_name, main_country, annual_revenue) values (496, 'Erie Insurance Group', 'Uzbekistan', 68726.0753);
insert into companies (id, company_name, main_country, annual_revenue) values (497, 'Nash-Finch', 'Marshall Islands', 26503.3755);
insert into companies (id, company_name, main_country, annual_revenue) values (498, 'KeyCorp', 'Syria', 90982.2264);
insert into companies (id, company_name, main_country, annual_revenue) values (499, 'Molina Healthcare', 'Bahrain', 10929.1956);
