insert into companies (id, company_name, main_country, annual_revenue) values (0, 'Exxon Mobil', 'Zambia', 71514.866);
insert into companies (id, company_name, main_country, annual_revenue) values (1, 'Wal-Mart Stores', 'Colombia', 43589.1065);
insert into companies (id, company_name, main_country, annual_revenue) values (2, 'Chevron', 'Sao Tome & Principe', 32430.7971);
insert into companies (id, company_name, main_country, annual_revenue) values (3, 'ConocoPhillips', 'Zimbabwe', 30933.7868);
insert into companies (id, company_name, main_country, annual_revenue) values (4, 'General Motors', 'Congo', 37436.4658);
insert into companies (id, company_name, main_country, annual_revenue) values (5, 'General Electric', 'Malta', 4150.824);
insert into companies (id, company_name, main_country, annual_revenue) values (6, 'Berkshire Hathaway', 'Papua New Guinea', 45264.7809);
insert into companies (id, company_name, main_country, annual_revenue) values (7, 'Fannie Mae', 'Bangladesh', 9996.2877);
insert into companies (id, company_name, main_country, annual_revenue) values (8, 'Ford Motor', 'Syria', 28481.3353);
insert into companies (id, company_name, main_country, annual_revenue) values (9, 'Hewlett-Packard', 'Sweden', 89586.0046);
insert into companies (id, company_name, main_country, annual_revenue) values (10, 'AT&T', 'Pakistan', 53440.5812);
insert into companies (id, company_name, main_country, annual_revenue) values (11, 'Valero Energy', 'Vanuatu', 77135.2329);
insert into companies (id, company_name, main_country, annual_revenue) values (12, 'Bank of America Corp.', 'Maldives', 38624.1583);
insert into companies (id, company_name, main_country, annual_revenue) values (13, 'McKesson', 'China', 46824.0113);
insert into companies (id, company_name, main_country, annual_revenue) values (14, 'Verizon Communications', 'Togo', 10781.374);
insert into companies (id, company_name, main_country, annual_revenue) values (15, 'J.P. Morgan Chase & Co.', 'Kazakhstan', 45370.7906);
insert into companies (id, company_name, main_country, annual_revenue) values (16, 'Apple', 'Philippines', 86102.7422);
insert into companies (id, company_name, main_country, annual_revenue) values (17, 'CVS Caremark', 'Myanmar, {Burma}', 74577.6332);
insert into companies (id, company_name, main_country, annual_revenue) values (18, 'International Business Machines', 'Andorra', 37430.4956);
insert into companies (id, company_name, main_country, annual_revenue) values (19, 'Citigroup', 'South Africa', 65986.0441);
insert into companies (id, company_name, main_country, annual_revenue) values (20, 'Cardinal Health', 'St Lucia', 33229.2828);
insert into companies (id, company_name, main_country, annual_revenue) values (21, 'UnitedHealth Group', 'Mauritania', 77852.7542);
insert into companies (id, company_name, main_country, annual_revenue) values (22, 'Kroger', 'Grenada', 36878.689);
insert into companies (id, company_name, main_country, annual_revenue) values (23, 'Costco Wholesale', 'Guatemala', 29973.0391);
insert into companies (id, company_name, main_country, annual_revenue) values (24, 'Freddie Mac', 'Cameroon', 55682.205);
insert into companies (id, company_name, main_country, annual_revenue) values (25, 'Wells Fargo', 'Samoa', 26643.4334);
insert into companies (id, company_name, main_country, annual_revenue) values (26, 'Procter & Gamble', 'Azerbaijan', 56723.5415);
insert into companies (id, company_name, main_country, annual_revenue) values (27, 'Archer Daniels Midland', 'Canada', 50582.5017);
insert into companies (id, company_name, main_country, annual_revenue) values (28, 'AmerisourceBergen', 'Palau', 71377.8643);
insert into companies (id, company_name, main_country, annual_revenue) values (29, 'INTL FCStone', 'Finland', 93361.132);
insert into companies (id, company_name, main_country, annual_revenue) values (30, 'Marathon Petroleum', 'Serbia', 52374.3202);
insert into companies (id, company_name, main_country, annual_revenue) values (31, 'Walgreen', 'Azerbaijan', 62778.2729);
insert into companies (id, company_name, main_country, annual_revenue) values (32, 'American International Group', 'Austria', 54889.2602);
insert into companies (id, company_name, main_country, annual_revenue) values (33, 'MetLife', 'Paraguay', 39881.1232);
insert into companies (id, company_name, main_country, annual_revenue) values (34, 'Home Depot', 'Iraq', 78685.2168);
insert into companies (id, company_name, main_country, annual_revenue) values (35, 'Medco Health Solutions', 'Senegal', 29639.579);
insert into companies (id, company_name, main_country, annual_revenue) values (36, 'Microsoft', 'India', 27514.0746);
insert into companies (id, company_name, main_country, annual_revenue) values (37, 'Target', 'Bhutan', 86292.5975);
insert into companies (id, company_name, main_country, annual_revenue) values (38, 'Boeing', 'Grenada', 75442.8782);
insert into companies (id, company_name, main_country, annual_revenue) values (39, 'Pfizer', 'Moldova', 59472.2025);
insert into companies (id, company_name, main_country, annual_revenue) values (40, 'PepsiCo', 'Myanmar, {Burma}', 78742.2431);
insert into companies (id, company_name, main_country, annual_revenue) values (41, 'Johnson & Johnson', 'Kosovo', 35029.1263);
insert into companies (id, company_name, main_country, annual_revenue) values (42, 'State Farm Insurance Cos.', 'Mali', 33635.8302);
insert into companies (id, company_name, main_country, annual_revenue) values (43, 'Dell', 'Samoa', 66588.4949);
insert into companies (id, company_name, main_country, annual_revenue) values (44, 'WellPoint', 'Dominica', 65051.8919);
insert into companies (id, company_name, main_country, annual_revenue) values (45, 'Caterpillar', 'Moldova', 94347.0775);
insert into companies (id, company_name, main_country, annual_revenue) values (46, 'Dow Chemical', 'Sierra Leone', 54111.1204);
insert into companies (id, company_name, main_country, annual_revenue) values (47, 'United Technologies', 'Myanmar, {Burma}', 89104.96);
insert into companies (id, company_name, main_country, annual_revenue) values (48, 'Comcast', 'Comoros', 10153.149);
insert into companies (id, company_name, main_country, annual_revenue) values (49, 'Kraft Foods', 'Tuvalu', 73990.3151);
insert into companies (id, company_name, main_country, annual_revenue) values (50, 'Intel', 'Palau', 45318.7898);
insert into companies (id, company_name, main_country, annual_revenue) values (51, 'United Parcel Service', 'Argentina', 61134.6866);
insert into companies (id, company_name, main_country, annual_revenue) values (52, 'Best Buy', 'Congo', 96640.2324);
insert into companies (id, company_name, main_country, annual_revenue) values (53, 'Lowes', 'Iran', 60393.6984);
insert into companies (id, company_name, main_country, annual_revenue) values (54, 'Prudential Financial', 'Latvia', 65077.3609);
insert into companies (id, company_name, main_country, annual_revenue) values (55, 'Amazon.com', 'Korea South', 9102.3016);
insert into companies (id, company_name, main_country, annual_revenue) values (56, 'Merck', 'Eritrea', 54010.9087);
insert into companies (id, company_name, main_country, annual_revenue) values (57, 'Lockheed Martin', 'Argentina', 84908.967);
insert into companies (id, company_name, main_country, annual_revenue) values (58, 'Coca-Cola', 'Guatemala', 69209.3758);
insert into companies (id, company_name, main_country, annual_revenue) values (59, 'Express Scripts Holding', 'Honduras', 86889.4067);
insert into companies (id, company_name, main_country, annual_revenue) values (60, 'Sunoco', 'Iraq', 70194.5905);
insert into companies (id, company_name, main_country, annual_revenue) values (61, 'Enterprise Products Partners', 'Botswana', 18010.0131);
insert into companies (id, company_name, main_country, annual_revenue) values (62, 'Safeway', 'Benin', 88824.6393);
insert into companies (id, company_name, main_country, annual_revenue) values (63, 'Cisco Systems', 'Hungary', 97423.8142);
insert into companies (id, company_name, main_country, annual_revenue) values (64, 'Sears Holdings', 'Fiji', 79924.2005);
insert into companies (id, company_name, main_country, annual_revenue) values (65, 'Walt Disney', 'Tonga', 1387.721);
insert into companies (id, company_name, main_country, annual_revenue) values (66, 'Johnson Controls', 'Indonesia', 47511.2332);
insert into companies (id, company_name, main_country, annual_revenue) values (67, 'Morgan Stanley', 'Sao Tome & Principe', 91451.2101);
insert into companies (id, company_name, main_country, annual_revenue) values (68, 'Sysco', 'Liechtenstein', 77772.0463);
insert into companies (id, company_name, main_country, annual_revenue) values (69, 'FedEx', 'Estonia', 32426.62);
insert into companies (id, company_name, main_country, annual_revenue) values (70, 'Abbott Laboratories', 'Djibouti', 26249.4827);
insert into companies (id, company_name, main_country, annual_revenue) values (71, 'DuPont', 'Sao Tome & Principe', 57770.5872);
insert into companies (id, company_name, main_country, annual_revenue) values (72, 'Google', 'Tonga', 16214.7539);
insert into companies (id, company_name, main_country, annual_revenue) values (73, 'Hess', 'El Salvador', 72775.728);
insert into companies (id, company_name, main_country, annual_revenue) values (74, 'Supervalu', 'Slovakia', 60816.7097);
insert into companies (id, company_name, main_country, annual_revenue) values (75, 'United Continental Holdings', 'Bahrain', 57189.2702);
insert into companies (id, company_name, main_country, annual_revenue) values (76, 'Honeywell International', 'San Marino', 92645.4705);
insert into companies (id, company_name, main_country, annual_revenue) values (77, 'CHS', 'Denmark', 2411.045);
insert into companies (id, company_name, main_country, annual_revenue) values (78, 'Humana', 'Yemen', 52930.9808);
insert into companies (id, company_name, main_country, annual_revenue) values (79, 'Goldman Sachs Group', 'Azerbaijan', 1415.9247);
insert into companies (id, company_name, main_country, annual_revenue) values (80, 'Ingram Micro', 'Mauritania', 79876.8819);
insert into companies (id, company_name, main_country, annual_revenue) values (81, 'Oracle', 'Bolivia', 78778.5613);
insert into companies (id, company_name, main_country, annual_revenue) values (82, 'Delta Air Lines', 'Turkey', 38458.9928);
insert into companies (id, company_name, main_country, annual_revenue) values (83, 'Liberty Mutual Insurance Group', 'Monaco', 52841.8424);
insert into companies (id, company_name, main_country, annual_revenue) values (84, 'World Fuel Services', 'Laos', 73711.0681);
insert into companies (id, company_name, main_country, annual_revenue) values (85, 'New York Life Insurance', 'Bosnia Herzegovina', 36911.1084);
insert into companies (id, company_name, main_country, annual_revenue) values (86, 'Plains All American Pipeline', 'Malta', 84301.5901);
insert into companies (id, company_name, main_country, annual_revenue) values (87, 'TIAA-CREF', 'Vatican City', 9986.0067);
insert into companies (id, company_name, main_country, annual_revenue) values (88, 'Aetna', 'United States', 13585.2876);
insert into companies (id, company_name, main_country, annual_revenue) values (89, 'Sprint Nextel', 'Peru', 45478.9026);
insert into companies (id, company_name, main_country, annual_revenue) values (90, 'News Corp.', 'Trinidad & Tobago', 96820.9545);
insert into companies (id, company_name, main_country, annual_revenue) values (91, 'General Dynamics', 'Uganda', 57260.3571);
insert into companies (id, company_name, main_country, annual_revenue) values (92, 'Allstate', 'Vietnam', 77136.2766);
insert into companies (id, company_name, main_country, annual_revenue) values (93, 'HCA Holdings', 'Costa Rica', 52337.96);
insert into companies (id, company_name, main_country, annual_revenue) values (94, 'American Express', 'Nigeria', 28388.3292);
insert into companies (id, company_name, main_country, annual_revenue) values (95, 'Tyson Foods', 'Rwanda', 10968.3797);
insert into companies (id, company_name, main_country, annual_revenue) values (96, 'Deere', 'Russian Federation', 25086.2751);
insert into companies (id, company_name, main_country, annual_revenue) values (97, 'Murphy Oil', 'Montenegro', 75829.8168);
insert into companies (id, company_name, main_country, annual_revenue) values (98, 'Philip Morris International', 'Lebanon', 61478.2815);
insert into companies (id, company_name, main_country, annual_revenue) values (99, 'Nationwide', 'Antigua & Deps', 6553.5378);
insert into companies (id, company_name, main_country, annual_revenue) values (100, 'Tesoro', 'Ethiopia', 74116.4362);
insert into companies (id, company_name, main_country, annual_revenue) values (101, '3M', 'Philippines', 13464.8543);
insert into companies (id, company_name, main_country, annual_revenue) values (102, 'Time Warner', 'Australia', 43635.204);
insert into companies (id, company_name, main_country, annual_revenue) values (103, 'Northrop Grumman', 'Uruguay', 84489.2821);
insert into companies (id, company_name, main_country, annual_revenue) values (104, 'DirecTV', 'Armenia', 1159.997);
insert into companies (id, company_name, main_country, annual_revenue) values (105, 'Publix Super Markets', 'Bahamas', 71359.291);
insert into companies (id, company_name, main_country, annual_revenue) values (106, 'McDonalds', 'Cameroon', 65453.3018);
insert into companies (id, company_name, main_country, annual_revenue) values (107, 'Avnet', 'Mali', 22231.0367);
insert into companies (id, company_name, main_country, annual_revenue) values (108, 'Tech Data', 'Fiji', 94728.2044);
insert into companies (id, company_name, main_country, annual_revenue) values (109, 'Macys', 'Lebanon', 60125.0333);
insert into companies (id, company_name, main_country, annual_revenue) values (110, 'International Paper', 'Slovakia', 12409.8923);
insert into companies (id, company_name, main_country, annual_revenue) values (111, 'Travelers Cos.', 'Austria', 33030.8672);
insert into companies (id, company_name, main_country, annual_revenue) values (112, 'Rite Aid', 'Somalia', 72071.0109);
insert into companies (id, company_name, main_country, annual_revenue) values (113, 'Staples', 'Honduras', 95909.8995);
insert into companies (id, company_name, main_country, annual_revenue) values (114, 'Alcoa', 'Libya', 50636.0011);
insert into companies (id, company_name, main_country, annual_revenue) values (115, 'Northwestern Mutual', 'Colombia', 2553.7629);
insert into companies (id, company_name, main_country, annual_revenue) values (116, 'Raytheon', 'Belarus', 56440.5527);
insert into companies (id, company_name, main_country, annual_revenue) values (117, 'Halliburton', 'Chad', 5405.012);
insert into companies (id, company_name, main_country, annual_revenue) values (118, 'Eli Lilly', 'Kiribati', 87781.8309);
insert into companies (id, company_name, main_country, annual_revenue) values (119, 'Emerson Electric', 'Croatia', 43576.2406);
insert into companies (id, company_name, main_country, annual_revenue) values (120, 'Massachusetts Mutual Life Insurance', 'Andorra', 27052.9749);
insert into companies (id, company_name, main_country, annual_revenue) values (121, 'Occidental Petroleum', 'Bhutan', 30228.9221);
insert into companies (id, company_name, main_country, annual_revenue) values (122, 'AMR', 'Korea North', 18180.764);
insert into companies (id, company_name, main_country, annual_revenue) values (123, 'Fluor', 'Greece', 79413.5797);
insert into companies (id, company_name, main_country, annual_revenue) values (124, 'TJX', 'Bulgaria', 62283.3934);
insert into companies (id, company_name, main_country, annual_revenue) values (125, 'Goodyear Tire & Rubber', 'Mauritania', 21388.1287);
insert into companies (id, company_name, main_country, annual_revenue) values (126, 'Xerox', 'Vatican City', 8656.4883);
insert into companies (id, company_name, main_country, annual_revenue) values (127, 'Aflac', 'San Marino', 58242.5324);
insert into companies (id, company_name, main_country, annual_revenue) values (128, 'Manpower', 'Haiti', 85583.7889);
insert into companies (id, company_name, main_country, annual_revenue) values (129, 'Cigna', 'Sweden', 69500.8943);
insert into companies (id, company_name, main_country, annual_revenue) values (130, 'Hartford Financial Services Group', 'Palau', 67374.7633);
insert into companies (id, company_name, main_country, annual_revenue) values (131, 'U.S. Bancorp', 'Botswana', 44241.5789);
insert into companies (id, company_name, main_country, annual_revenue) values (132, 'Arrow Electronics', 'Zimbabwe', 1754.5278);
insert into companies (id, company_name, main_country, annual_revenue) values (133, 'Bristol-Myers Squibb', 'Turkmenistan', 62122.934);
insert into companies (id, company_name, main_country, annual_revenue) values (134, 'Freeport-McMoRan Copper & Gold', 'Pakistan', 42194.3162);
insert into companies (id, company_name, main_country, annual_revenue) values (135, 'Nike', 'Fiji', 67044.2059);
insert into companies (id, company_name, main_country, annual_revenue) values (136, 'Kimberly-Clark', 'Lithuania', 80457.413);
insert into companies (id, company_name, main_country, annual_revenue) values (137, 'Nucor', 'Guinea', 32174.9851);
insert into companies (id, company_name, main_country, annual_revenue) values (138, 'EMC', 'Sudan', 62024.9278);
insert into companies (id, company_name, main_country, annual_revenue) values (139, 'United States Steel', 'Micronesia', 34396.7579);
insert into companies (id, company_name, main_country, annual_revenue) values (140, 'Baker Hughes', 'Sweden', 57821.7878);
insert into companies (id, company_name, main_country, annual_revenue) values (141, 'Time Warner Cable', 'Moldova', 56064.8795);
insert into companies (id, company_name, main_country, annual_revenue) values (142, 'Union Pacific', 'Marshall Islands', 74860.7669);
insert into companies (id, company_name, main_country, annual_revenue) values (143, 'United Services Automobile Assn.', 'Saudi Arabia', 6796.62);
insert into companies (id, company_name, main_country, annual_revenue) values (144, 'Exelon', 'Mali', 78133.132);
insert into companies (id, company_name, main_country, annual_revenue) values (145, 'Kohls', 'Afghanistan', 98855.6699);
insert into companies (id, company_name, main_country, annual_revenue) values (146, 'Whirlpool', 'Tanzania', 62498.0822);
insert into companies (id, company_name, main_country, annual_revenue) values (147, 'Capital One Financial', 'Barbados', 77090.953);
insert into companies (id, company_name, main_country, annual_revenue) values (148, 'Illinois Tool Works', 'Eritrea', 77854.346);
insert into companies (id, company_name, main_country, annual_revenue) values (149, 'Cummins', 'Panama', 97614.7313);
insert into companies (id, company_name, main_country, annual_revenue) values (150, 'AES', 'St Kitts & Nevis', 77543.2035);
insert into companies (id, company_name, main_country, annual_revenue) values (151, 'Southern', 'Nigeria', 24384.8154);
insert into companies (id, company_name, main_country, annual_revenue) values (152, 'J.C. Penney', 'Czech Republic', 63834.8679);
insert into companies (id, company_name, main_country, annual_revenue) values (153, 'Apache', 'Chad', 32389.7359);
insert into companies (id, company_name, main_country, annual_revenue) values (154, 'Colgate-Palmolive', 'Senegal', 74268.2067);
insert into companies (id, company_name, main_country, annual_revenue) values (155, 'Altria Group', 'Netherlands', 71185.6839);
insert into companies (id, company_name, main_country, annual_revenue) values (156, 'Jabil Circuit', 'Seychelles', 78941.8052);
insert into companies (id, company_name, main_country, annual_revenue) values (157, 'Danaher', 'Senegal', 49619.3458);
insert into companies (id, company_name, main_country, annual_revenue) values (158, 'Paccar', 'Cambodia', 92540.1061);
insert into companies (id, company_name, main_country, annual_revenue) values (159, 'FirstEnergy', 'Mali', 78821.5564);
insert into companies (id, company_name, main_country, annual_revenue) values (160, 'TRW Automotive Holdings', 'Botswana', 34762.4301);
insert into companies (id, company_name, main_country, annual_revenue) values (161, 'Computer Sciences', 'Lesotho', 96385.9053);
insert into companies (id, company_name, main_country, annual_revenue) values (162, 'Eaton', 'United States', 27789.5719);
insert into companies (id, company_name, main_country, annual_revenue) values (163, 'Medtronic', 'Indonesia', 4135.7698);
insert into companies (id, company_name, main_country, annual_revenue) values (164, 'PNC Financial Services Group', 'Saudi Arabia', 20610.0813);
insert into companies (id, company_name, main_country, annual_revenue) values (165, 'Bank of New York Mellon Corp.', 'Ecuador', 56030.1523);
insert into companies (id, company_name, main_country, annual_revenue) values (166, 'Southwest Airlines', 'United Kingdom', 57541.773);
insert into companies (id, company_name, main_country, annual_revenue) values (167, 'Amgen', 'Estonia', 48471.7185);
insert into companies (id, company_name, main_country, annual_revenue) values (168, 'Progressive', 'Ivory Coast', 53794.9121);
insert into companies (id, company_name, main_country, annual_revenue) values (169, 'HollyFrontier', 'Brazil', 80564.6018);
insert into companies (id, company_name, main_country, annual_revenue) values (170, 'CenturyLink', 'Bolivia', 74930.9088);
insert into companies (id, company_name, main_country, annual_revenue) values (171, 'NextEra Energy', 'Guyana', 9560.5756);
insert into companies (id, company_name, main_country, annual_revenue) values (172, 'Marathon Oil', 'Algeria', 45479.0315);
insert into companies (id, company_name, main_country, annual_revenue) values (173, 'L-3 Communications', 'Belgium', 2302.4489);
insert into companies (id, company_name, main_country, annual_revenue) values (174, 'Oneok', 'Australia', 96096.3748);
insert into companies (id, company_name, main_country, annual_revenue) values (175, 'American Electric Power', 'Tunisia', 32181.4377);
insert into companies (id, company_name, main_country, annual_revenue) values (176, 'Viacom', 'Germany', 62270.2562);
insert into companies (id, company_name, main_country, annual_revenue) values (177, 'Qualcomm', 'Solomon Islands', 37583.57);
insert into companies (id, company_name, main_country, annual_revenue) values (178, 'PG&E Corp.', 'Brunei', 31645.7499);
insert into companies (id, company_name, main_country, annual_revenue) values (179, 'PPG Industries', 'Greece', 27354.8363);
insert into companies (id, company_name, main_country, annual_revenue) values (180, 'General Mills', 'Monaco', 25282.7882);
insert into companies (id, company_name, main_country, annual_revenue) values (181, 'Global Partners', 'Vatican City', 20809.7908);
insert into companies (id, company_name, main_country, annual_revenue) values (182, 'Dollar General', 'Suriname', 52526.6261);
insert into companies (id, company_name, main_country, annual_revenue) values (183, 'National Oilwell Varco', 'Ireland {Republic}', 2398.4472);
insert into companies (id, company_name, main_country, annual_revenue) values (184, 'Gap', 'Netherlands', 55196.287);
insert into companies (id, company_name, main_country, annual_revenue) values (185, 'Duke Energy', 'Italy', 45581.4601);
insert into companies (id, company_name, main_country, annual_revenue) values (186, 'Dominion Resources', 'Croatia', 44468.9068);
insert into companies (id, company_name, main_country, annual_revenue) values (187, 'CBS', 'Kiribati', 79547.7427);
insert into companies (id, company_name, main_country, annual_revenue) values (188, 'Lear', 'Singapore', 63761.5078);
insert into companies (id, company_name, main_country, annual_revenue) values (189, 'Loews', 'Bosnia Herzegovina', 37875.4568);
insert into companies (id, company_name, main_country, annual_revenue) values (190, 'DISH Network', 'Poland', 90449.0402);
insert into companies (id, company_name, main_country, annual_revenue) values (191, 'Anadarko Petroleum', 'Korea North', 34252.3983);
insert into companies (id, company_name, main_country, annual_revenue) values (192, 'Navistar International', 'Guatemala', 93477.7823);
insert into companies (id, company_name, main_country, annual_revenue) values (193, 'Toys "R" Us', 'Australia', 12731.0767);
insert into companies (id, company_name, main_country, annual_revenue) values (194, 'Baxter International', 'Tunisia', 67183.546);
insert into companies (id, company_name, main_country, annual_revenue) values (195, 'Omnicom Group', 'St Lucia', 36722.6256);
insert into companies (id, company_name, main_country, annual_revenue) values (196, 'AutoNation', 'India', 94727.2459);
insert into companies (id, company_name, main_country, annual_revenue) values (197, 'Community Health Systems', 'Serbia', 70775.2504);
insert into companies (id, company_name, main_country, annual_revenue) values (198, 'Constellation Energy', 'Mexico', 65135.166);
insert into companies (id, company_name, main_country, annual_revenue) values (199, 'Texas Instruments', 'Sierra Leone', 82045.3714);
insert into companies (id, company_name, main_country, annual_revenue) values (200, 'Ally Financial', 'Burkina', 86809.0217);
insert into companies (id, company_name, main_country, annual_revenue) values (201, 'Chubb', 'Ireland {Republic}', 65430.0131);
insert into companies (id, company_name, main_country, annual_revenue) values (202, 'Waste Management', 'Saint Vincent & the Grenadines', 764.0448);
insert into companies (id, company_name, main_country, annual_revenue) values (203, 'Aramark', 'Egypt', 56208.4997);
insert into companies (id, company_name, main_country, annual_revenue) values (204, 'Kellogg', 'Dominica', 95796.3888);
insert into companies (id, company_name, main_country, annual_revenue) values (205, 'Motorola Mobility Holdings', 'Guyana', 84285.9801);
insert into companies (id, company_name, main_country, annual_revenue) values (206, 'Dean Foods', 'Liberia', 54356.1646);
insert into companies (id, company_name, main_country, annual_revenue) values (207, 'US Airways Group', 'United States', 84110.5967);
insert into companies (id, company_name, main_country, annual_revenue) values (208, 'Consolidated Edison', 'Barbados', 19886.5376);
insert into companies (id, company_name, main_country, annual_revenue) values (209, 'Land OLakes', 'Spain', 52898.9724);
insert into companies (id, company_name, main_country, annual_revenue) values (210, 'Edison International', 'Solomon Islands', 40612.4558);
insert into companies (id, company_name, main_country, annual_revenue) values (211, 'PPL', 'El Salvador', 80180.2135);
insert into companies (id, company_name, main_country, annual_revenue) values (212, 'Yum Brands', 'Kuwait', 98601.1203);
insert into companies (id, company_name, main_country, annual_revenue) values (213, 'Genuine Parts', 'Morocco', 1901.1848);
insert into companies (id, company_name, main_country, annual_revenue) values (214, 'ConAgra Foods', 'Liberia', 93388.8284);
insert into companies (id, company_name, main_country, annual_revenue) values (215, 'Parker Hannifin', 'Honduras', 38220.3152);
insert into companies (id, company_name, main_country, annual_revenue) values (216, 'Marriott International', 'Korea South', 73976.1281);
insert into companies (id, company_name, main_country, annual_revenue) values (217, 'Smithfield Foods', 'Greece', 28283.9008);
insert into companies (id, company_name, main_country, annual_revenue) values (218, 'Coventry Health Care', 'Fiji', 84107.9533);
insert into companies (id, company_name, main_country, annual_revenue) values (219, 'Sara Lee', 'Jordan', 15734.6927);
insert into companies (id, company_name, main_country, annual_revenue) values (220, 'Health Net', 'Australia', 14646.4751);
insert into companies (id, company_name, main_country, annual_revenue) values (221, 'Penske Automotive Group', 'Nepal', 46525.1552);
insert into companies (id, company_name, main_country, annual_revenue) values (222, 'Icahn Enterprises', 'Dominican Republic', 58083.6955);
insert into companies (id, company_name, main_country, annual_revenue) values (223, 'Monsanto', 'Mongolia', 43931.8571);
insert into companies (id, company_name, main_country, annual_revenue) values (224, 'Thermo Fisher Scientific', 'Latvia', 2591.5527);
insert into companies (id, company_name, main_country, annual_revenue) values (225, 'CSX', 'United States', 35773.7243);
insert into companies (id, company_name, main_country, annual_revenue) values (226, 'Starbucks', 'Suriname', 77895.5844);
insert into companies (id, company_name, main_country, annual_revenue) values (227, 'eBay', 'Estonia', 57265.4154);
insert into companies (id, company_name, main_country, annual_revenue) values (228, 'Chesapeake Energy', 'Uruguay', 49636.722);
insert into companies (id, company_name, main_country, annual_revenue) values (229, 'Liberty Interactive', 'Uganda', 82168.1542);
insert into companies (id, company_name, main_country, annual_revenue) values (230, 'Marsh & McLennan', 'Belize', 27036.4823);
insert into companies (id, company_name, main_country, annual_revenue) values (231, 'Devon Energy', 'Luxembourg', 60029.1707);
insert into companies (id, company_name, main_country, annual_revenue) values (232, 'Office Depot', 'Bahrain', 71279.6809);
insert into companies (id, company_name, main_country, annual_revenue) values (233, 'Avon Products', 'Gambia', 76371.4519);
insert into companies (id, company_name, main_country, annual_revenue) values (234, 'Aon', 'Luxembourg', 88524.2202);
insert into companies (id, company_name, main_country, annual_revenue) values (235, 'Textron', 'Taiwan', 83139.7476);
insert into companies (id, company_name, main_country, annual_revenue) values (236, 'Huntsman', 'Lesotho', 99990.2313);
insert into companies (id, company_name, main_country, annual_revenue) values (237, 'Praxair', 'Sudan', 38106.5473);
insert into companies (id, company_name, main_country, annual_revenue) values (238, 'Entergy', 'Dominica', 90444.299);
insert into companies (id, company_name, main_country, annual_revenue) values (239, 'Public Service Enterprise Group', 'Fiji', 31626.1319);
insert into companies (id, company_name, main_country, annual_revenue) values (240, 'Norfolk Southern', 'Botswana', 5614.8093);
insert into companies (id, company_name, main_country, annual_revenue) values (241, 'Nordstrom', 'Czech Republic', 70736.2132);
insert into companies (id, company_name, main_country, annual_revenue) values (242, 'First Data', 'Zambia', 63316.8759);
insert into companies (id, company_name, main_country, annual_revenue) values (243, 'H.J. Heinz', 'Nicaragua', 94741.7731);
insert into companies (id, company_name, main_country, annual_revenue) values (244, 'SAIC', 'Burundi', 79428.3585);
insert into companies (id, company_name, main_country, annual_revenue) values (245, 'Xcel Energy', 'Luxembourg', 93832.3197);
insert into companies (id, company_name, main_country, annual_revenue) values (246, 'Lincoln National', 'Kyrgyzstan', 30273.5405);
insert into companies (id, company_name, main_country, annual_revenue) values (247, 'Ameriprise Financial', 'South Sudan', 25440.5899);
insert into companies (id, company_name, main_country, annual_revenue) values (248, 'R.R. Donnelley & Sons', 'Pakistan', 62995.0338);
insert into companies (id, company_name, main_country, annual_revenue) values (249, 'Guardian Life Ins. Co. of America', 'Georgia', 75147.5845);
insert into companies (id, company_name, main_country, annual_revenue) values (250, 'Applied Materials', 'Monaco', 80749.0096);
insert into companies (id, company_name, main_country, annual_revenue) values (251, 'Stanley Black & Decker', 'Finland', 56213.2385);
insert into companies (id, company_name, main_country, annual_revenue) values (252, 'Synnex', 'Romania', 48788.2069);
insert into companies (id, company_name, main_country, annual_revenue) values (253, 'Jacobs Engineering Group', 'Portugal', 70796.8823);
insert into companies (id, company_name, main_country, annual_revenue) values (254, 'Peter Kiewit Sons', 'Lebanon', 84136.8312);
insert into companies (id, company_name, main_country, annual_revenue) values (255, 'Limited Brands', 'Georgia', 80240.718);
insert into companies (id, company_name, main_country, annual_revenue) values (256, 'Newmont Mining', 'Sao Tome & Principe', 94955.4409);
insert into companies (id, company_name, main_country, annual_revenue) values (257, 'Genworth Financial', 'Australia', 49544.895);
insert into companies (id, company_name, main_country, annual_revenue) values (258, 'C.H. Robinson Worldwide', 'Philippines', 98567.6284);
insert into companies (id, company_name, main_country, annual_revenue) values (259, 'Unum Group', 'Equatorial Guinea', 16733.0709);
insert into companies (id, company_name, main_country, annual_revenue) values (260, 'Liberty Global', 'Monaco', 5665.7281);
insert into companies (id, company_name, main_country, annual_revenue) values (261, 'State Street Corp.', 'Macedonia', 90114.1501);
insert into companies (id, company_name, main_country, annual_revenue) values (262, 'EOG Resources', 'Venezuela', 69023.5403);
insert into companies (id, company_name, main_country, annual_revenue) values (263, 'Whole Foods Market', 'United Arab Emirates', 73926.1275);
insert into companies (id, company_name, main_country, annual_revenue) values (264, 'Air Products & Chemicals', 'Pakistan', 69067.1907);
insert into companies (id, company_name, main_country, annual_revenue) values (265, 'Sempra Energy', 'South Africa', 60650.0113);
insert into companies (id, company_name, main_country, annual_revenue) values (266, 'BB&T Corp.', 'Belgium', 24079.498);
insert into companies (id, company_name, main_country, annual_revenue) values (267, 'Mosaic', 'Liberia', 21337.9888);
insert into companies (id, company_name, main_country, annual_revenue) values (268, 'Automatic Data Processing', 'Estonia', 10942.758);
insert into companies (id, company_name, main_country, annual_revenue) values (269, 'CDW', 'Honduras', 81622.3983);
insert into companies (id, company_name, main_country, annual_revenue) values (270, 'SunTrust Banks', 'United States', 85039.2079);
insert into companies (id, company_name, main_country, annual_revenue) values (271, 'Tenet Healthcare', 'Croatia', 11301.1338);
insert into companies (id, company_name, main_country, annual_revenue) values (272, 'GameStop', 'Romania', 17158.1021);
insert into companies (id, company_name, main_country, annual_revenue) values (273, 'Motorola Solutions', 'Georgia', 91434.1093);
insert into companies (id, company_name, main_country, annual_revenue) values (274, 'URS', 'Gabon', 99335.08);
insert into companies (id, company_name, main_country, annual_revenue) values (275, 'Western Digital', 'Guinea-Bissau', 97669.5088);
insert into companies (id, company_name, main_country, annual_revenue) values (276, 'VF', 'Andorra', 47026.8307);
insert into companies (id, company_name, main_country, annual_revenue) values (277, 'Las Vegas Sands', 'United States', 85712.3914);
insert into companies (id, company_name, main_country, annual_revenue) values (278, 'CarMax', 'Kazakhstan', 57191.3927);
insert into companies (id, company_name, main_country, annual_revenue) values (279, 'KBR', 'Malaysia', 76656.3295);
insert into companies (id, company_name, main_country, annual_revenue) values (280, 'Visa', 'Samoa', 47988.5735);
insert into companies (id, company_name, main_country, annual_revenue) values (281, 'Enbridge Energy Partners', 'Belarus', 18369.3683);
insert into companies (id, company_name, main_country, annual_revenue) values (282, 'BlackRock', 'Lithuania', 37343.866);
insert into companies (id, company_name, main_country, annual_revenue) values (283, 'NRG Energy', 'Haiti', 17457.6136);
insert into companies (id, company_name, main_country, annual_revenue) values (284, 'Western Refining', 'San Marino', 26286.9777);
insert into companies (id, company_name, main_country, annual_revenue) values (285, 'Progress Energy', 'Armenia', 1396.728);
insert into companies (id, company_name, main_country, annual_revenue) values (286, 'DTE Energy', 'Myanmar, {Burma}', 9525.0177);
insert into companies (id, company_name, main_country, annual_revenue) values (287, 'Caesars Entertainment', 'Congo {Democratic Rep}', 54208.1147);
insert into companies (id, company_name, main_country, annual_revenue) values (288, 'Reinsurance Group of America', 'Montenegro', 26688.5837);
insert into companies (id, company_name, main_country, annual_revenue) values (289, 'Estée Lauder', 'Korea South', 50428.2008);
insert into companies (id, company_name, main_country, annual_revenue) values (290, 'Micron Technology', 'Brunei', 35146.0224);
insert into companies (id, company_name, main_country, annual_revenue) values (291, 'AGCO', 'Estonia', 25114.3513);
insert into companies (id, company_name, main_country, annual_revenue) values (292, 'Sherwin-Williams', 'Guyana', 15111.9882);
insert into companies (id, company_name, main_country, annual_revenue) values (293, 'Bed Bath & Beyond', 'Congo {Democratic Rep}', 48173.0102);
insert into companies (id, company_name, main_country, annual_revenue) values (294, 'Principal Financial', 'Australia', 65394.7007);
insert into companies (id, company_name, main_country, annual_revenue) values (295, 'Crown Holdings', 'Denmark', 76844.4255);
insert into companies (id, company_name, main_country, annual_revenue) values (296, 'Ball', 'Congo {Democratic Rep}', 47197.3695);
insert into companies (id, company_name, main_country, annual_revenue) values (297, 'Owens & Minor', 'Sweden', 28282.3018);
insert into companies (id, company_name, main_country, annual_revenue) values (298, 'Ross Stores', 'Bhutan', 47184.3244);
insert into companies (id, company_name, main_country, annual_revenue) values (299, 'Discover Financial Services', 'Italy', 6276.2983);
insert into companies (id, company_name, main_country, annual_revenue) values (300, 'Family Dollar Stores', 'Swaziland', 13355.532);
insert into companies (id, company_name, main_country, annual_revenue) values (301, 'Reynolds American', 'Moldova', 80126.179);
insert into companies (id, company_name, main_country, annual_revenue) values (302, 'Henry Schein', 'Nauru', 44336.1146);
insert into companies (id, company_name, main_country, annual_revenue) values (303, 'Dover', 'Laos', 32167.2071);
insert into companies (id, company_name, main_country, annual_revenue) values (304, 'CenterPoint Energy', 'Bosnia Herzegovina', 92239.7878);
insert into companies (id, company_name, main_country, annual_revenue) values (305, 'Gilead Sciences', 'Nepal', 13143.4687);
insert into companies (id, company_name, main_country, annual_revenue) values (306, 'Ashland', 'Mali', 50705.0165);
insert into companies (id, company_name, main_country, annual_revenue) values (307, 'Stryker', 'St Kitts & Nevis', 541.9195);
insert into companies (id, company_name, main_country, annual_revenue) values (308, 'Hertz Global Holdings', 'Angola', 83297.6517);
insert into companies (id, company_name, main_country, annual_revenue) values (309, 'Assurant', 'Iraq', 39469.6892);
insert into companies (id, company_name, main_country, annual_revenue) values (310, 'Kinder Morgan', 'Belarus', 32756.8411);
insert into companies (id, company_name, main_country, annual_revenue) values (311, 'Energy Transfer Equity', 'Nicaragua', 71827.2171);
insert into companies (id, company_name, main_country, annual_revenue) values (312, 'Autoliv', 'Peru', 26074.075);
insert into companies (id, company_name, main_country, annual_revenue) values (313, 'Republic Services', 'Botswana', 93389.5844);
insert into companies (id, company_name, main_country, annual_revenue) values (314, 'Reliance Steel & Aluminum', 'Kosovo', 16412.0133);
insert into companies (id, company_name, main_country, annual_revenue) values (315, 'Peabody Energy', 'Brazil', 65758.3428);
insert into companies (id, company_name, main_country, annual_revenue) values (316, 'Great Atlantic & Pacific Tea', 'Thailand', 5900.3002);
insert into companies (id, company_name, main_country, annual_revenue) values (317, 'W.W. Grainger', 'Micronesia', 65032.0232);
insert into companies (id, company_name, main_country, annual_revenue) values (318, 'Goodrich', 'Iceland', 44147.7342);
insert into companies (id, company_name, main_country, annual_revenue) values (319, 'AutoZone', 'Bahamas', 88060.8893);
insert into companies (id, company_name, main_country, annual_revenue) values (320, 'Visteon', 'Comoros', 45586.9105);
insert into companies (id, company_name, main_country, annual_revenue) values (321, 'AECOM Technology', 'Austria', 40867.6053);
insert into companies (id, company_name, main_country, annual_revenue) values (322, 'Steel Dynamics', 'Monaco', 70620.2549);
insert into companies (id, company_name, main_country, annual_revenue) values (323, 'Coca-Cola Enterprises', 'Jamaica', 68784.1247);
insert into companies (id, company_name, main_country, annual_revenue) values (324, 'Williams', 'Nauru', 94465.3928);
insert into companies (id, company_name, main_country, annual_revenue) values (325, 'Commercial Metals', 'Malaysia', 11574.32);
insert into companies (id, company_name, main_country, annual_revenue) values (326, 'Hormel Foods', 'Kazakhstan', 7867.6454);
insert into companies (id, company_name, main_country, annual_revenue) values (327, 'Corning', 'Lebanon', 42208.4708);
insert into companies (id, company_name, main_country, annual_revenue) values (328, 'TravelCenters of America', 'Mali', 35382.3142);
insert into companies (id, company_name, main_country, annual_revenue) values (329, 'Sonic Automotive', 'Ivory Coast', 70137.9897);
insert into companies (id, company_name, main_country, annual_revenue) values (330, 'MGM Resorts International', 'Luxembourg', 24232.2364);
insert into companies (id, company_name, main_country, annual_revenue) values (331, 'Thrivent Financial for Lutherans', 'United States', 65211.2292);
insert into companies (id, company_name, main_country, annual_revenue) values (332, 'Becton Dickinson', 'Eritrea', 31590.5856);
insert into companies (id, company_name, main_country, annual_revenue) values (333, 'Campbell Soup', 'Colombia', 1444.6282);
insert into companies (id, company_name, main_country, annual_revenue) values (334, 'Boston Scientific', 'Angola', 33909.1519);
insert into companies (id, company_name, main_country, annual_revenue) values (335, 'Dana Holding', 'Oman', 8705.5616);
insert into companies (id, company_name, main_country, annual_revenue) values (336, 'Oshkosh', 'St Kitts & Nevis', 11240.4689);
insert into companies (id, company_name, main_country, annual_revenue) values (337, 'Masco', 'Solomon Islands', 80809.7854);
insert into companies (id, company_name, main_country, annual_revenue) values (338, 'Universal Health Services', 'Mexico', 84692.301);
insert into companies (id, company_name, main_country, annual_revenue) values (339, 'Ameren', 'Saudi Arabia', 44350.9337);
insert into companies (id, company_name, main_country, annual_revenue) values (340, 'Quest Diagnostics', 'San Marino', 29801.4822);
insert into companies (id, company_name, main_country, annual_revenue) values (341, 'Darden Restaurants', 'Korea South', 63980.9554);
insert into companies (id, company_name, main_country, annual_revenue) values (342, 'Regions Financial', 'Syria', 62997.8462);
insert into companies (id, company_name, main_country, annual_revenue) values (343, 'Broadcom', 'Angola', 81190.1822);
insert into companies (id, company_name, main_country, annual_revenue) values (344, 'Owens-Illinois', 'Brazil', 35863.5884);
insert into companies (id, company_name, main_country, annual_revenue) values (345, 'Eastman Chemical', 'Ireland {Republic}', 51293.3586);
insert into companies (id, company_name, main_country, annual_revenue) values (346, 'Pantry', 'Botswana', 80038.513);
insert into companies (id, company_name, main_country, annual_revenue) values (347, 'Cablevision Systems', 'Hungary', 42097.5383);
insert into companies (id, company_name, main_country, annual_revenue) values (348, 'Dole Food', 'Sri Lanka', 4712.8639);
insert into companies (id, company_name, main_country, annual_revenue) values (349, 'Tenneco', 'Singapore', 74998.8357);
insert into companies (id, company_name, main_country, annual_revenue) values (350, 'Charter Communications', 'Jordan', 64370.5633);
insert into companies (id, company_name, main_country, annual_revenue) values (351, 'Spectrum Group International', 'Bolivia', 34030.3717);
insert into companies (id, company_name, main_country, annual_revenue) values (352, 'Franklin Resources', 'Zimbabwe', 9865.8392);
insert into companies (id, company_name, main_country, annual_revenue) values (353, 'OfficeMax', 'Kazakhstan', 56926.0678);
insert into companies (id, company_name, main_country, annual_revenue) values (354, 'BorgWarner', 'Denmark', 19033.3719);
insert into companies (id, company_name, main_country, annual_revenue) values (355, 'Alpha Natural Resources', 'Netherlands', 79242.1999);
insert into companies (id, company_name, main_country, annual_revenue) values (356, 'Energy Future Holdings', 'Micronesia', 65166.479);
insert into companies (id, company_name, main_country, annual_revenue) values (357, 'Interpublic Group', 'San Marino', 89828.6134);
insert into companies (id, company_name, main_country, annual_revenue) values (358, 'DaVita', 'Swaziland', 58510.9026);
insert into companies (id, company_name, main_country, annual_revenue) values (359, 'Barnes & Noble', 'Bangladesh', 76646.1878);
insert into companies (id, company_name, main_country, annual_revenue) values (360, 'Targa Resources', 'Argentina', 33944.8693);
insert into companies (id, company_name, main_country, annual_revenue) values (361, 'Cameron International', 'Canada', 32634.8841);
insert into companies (id, company_name, main_country, annual_revenue) values (362, 'Winn-Dixie Stores', 'Sao Tome & Principe', 11525.0469);
insert into companies (id, company_name, main_country, annual_revenue) values (363, 'Calpine', 'Malawi', 74641.9607);
insert into companies (id, company_name, main_country, annual_revenue) values (364, 'Ecolab', 'Czech Republic', 10909.5333);
insert into companies (id, company_name, main_country, annual_revenue) values (365, 'Cliffs Natural Resources', 'Solomon Islands', 23156.5019);
insert into companies (id, company_name, main_country, annual_revenue) values (366, 'Avery Dennison', 'Saint Vincent & the Grenadines', 71138.3675);
insert into companies (id, company_name, main_country, annual_revenue) values (367, 'Celanese', 'Azerbaijan', 76888.8004);
insert into companies (id, company_name, main_country, annual_revenue) values (368, 'NII Holdings', 'Nigeria', 46981.5463);
insert into companies (id, company_name, main_country, annual_revenue) values (369, 'MasterCard', 'Liechtenstein', 94338.3495);
insert into companies (id, company_name, main_country, annual_revenue) values (370, 'Jarden', 'United Kingdom', 35474.0391);
insert into companies (id, company_name, main_country, annual_revenue) values (371, 'Fifth Third Bancorp', 'Bangladesh', 78348.9548);
insert into companies (id, company_name, main_country, annual_revenue) values (372, 'Dollar Tree', 'Lithuania', 64321.2355);
insert into companies (id, company_name, main_country, annual_revenue) values (373, 'Weyerhaeuser', 'Denmark', 76883.7414);
insert into companies (id, company_name, main_country, annual_revenue) values (374, 'Agilent Technologies', 'Australia', 74829.8943);
insert into companies (id, company_name, main_country, annual_revenue) values (375, 'Sanmina-SCI', 'Mauritius', 14342.4055);
insert into companies (id, company_name, main_country, annual_revenue) values (376, 'NuStar Energy', 'Maldives', 98393.8017);
insert into companies (id, company_name, main_country, annual_revenue) values (377, 'Advanced Micro Devices', 'Congo', 88260.7038);
insert into companies (id, company_name, main_country, annual_revenue) values (378, 'Terex', 'Thailand', 23614.5895);
insert into companies (id, company_name, main_country, annual_revenue) values (379, 'CMS Energy', 'Jordan', 41948.7205);
insert into companies (id, company_name, main_country, annual_revenue) values (380, 'AK Steel Holding', 'Tajikistan', 98203.9955);
insert into companies (id, company_name, main_country, annual_revenue) values (381, 'American Family Insurance Group', 'Czech Republic', 44784.4494);
insert into companies (id, company_name, main_country, annual_revenue) values (382, 'Dillards', 'Ivory Coast', 3593.2195);
insert into companies (id, company_name, main_country, annual_revenue) values (383, 'McGraw-Hill', 'Netherlands', 69181.1452);
insert into companies (id, company_name, main_country, annual_revenue) values (384, 'Amerigroup', 'Croatia', 63923.6588);
insert into companies (id, company_name, main_country, annual_revenue) values (385, 'Anixter International', 'India', 23159.8851);
insert into companies (id, company_name, main_country, annual_revenue) values (386, 'Precision Castparts', 'United Arab Emirates', 94483.7583);
insert into companies (id, company_name, main_country, annual_revenue) values (387, 'Mattel', 'Congo {Democratic Rep}', 51246.0727);
insert into companies (id, company_name, main_country, annual_revenue) values (388, 'Omnicare', 'Nepal', 9171.0899);
insert into companies (id, company_name, main_country, annual_revenue) values (389, 'Corn Products International', 'Iran', 37693.8384);
insert into companies (id, company_name, main_country, annual_revenue) values (390, 'Symantec', 'Benin', 59413.7188);
insert into companies (id, company_name, main_country, annual_revenue) values (391, 'Advance Auto Parts', 'Italy', 66804.6589);
insert into companies (id, company_name, main_country, annual_revenue) values (392, 'Core-Mark Holding', 'Haiti', 77797.1924);
insert into companies (id, company_name, main_country, annual_revenue) values (393, 'CC Media Holdings', 'St Lucia', 69664.2435);
insert into companies (id, company_name, main_country, annual_revenue) values (394, 'Expeditors International of Washington', 'Taiwan', 98449.1227);
insert into companies (id, company_name, main_country, annual_revenue) values (395, 'Mylan', 'Bhutan', 65651.0695);
insert into companies (id, company_name, main_country, annual_revenue) values (396, 'Wesco International', 'El Salvador', 53036.663);
insert into companies (id, company_name, main_country, annual_revenue) values (397, 'Cognizant Technology Solutions', 'Niger', 93355.075);
insert into companies (id, company_name, main_country, annual_revenue) values (398, 'Consol Energy', 'Tajikistan', 65307.513);
insert into companies (id, company_name, main_country, annual_revenue) values (399, 'PetSmart', 'Denmark', 85848.8364);
insert into companies (id, company_name, main_country, annual_revenue) values (400, 'WellCare Health Plans', 'Austria', 3933.6831);
insert into companies (id, company_name, main_country, annual_revenue) values (401, 'CF Industries Holdings', 'Uruguay', 81282.9695);
insert into companies (id, company_name, main_country, annual_revenue) values (402, 'UGI', 'Uzbekistan', 50676.4089);
insert into companies (id, company_name, main_country, annual_revenue) values (403, 'Hershey', 'Ireland {Republic}', 10574.6152);
insert into companies (id, company_name, main_country, annual_revenue) values (404, 'Group 1 Automotive', 'Indonesia', 56815.8234);
insert into companies (id, company_name, main_country, annual_revenue) values (405, 'MeadWestvaco', 'Bulgaria', 64641.8631);
insert into companies (id, company_name, main_country, annual_revenue) values (406, 'Ryder System', 'Guyana', 99643.2494);
insert into companies (id, company_name, main_country, annual_revenue) values (407, 'Eastman Kodak', 'Taiwan', 62437.0285);
insert into companies (id, company_name, main_country, annual_revenue) values (408, 'NiSource', 'Czech Republic', 56607.476);
insert into companies (id, company_name, main_country, annual_revenue) values (409, 'Rockwell Automation', 'Kiribati', 23694.4322);
insert into companies (id, company_name, main_country, annual_revenue) values (410, 'Mutual of Omaha Insurance', 'Malta', 35295.6372);
insert into companies (id, company_name, main_country, annual_revenue) values (411, 'Shaw Group', 'Belgium', 86730.5228);
insert into companies (id, company_name, main_country, annual_revenue) values (412, 'Harris', 'Bosnia Herzegovina', 4184.3452);
insert into companies (id, company_name, main_country, annual_revenue) values (413, 'Newell Rubbermaid', 'Micronesia', 76387.2783);
insert into companies (id, company_name, main_country, annual_revenue) values (414, 'Pepco Holdings', 'Philippines', 23722.6293);
insert into companies (id, company_name, main_country, annual_revenue) values (415, 'CBRE Group', 'Ghana', 50917.3947);
insert into companies (id, company_name, main_country, annual_revenue) values (416, 'Dr Pepper Snapple Group', 'Argentina', 17707.3864);
insert into companies (id, company_name, main_country, annual_revenue) values (417, 'Avis Budget Group', 'Gabon', 19564.6507);
insert into companies (id, company_name, main_country, annual_revenue) values (418, 'PVH', 'France', 32053.3059);
insert into companies (id, company_name, main_country, annual_revenue) values (419, 'Pacific Life', 'Malaysia', 93698.9398);
insert into companies (id, company_name, main_country, annual_revenue) values (420, 'General Cable', 'Czech Republic', 74708.3658);
insert into companies (id, company_name, main_country, annual_revenue) values (421, 'Exelis', 'Bosnia Herzegovina', 93345.5326);
insert into companies (id, company_name, main_country, annual_revenue) values (422, 'Health Management Associates', 'Bhutan', 95812.4966);
insert into companies (id, company_name, main_country, annual_revenue) values (423, 'OReilly Automotive', 'New Zealand', 63511.1319);
insert into companies (id, company_name, main_country, annual_revenue) values (424, 'Fidelity National Information Services', 'Czech Republic', 4253.8412);
insert into companies (id, company_name, main_country, annual_revenue) values (425, 'SLM', 'Suriname', 74179.2087);
insert into companies (id, company_name, main_country, annual_revenue) values (426, 'Seaboard', 'Peru', 68817.7717);
insert into companies (id, company_name, main_country, annual_revenue) values (427, 'Emcor Group', 'Vanuatu', 95153.0243);
insert into companies (id, company_name, main_country, annual_revenue) values (428, 'Auto-Owners Insurance', 'Tuvalu', 54911.4311);
insert into companies (id, company_name, main_country, annual_revenue) values (429, 'SanDisk', 'Burundi', 60959.8593);
insert into companies (id, company_name, main_country, annual_revenue) values (430, 'Ralph Lauren', 'Maldives', 52881.3443);
insert into companies (id, company_name, main_country, annual_revenue) values (431, 'Mohawk Industries', 'Iceland', 54283.9404);
insert into companies (id, company_name, main_country, annual_revenue) values (432, 'Sealed Air', 'Andorra', 29783.9406);
insert into companies (id, company_name, main_country, annual_revenue) values (433, 'Starwood Hotels & Resorts', 'Rwanda', 6971.4255);
insert into companies (id, company_name, main_country, annual_revenue) values (434, 'Foot Locker', 'Benin', 35369.786);
insert into companies (id, company_name, main_country, annual_revenue) values (435, 'Domtar', 'Albania', 99246.5905);
insert into companies (id, company_name, main_country, annual_revenue) values (436, 'St. Jude Medical', 'Burundi', 60299.2235);
insert into companies (id, company_name, main_country, annual_revenue) values (437, 'Spectra Energy', 'Israel', 85661.7324);
insert into companies (id, company_name, main_country, annual_revenue) values (438, 'Booz Allen Hamilton Holding', 'Azerbaijan', 94763.0395);
insert into companies (id, company_name, main_country, annual_revenue) values (439, 'CH2M Hill', 'United Kingdom', 13691.5734);
insert into companies (id, company_name, main_country, annual_revenue) values (440, 'Kelly Services', 'Luxembourg', 98116.1757);
insert into companies (id, company_name, main_country, annual_revenue) values (441, 'Avaya', 'Afghanistan', 31257.7494);
insert into companies (id, company_name, main_country, annual_revenue) values (442, 'Laboratory Corp. of America', 'Taiwan', 98177.4664);
insert into companies (id, company_name, main_country, annual_revenue) values (443, 'Kindred Healthcare', 'Greece', 79581.4309);
insert into companies (id, company_name, main_country, annual_revenue) values (444, 'Western Union', 'Sao Tome & Principe', 69530.0669);
insert into companies (id, company_name, main_country, annual_revenue) values (445, 'SPX', 'Albania', 43091.149);
insert into companies (id, company_name, main_country, annual_revenue) values (446, 'NCR', 'Belgium', 32153.4758);
insert into companies (id, company_name, main_country, annual_revenue) values (447, 'Allergan', 'Turkey', 31737.5954);
insert into companies (id, company_name, main_country, annual_revenue) values (448, 'Rock-Tenn', 'Slovakia', 86500.3088);
insert into companies (id, company_name, main_country, annual_revenue) values (449, 'Live Nation Entertainment', 'Costa Rica', 3358.0957);
insert into companies (id, company_name, main_country, annual_revenue) values (450, 'Graybar Electric', 'Portugal', 97630.8342);
insert into companies (id, company_name, main_country, annual_revenue) values (451, 'Momentive Specialty Chemicals', 'Haiti', 86464.0344);
insert into companies (id, company_name, main_country, annual_revenue) values (452, 'Centene', 'Brunei', 30478.4834);
insert into companies (id, company_name, main_country, annual_revenue) values (453, 'Owens Corning', 'Vietnam', 91441.1903);
insert into companies (id, company_name, main_country, annual_revenue) values (454, 'Catalyst Health Solutions', 'Colombia', 88950.5429);
insert into companies (id, company_name, main_country, annual_revenue) values (455, 'Clorox', 'Croatia', 23052.085);
insert into companies (id, company_name, main_country, annual_revenue) values (456, 'Bemis', 'Chad', 23400.7608);
insert into companies (id, company_name, main_country, annual_revenue) values (457, 'Harley-Davidson', 'Serbia', 43212.9409);
insert into companies (id, company_name, main_country, annual_revenue) values (458, 'Con-way', 'Afghanistan', 59422.474);
insert into companies (id, company_name, main_country, annual_revenue) values (459, 'Insight Enterprises', 'Ecuador', 8188.5141);
insert into companies (id, company_name, main_country, annual_revenue) values (460, 'Pitney Bowes', 'France', 17915.0929);
insert into companies (id, company_name, main_country, annual_revenue) values (461, 'Wynn Resorts', 'Bahamas', 47685.1685);
insert into companies (id, company_name, main_country, annual_revenue) values (462, 'BrightPoint', 'Belize', 27754.0274);
insert into companies (id, company_name, main_country, annual_revenue) values (463, 'Frontier Communications', 'Brazil', 46578.7067);
insert into companies (id, company_name, main_country, annual_revenue) values (464, 'Gannett', 'Georgia', 1703.3585);
insert into companies (id, company_name, main_country, annual_revenue) values (465, 'Dicks Sporting Goods', 'Guinea', 33006.5958);
insert into companies (id, company_name, main_country, annual_revenue) values (466, 'Big Lots', 'Nigeria', 33022.0176);
insert into companies (id, company_name, main_country, annual_revenue) values (467, 'Allegheny Technologies', 'Bahamas', 26514.1228);
insert into companies (id, company_name, main_country, annual_revenue) values (468, 'Telephone & Data Systems', 'El Salvador', 29249.9915);
insert into companies (id, company_name, main_country, annual_revenue) values (469, 'Timken', 'Thailand', 5264.6423);
insert into companies (id, company_name, main_country, annual_revenue) values (470, 'W.R. Berkley', 'Saint Vincent & the Grenadines', 57150.5135);
insert into companies (id, company_name, main_country, annual_revenue) values (471, 'Fidelity National Financial', 'St Lucia', 32580.0758);
insert into companies (id, company_name, main_country, annual_revenue) values (472, 'Caseys General Stores', 'Sweden', 45312.911);
insert into companies (id, company_name, main_country, annual_revenue) values (473, 'NetApp', 'China', 26686.9246);
insert into companies (id, company_name, main_country, annual_revenue) values (474, 'FMC Technologies', 'Nigeria', 62354.4374);
insert into companies (id, company_name, main_country, annual_revenue) values (475, 'Biogen Idec', 'Pakistan', 12863.0899);
insert into companies (id, company_name, main_country, annual_revenue) values (476, 'CVR Energy', 'Ireland {Republic}', 54437.0196);
insert into companies (id, company_name, main_country, annual_revenue) values (477, 'United Stationers', 'Netherlands', 99787.1912);
insert into companies (id, company_name, main_country, annual_revenue) values (478, 'Host Hotels & Resorts', 'Tunisia', 66805.4786);
insert into companies (id, company_name, main_country, annual_revenue) values (479, 'SunGard Data Systems', 'Panama', 21502.6622);
insert into companies (id, company_name, main_country, annual_revenue) values (480, 'Meritor', 'Singapore', 15429.8273);
insert into companies (id, company_name, main_country, annual_revenue) values (481, 'Western & Southern Financial Group', 'Gambia', 48774.5956);
insert into companies (id, company_name, main_country, annual_revenue) values (482, 'Yahoo', 'Sao Tome & Principe', 83306.1683);
insert into companies (id, company_name, main_country, annual_revenue) values (483, 'Vanguard Health Systems', 'Singapore', 22125.9063);
insert into companies (id, company_name, main_country, annual_revenue) values (484, 'Charles Schwab', 'Uruguay', 66734.5949);
insert into companies (id, company_name, main_country, annual_revenue) values (485, 'Susser Holdings', 'Botswana', 21859.9087);
insert into companies (id, company_name, main_country, annual_revenue) values (486, 'YRC Worldwide', 'Germany', 85232.178);
insert into companies (id, company_name, main_country, annual_revenue) values (487, 'El Paso', 'Libya', 63274.7241);
insert into companies (id, company_name, main_country, annual_revenue) values (488, 'CIT Group', 'Kazakhstan', 77430.3838);
insert into companies (id, company_name, main_country, annual_revenue) values (489, 'MetroPCS Communications', 'Qatar', 39129.8189);
insert into companies (id, company_name, main_country, annual_revenue) values (490, 'Alliant Techsystems', 'Turkey', 52130.5788);
insert into companies (id, company_name, main_country, annual_revenue) values (491, 'Celgene', 'Myanmar, {Burma}', 90136.1954);
insert into companies (id, company_name, main_country, annual_revenue) values (492, 'MRC Global', 'Vanuatu', 39032.9852);
insert into companies (id, company_name, main_country, annual_revenue) values (493, 'Aleris', 'Nicaragua', 93314.7538);
insert into companies (id, company_name, main_country, annual_revenue) values (494, 'J.M. Smucker', 'Singapore', 99539.5385);
insert into companies (id, company_name, main_country, annual_revenue) values (495, 'Rockwell Collins', 'Montenegro', 92148.4833);
insert into companies (id, company_name, main_country, annual_revenue) values (496, 'Erie Insurance Group', 'Venezuela', 39587.166);
insert into companies (id, company_name, main_country, annual_revenue) values (497, 'Nash-Finch', 'Guinea', 83066.2371);
insert into companies (id, company_name, main_country, annual_revenue) values (498, 'KeyCorp', 'Cyprus', 67883.9062);
insert into companies (id, company_name, main_country, annual_revenue) values (499, 'Molina Healthcare', 'New Zealand', 33007.8125);
