insert into cities (id, name) values (1,'Abbeville');
insert into cities (id, name) values (2,'Acme');
insert into cities (id, name) values (3,'Adamsville');
insert into cities (id, name) values (4,'Advance');
insert into cities (id, name) values (5,'Akhiok');
insert into cities (id, name) values (6,'Albertson');
insert into cities (id, name) values (7,'Aledo');
insert into cities (id, name) values (8,'Aliceville');
insert into cities (id, name) values (9,'Alliance');
insert into cities (id, name) values (10,'Alpharetta');
insert into cities (id, name) values (11,'Alton Bay');
insert into cities (id, name) values (12,'Amagansett');
insert into cities (id, name) values (13,'American Canyon');
insert into cities (id, name) values (14,'Amity');
insert into cities (id, name) values (15,'Anderson');
insert into cities (id, name) values (16,'Animas');
insert into cities (id, name) values (17,'Anson');
insert into cities (id, name) values (18,'Aplington');
insert into cities (id, name) values (19,'Arab');
insert into cities (id, name) values (20,'Arden');
insert into cities (id, name) values (21,'Arkdale');
insert into cities (id, name) values (22,'Aroostook Band of Micmac Trust Land');
insert into cities (id, name) values (23,'Ashdown');
insert into cities (id, name) values (24,'Ashville');
insert into cities (id, name) values (25,'Atco');
insert into cities (id, name) values (26,'Atlantic Highlands');
insert into cities (id, name) values (27,'Aubrey');
insert into cities (id, name) values (28,'Avalon');
insert into cities (id, name) values (29,'Axton');
insert into cities (id, name) values (30,'Bahama');
insert into cities (id, name) values (31,'Baldwin City');
insert into cities (id, name) values (32,'Ballston Spa');
insert into cities (id, name) values (33,'Banner Elk');
insert into cities (id, name) values (34,'Bargersville');
insert into cities (id, name) values (35,'Barrow');
insert into cities (id, name) values (36,'Basking Ridge');
insert into cities (id, name) values (37,'Bay City');
insert into cities (id, name) values (38,'Bayview');
insert into cities (id, name) values (39,'Beardstown');
insert into cities (id, name) values (40,'Beaver Springs');
insert into cities (id, name) values (41,'Beeville');
insert into cities (id, name) values (42,'Belknap');
insert into cities (id, name) values (43,'Belle Vernon');
insert into cities (id, name) values (44,'Bellport');
insert into cities (id, name) values (45,'Belvidere');
insert into cities (id, name) values (46,'Bensenville');
insert into cities (id, name) values (47,'Bergen');
insert into cities (id, name) values (48,'Berrien Springs');
insert into cities (id, name) values (49,'Bethania');
insert into cities (id, name) values (50,'Beverly');
insert into cities (id, name) values (51,'Big Sandy');
insert into cities (id, name) values (52,'Birdsboro');
insert into cities (id, name) values (53,'Black Hawk');
insert into cities (id, name) values (54,'Blakeslee');
insert into cities (id, name) values (55,'Bloomsbury');
insert into cities (id, name) values (56,'Blue Earth');
insert into cities (id, name) values (57,'Blythe');
insert into cities (id, name) values (58,'Bogota');
insert into cities (id, name) values (59,'Bolton');
insert into cities (id, name) values (60,'Bonner Springs');
insert into cities (id, name) values (61,'Borger');
insert into cities (id, name) values (62,'Boulder City');
insert into cities (id, name) values (63,'Bowling Green');
insert into cities (id, name) values (64,'Bradenton');
insert into cities (id, name) values (65,'Brandenburg');
insert into cities (id, name) values (66,'Breckenridge');
insert into cities (id, name) values (67,'Brewton');
insert into cities (id, name) values (68,'Bridgman');
insert into cities (id, name) values (69,'Brisbane');
insert into cities (id, name) values (70,'Brockton');
insert into cities (id, name) values (71,'Brook Park');
insert into cities (id, name) values (72,'Browning');
insert into cities (id, name) values (73,'Brunswick');
insert into cities (id, name) values (74,'Buchanan');
insert into cities (id, name) values (75,'Budd Lake');
insert into cities (id, name) values (76,'Buna');
insert into cities (id, name) values (77,'Burleson');
insert into cities (id, name) values (78,'Burton');
insert into cities (id, name) values (79,'Byhalia');
insert into cities (id, name) values (80,'Cadott');
insert into cities (id, name) values (81,'California');
insert into cities (id, name) values (82,'Camanche');
insert into cities (id, name) values (83,'Camillus');
insert into cities (id, name) values (84,'Camp Verde');
insert into cities (id, name) values (85,'Candia');
insert into cities (id, name) values (86,'Cantrall');
insert into cities (id, name) values (87,'Cape May');
insert into cities (id, name) values (88,'Carlinville');
insert into cities (id, name) values (89,'Carmi');
insert into cities (id, name) values (90,'Carriere');
insert into cities (id, name) values (91,'Carterville');
insert into cities (id, name) values (92,'Caseyville');
insert into cities (id, name) values (93,'Castaic');
insert into cities (id, name) values (94,'Cathedral City');
insert into cities (id, name) values (95,'Cecil');
insert into cities (id, name) values (96,'Cedar Park');
insert into cities (id, name) values (97,'Centerbrook');
insert into cities (id, name) values (98,'Central City');
insert into cities (id, name) values (99,'Chadds Ford');
insert into cities (id, name) values (100,'Champlain');
insert into cities (id, name) values (101,'Chapel Hill');
insert into cities (id, name) values (102,'Charlotte');
insert into cities (id, name) values (103,'Chatom');
insert into cities (id, name) values (104,'Chelmsford');
insert into cities (id, name) values (105,'Cherryfield');
insert into cities (id, name) values (106,'Chesterland');
insert into cities (id, name) values (107,'Chicago Heights');
insert into cities (id, name) values (108,'Chincoteague Island');
insert into cities (id, name) values (109,'Chowchilla');
insert into cities (id, name) values (110,'Cicero');
insert into cities (id, name) values (111,'City of Saint Peters');
insert into cities (id, name) values (112,'Clarion');
insert into cities (id, name) values (113,'Clatskanie');
insert into cities (id, name) values (114,'Clear Spring');
insert into cities (id, name) values (115,'Clever');
insert into cities (id, name) values (116,'Clio');
insert into cities (id, name) values (117,'Coaldale');
insert into cities (id, name) values (118,'Cochranton');
insert into cities (id, name) values (119,'Cohoes');
insert into cities (id, name) values (120,'Coleman');
insert into cities (id, name) values (121,'Collingswood');
insert into cities (id, name) values (122,'Colora');
insert into cities (id, name) values (123,'Columbia Station');
insert into cities (id, name) values (124,'Comstock Park');
insert into cities (id, name) values (125,'Conneaut');
insert into cities (id, name) values (126,'Contoocook');
insert into cities (id, name) values (127,'Coopersville');
insert into cities (id, name) values (128,'Coquille');
insert into cities (id, name) values (129,'Corinne');
insert into cities (id, name) values (130,'Corona');
insert into cities (id, name) values (131,'Corydon');
insert into cities (id, name) values (132,'Cottontown');
insert into cities (id, name) values (133,'Coushatta');
insert into cities (id, name) values (134,'Crabtree');
insert into cities (id, name) values (135,'Crawfordsville');
insert into cities (id, name) values (136,'Cresskill');
insert into cities (id, name) values (137,'Crofton');
insert into cities (id, name) values (138,'Crothersville');
insert into cities (id, name) values (139,'Crumpler');
insert into cities (id, name) values (140,'Cullom');
insert into cities (id, name) values (141,'Cupertino');
insert into cities (id, name) values (142,'Dade City');
insert into cities (id, name) values (143,'Dalton');
insert into cities (id, name) values (144,'Dansville');
insert into cities (id, name) values (145,'Davenport');
insert into cities (id, name) values (146,'Daytona Beach');
insert into cities (id, name) values (147,'Dedham');
insert into cities (id, name) values (148,'De Kalb');
insert into cities (id, name) values (149,'Del Mar');
insert into cities (id, name) values (150,'Deming');
insert into cities (id, name) values (151,'Denver City');
insert into cities (id, name) values (152,'Derwood');
insert into cities (id, name) values (153,'Detroit Lakes');
insert into cities (id, name) values (154,'Diamond Bar');
insert into cities (id, name) values (155,'Dillon');
insert into cities (id, name) values (156,'Disputanta');
insert into cities (id, name) values (157,'Dodgewood');
insert into cities (id, name) values (158,'Dorchester');
insert into cities (id, name) values (159,'Dover Plains');
insert into cities (id, name) values (160,'Dresden');
insert into cities (id, name) values (161,'Dry Prong');
insert into cities (id, name) values (162,'Dulles');
insert into cities (id, name) values (163,'Duncanville');
insert into cities (id, name) values (164,'Dunnsville');
insert into cities (id, name) values (165,'Dushore');
insert into cities (id, name) values (166,'Eagle Pass');
insert into cities (id, name) values (167,'East Bend');
insert into cities (id, name) values (168,'Eastchester');
insert into cities (id, name) values (169,'East Freedom');
insert into cities (id, name) values (170,'East Hanover');
insert into cities (id, name) values (171,'East Moline');
insert into cities (id, name) values (172,'East Petersburg');
insert into cities (id, name) values (173,'East Saint Louis');
insert into cities (id, name) values (174,'East Weymouth');
insert into cities (id, name) values (175,'Ector');
insert into cities (id, name) values (176,'Edison');
insert into cities (id, name) values (177,'Egan');
insert into cities (id, name) values (178,'El Campo');
insert into cities (id, name) values (179,'Electra');
insert into cities (id, name) values (180,'Elk Grove');
insert into cities (id, name) values (181,'Elk River');
insert into cities (id, name) values (182,'Ellettsville');
insert into cities (id, name) values (183,'Ellwood City');
insert into cities (id, name) values (184,'Elmora');
insert into cities (id, name) values (185,'El Sobrante');
insert into cities (id, name) values (186,'Emeryville');
insert into cities (id, name) values (187,'Endicott');
insert into cities (id, name) values (188,'Enterprise');
insert into cities (id, name) values (189,'Erving');
insert into cities (id, name) values (190,'Estes Park');
insert into cities (id, name) values (191,'Eureka');
insert into cities (id, name) values (192,'Evergreen Park');
insert into cities (id, name) values (193,'Exton');
insert into cities (id, name) values (194,'Fairdealing');
insert into cities (id, name) values (195,'Fairmount');
insert into cities (id, name) values (196,'Falling Waters');
insert into cities (id, name) values (197,'Far Hills');
insert into cities (id, name) values (198,'Farmville');
insert into cities (id, name) values (199,'Fenelton');
insert into cities (id, name) values (200,'Filer');
insert into cities (id, name) values (201,'Fishersville');
insert into cities (id, name) values (202,'Flanders');
insert into cities (id, name) values (203,'Floral Park');
insert into cities (id, name) values (204,'Flowery Branch');
insert into cities (id, name) values (205,'Fontana');
insert into cities (id, name) values (206,'Forest Lake');
insert into cities (id, name) values (207,'Fort Apache');
insert into cities (id, name) values (208,'Fort Edward');
insert into cities (id, name) values (209,'Fort Mill');
insert into cities (id, name) values (210,'Fort Scott');
insert into cities (id, name) values (211,'Fort Worth');
insert into cities (id, name) values (212,'Fowlerville');
insert into cities (id, name) values (213,'Franklin Lakes');
insert into cities (id, name) values (214,'Fredericksburg');
insert into cities (id, name) values (215,'French Camp');
insert into cities (id, name) values (216,'Friendship');
insert into cities (id, name) values (217,'Ft. Pierce');
insert into cities (id, name) values (218,'Gadsden');
insert into cities (id, name) values (219,'Galesville');
insert into cities (id, name) values (220,'Gans');
insert into cities (id, name) values (221,'Garfield');
insert into cities (id, name) values (222,'Gatlinburg');
insert into cities (id, name) values (223,'George West');
insert into cities (id, name) values (224,'Gibson City');
insert into cities (id, name) values (225,'Gillett');
insert into cities (id, name) values (226,'Gladwyne');
insert into cities (id, name) values (227,'Glencoe');
insert into cities (id, name) values (228,'Glen Head');
insert into cities (id, name) values (229,'Glen Rock');
insert into cities (id, name) values (230,'Globe');
insert into cities (id, name) values (231,'Gold Bar');
insert into cities (id, name) values (232,'Goodfield');
insert into cities (id, name) values (233,'Gordonsville');
insert into cities (id, name) values (234,'Graford');
insert into cities (id, name) values (235,'Grand Forks');
insert into cities (id, name) values (236,'Grand Terrace');
insert into cities (id, name) values (237,'Grantville');
insert into cities (id, name) values (238,'Gray');
insert into cities (id, name) values (239,'Great Lakes');
insert into cities (id, name) values (240,'Greendale');
insert into cities (id, name) values (241,'Greenup');
insert into cities (id, name) values (242,'Gresham');
insert into cities (id, name) values (243,'Grosvenor Dale');
insert into cities (id, name) values (244,'Groveton');
insert into cities (id, name) values (245,'Guntersville');
insert into cities (id, name) values (246,'Gwynn Oak');
insert into cities (id, name) values (247,'Haines City');
insert into cities (id, name) values (248,'Hallsville');
insert into cities (id, name) values (249,'Hammonton');
insert into cities (id, name) values (250,'Hanna City');
insert into cities (id, name) values (251,'Harbor Springs');
insert into cities (id, name) values (252,'Harmon');
insert into cities (id, name) values (253,'Harrison');
insert into cities (id, name) values (254,'Hartford');
insert into cities (id, name) values (255,'Harvey');
insert into cities (id, name) values (256,'Hatboro');
insert into cities (id, name) values (257,'Havertown');
insert into cities (id, name) values (258,'Hayfield');
insert into cities (id, name) values (259,'Hazelwood');
insert into cities (id, name) values (260,'Heavener');
insert into cities (id, name) values (261,'Helendale');
insert into cities (id, name) values (262,'Hempstead');
insert into cities (id, name) values (263,'Hercules');
insert into cities (id, name) values (264,'Herndon');
insert into cities (id, name) values (265,'Hialeah');
insert into cities (id, name) values (266,'Higginsville');
insert into cities (id, name) values (267,'Hildebran');
insert into cities (id, name) values (268,'Hilton');
insert into cities (id, name) values (269,'Hiwasse');
insert into cities (id, name) values (270,'Hogansville');
insert into cities (id, name) values (271,'Holland');
insert into cities (id, name) values (272,'Holly Springs');
insert into cities (id, name) values (273,'Holyoke');
insert into cities (id, name) values (274,'Honeoye Falls');
insert into cities (id, name) values (275,'Hopatcong');
insert into cities (id, name) values (276,'Hopwood');
insert into cities (id, name) values (277,'Hoschton');
insert into cities (id, name) values (278,'Howell');
insert into cities (id, name) values (279,'Hudsonville');
insert into cities (id, name) values (280,'Hungerford');
insert into cities (id, name) values (281,'Huntington Park');
insert into cities (id, name) values (282,'Hurricane');
insert into cities (id, name) values (283,'Idaho Falls');
insert into cities (id, name) values (284,'Incline Village');
insert into cities (id, name) values (285,'Indio');
insert into cities (id, name) values (286,'Interlachen');
insert into cities (id, name) values (287,'Iowa City');
insert into cities (id, name) values (288,'Irvine');
insert into cities (id, name) values (289,'Island Park');
insert into cities (id, name) values (290,'Ivanhoe');
insert into cities (id, name) values (291,'Jacksonville');
insert into cities (id, name) values (292,'Jarreau');
insert into cities (id, name) values (293,'Jefferson Valley');
insert into cities (id, name) values (294,'Jensen Beach');
insert into cities (id, name) values (295,'Jim Thorpe');
insert into cities (id, name) values (296,'Johnston City');
insert into cities (id, name) values (297,'Joseph');
insert into cities (id, name) values (298,'Justice');
insert into cities (id, name) values (299,'Kane');
insert into cities (id, name) values (300,'Kathleen');
insert into cities (id, name) values (301,'Kearneysville');
insert into cities (id, name) values (302,'Kelseyville');
insert into cities (id, name) values (303,'Kennebunk');
insert into cities (id, name) values (304,'Kenova');
insert into cities (id, name) values (305,'Kerrville');
insert into cities (id, name) values (306,'Keyport');
insert into cities (id, name) values (307,'Kilmarnock');
insert into cities (id, name) values (308,'Kings Beach');
insert into cities (id, name) values (309,'Kingstree');
insert into cities (id, name) values (310,'Kirtland');
insert into cities (id, name) values (311,'Knox');
insert into cities (id, name) values (312,'Kunkletown');
insert into cities (id, name) values (313,'Lacon');
insert into cities (id, name) values (314,'Lafayette');
insert into cities (id, name) values (315,'Laguna Woods');
insert into cities (id, name) values (316,'Lake Charles');
insert into cities (id, name) values (317,'Lake Havasu City');
insert into cities (id, name) values (318,'Lake Odessa');
insert into cities (id, name) values (319,'Lake Station');
insert into cities (id, name) values (320,'Lake Zurich');
insert into cities (id, name) values (321,'Lampasas');
insert into cities (id, name) values (322,'Langhorne');
insert into cities (id, name) values (323,'La Plata');
insert into cities (id, name) values (324,'Laredo');
insert into cities (id, name) values (325,'Latrobe');
insert into cities (id, name) values (326,'La Verne');
insert into cities (id, name) values (327,'League City');
insert into cities (id, name) values (328,'Ledyard Center');
insert into cities (id, name) values (329,'Leipsic');
insert into cities (id, name) values (330,'Lenoir');
insert into cities (id, name) values (331,'Le Roy');
insert into cities (id, name) values (332,'Lewisville');
insert into cities (id, name) values (333,'Ligonier');
insert into cities (id, name) values (334,'Lincolnton');
insert into cities (id, name) values (335,'Lindstrom');
insert into cities (id, name) values (336,'Litchfield');
insert into cities (id, name) values (337,'Little Hocking');
insert into cities (id, name) values (338,'Liverpool');
insert into cities (id, name) values (339,'Lockwood');
insert into cities (id, name) values (340,'Lombard');
insert into cities (id, name) values (341,'Long Beach');
insert into cities (id, name) values (342,'Long Prairie');
insert into cities (id, name) values (343,'Loris');
insert into cities (id, name) values (344,'Lostant');
insert into cities (id, name) values (345,'Loves Park');
insert into cities (id, name) values (346,'Lucedale');
insert into cities (id, name) values (347,'Lunenburg');
insert into cities (id, name) values (348,'Lyme');
insert into cities (id, name) values (349,'Lynnwood');
insert into cities (id, name) values (350,'Machesney Park');
insert into cities (id, name) values (351,'Magee');
insert into cities (id, name) values (352,'Maineville');
insert into cities (id, name) values (353,'Malta');
insert into cities (id, name) values (354,'Manchester Center');
insert into cities (id, name) values (355,'Manito');
insert into cities (id, name) values (356,'Mansfield Depot');
insert into cities (id, name) values (357,'Many');
insert into cities (id, name) values (358,'Maple Valley');
insert into cities (id, name) values (359,'Marcellus');
insert into cities (id, name) values (360,'Marion');
insert into cities (id, name) values (361,'Marne');
insert into cities (id, name) values (362,'Marshfield');
insert into cities (id, name) values (363,'Martins Ferry');
insert into cities (id, name) values (364,'Masonville');
insert into cities (id, name) values (365,'Matawan');
insert into cities (id, name) values (366,'Mattoon');
insert into cities (id, name) values (367,'Mays Landing');
insert into cities (id, name) values (368,'McCalla');
insert into cities (id, name) values (369,'McCordsville');
insert into cities (id, name) values (370,'McKees Rocks');
insert into cities (id, name) values (371,'McVeytown');
insert into cities (id, name) values (372,'Medina');
insert into cities (id, name) values (373,'Melville');
insert into cities (id, name) values (374,'Menifee');
insert into cities (id, name) values (375,'Merchantville');
insert into cities (id, name) values (376,'Mertztown');
insert into cities (id, name) values (377,'Mexia');
insert into cities (id, name) values (378,'Middlebury');
insert into cities (id, name) values (379,'Middle Village');
insert into cities (id, name) values (380,'Milbank');
insert into cities (id, name) values (381,'Miller Place');
insert into cities (id, name) values (382,'Millry');
insert into cities (id, name) values (383,'Milwaukee');
insert into cities (id, name) values (384,'Minerva');
insert into cities (id, name) values (385,'Minooka');
insert into cities (id, name) values (386,'Missoula');
insert into cities (id, name) values (387,'Mohnton');
insert into cities (id, name) values (388,'Monee');
insert into cities (id, name) values (389,'Monroe City');
insert into cities (id, name) values (390,'Montclair');
insert into cities (id, name) values (391,'Montgomeryville');
insert into cities (id, name) values (392,'Moodus');
insert into cities (id, name) values (393,'Moose Lake');
insert into cities (id, name) values (394,'Morganfield');
insert into cities (id, name) values (395,'Morrisdale');
insert into cities (id, name) values (396,'Morton Grove');
insert into cities (id, name) values (397,'Mound Bayou');
insert into cities (id, name) values (398,'Mountainville');
insert into cities (id, name) values (399,'Mount Holly');
insert into cities (id, name) values (400,'Mount Olive');
insert into cities (id, name) values (401,'Mount Washington');
insert into cities (id, name) values (402,'Mulberry');
insert into cities (id, name) values (403,'Murfreesboro');
insert into cities (id, name) values (404,'Muskegon');
insert into cities (id, name) values (405,'Nanticoke');
insert into cities (id, name) values (406,'Narragansett');
insert into cities (id, name) values (407,'Navarre');
insert into cities (id, name) values (408,'Neenah');
insert into cities (id, name) values (409,'Neptune Beach');
insert into cities (id, name) values (410,'Newalla');
insert into cities (id, name) values (411,'New Bern');
insert into cities (id, name) values (412,'New Burnside');
insert into cities (id, name) values (413,'New Columbia');
insert into cities (id, name) values (414,'Newfield');
insert into cities (id, name) values (415,'New Holstein');
insert into cities (id, name) values (416,'New Liberty');
insert into cities (id, name) values (417,'New Milford');
insert into cities (id, name) values (418,'Newport Center');
insert into cities (id, name) values (419,'New Rochelle');
insert into cities (id, name) values (420,'Newton Highlands');
insert into cities (id, name) values (421,'New Washington');
insert into cities (id, name) values (422,'Nicholson');
insert into cities (id, name) values (423,'Nobleboro');
insert into cities (id, name) values (424,'Norfolk');
insert into cities (id, name) values (425,'North Attleboro');
insert into cities (id, name) values (426,'North Branford');
insert into cities (id, name) values (427,'North Conway');
insert into cities (id, name) values (428,'North Fork');
insert into cities (id, name) values (429,'North Kingstown');
insert into cities (id, name) values (430,'North Pembroke');
insert into cities (id, name) values (431,'North Ridgeville');
insert into cities (id, name) values (432,'North Tonawanda');
insert into cities (id, name) values (433,'North Windham');
insert into cities (id, name) values (434,'Novelty');
insert into cities (id, name) values (435,'Oak Bluffs');
insert into cities (id, name) values (436,'Oakland');
insert into cities (id, name) values (437,'Oberlin');
insert into cities (id, name) values (438,'Ocean View');
insert into cities (id, name) values (439,'Odessa');
insert into cities (id, name) values (440,'Okanogan');
insert into cities (id, name) values (441,'Old Bethpage');
insert into cities (id, name) values (442,'Old Westbury');
insert into cities (id, name) values (443,'Onancock');
insert into cities (id, name) values (444,'Opolis');
insert into cities (id, name) values (445,'Orangeville');
insert into cities (id, name) values (446,'Oriskany');
insert into cities (id, name) values (447,'Osage Beach');
insert into cities (id, name) values (448,'Ossineke');
insert into cities (id, name) values (449,'Ottsville');
insert into cities (id, name) values (450,'Owatonna');
insert into cities (id, name) values (451,'Oxford');
insert into cities (id, name) values (452,'Pacoima');
insert into cities (id, name) values (453,'Painted Post');
insert into cities (id, name) values (454,'Palm Beach Gardens');
insert into cities (id, name) values (455,'Palm Springs');
insert into cities (id, name) values (456,'Panama City');
insert into cities (id, name) values (457,'Paramus');
insert into cities (id, name) values (458,'Parkton');
insert into cities (id, name) values (459,'Pasco');
insert into cities (id, name) values (460,'Paulding');
insert into cities (id, name) values (461,'Paw Paw');
insert into cities (id, name) values (462,'Pearce');
insert into cities (id, name) values (463,'Peebles');
insert into cities (id, name) values (464,'Pembroke');
insert into cities (id, name) values (465,'Pennsboro');
insert into cities (id, name) values (466,'Pequea');
insert into cities (id, name) values (467,'Peru');
insert into cities (id, name) values (468,'Pflugerville');
insert into cities (id, name) values (469,'Phoenix');
insert into cities (id, name) values (470,'Pigeon Forge');
insert into cities (id, name) values (471,'Pine');
insert into cities (id, name) values (472,'Pinehurst');
insert into cities (id, name) values (473,'Piney Flats');
insert into cities (id, name) values (474,'Pismo Beach');
insert into cities (id, name) values (475,'Pittston');
insert into cities (id, name) values (476,'Plainview');
insert into cities (id, name) values (477,'Platteville');
insert into cities (id, name) values (478,'Pleasant Prairie');
insert into cities (id, name) values (479,'Pocono Pines');
insert into cities (id, name) values (480,'Pomfret');
insert into cities (id, name) values (481,'Ponte Vedra Beach');
insert into cities (id, name) values (482,'Portageville');
insert into cities (id, name) values (483,'Port Crane');
insert into cities (id, name) values (484,'Port Isabel');
insert into cities (id, name) values (485,'Portola Valley');
insert into cities (id, name) values (486,'Port Washington');
insert into cities (id, name) values (487,'Pottsville');
insert into cities (id, name) values (488,'Prague');
insert into cities (id, name) values (489,'Presidio');
insert into cities (id, name) values (490,'Princeville');
insert into cities (id, name) values (491,'Prosperity');
insert into cities (id, name) values (492,'Punta Gorda');
insert into cities (id, name) values (493,'Puyallup');
insert into cities (id, name) values (494,'Queens Village');
insert into cities (id, name) values (495,'Radcliff');
insert into cities (id, name) values (496,'Rancho Cucamonga');
insert into cities (id, name) values (497,'Ranger');
insert into cities (id, name) values (498,'Ravena');
insert into cities (id, name) values (499,'Raymore');
insert into cities (id, name) values (500,'Redding Ridge');
insert into cities (id, name) values (501,'Redwood City');
insert into cities (id, name) values (502,'Reidsville');
insert into cities (id, name) values (503,'Reseda');
insert into cities (id, name) values (504,'Rhoadesville');
insert into cities (id, name) values (505,'Richlands');
insert into cities (id, name) values (506,'Ridgefield');
insert into cities (id, name) values (507,'Rifle');
insert into cities (id, name) values (508,'Rio Rico');
insert into cities (id, name) values (509,'River Forest');
insert into cities (id, name) values (510,'Roanoke');
insert into cities (id, name) values (511,'Roby');
insert into cities (id, name) values (512,'Rockingham');
insert into cities (id, name) values (513,'Rock View');
insert into cities (id, name) values (514,'Rocky River');
insert into cities (id, name) values (515,'Rollinsford');
insert into cities (id, name) values (516,'Roscoe');
insert into cities (id, name) values (517,'Rosemount');
insert into cities (id, name) values (518,'Rossville');
insert into cities (id, name) values (519,'Round Top');
insert into cities (id, name) values (520,'Royal Oak');
insert into cities (id, name) values (521,'Ruleville');
insert into cities (id, name) values (522,'Rushford');
insert into cities (id, name) values (523,'Rutherford');
insert into cities (id, name) values (524,'Sabot');
insert into cities (id, name) values (525,'Sag Harbor');
insert into cities (id, name) values (526,'Saint Ansgar');
insert into cities (id, name) values (527,'Saint George');
insert into cities (id, name) values (528,'Saint Libory');
insert into cities (id, name) values (529,'Saint Robert');
insert into cities (id, name) values (530,'Sallisaw');
insert into cities (id, name) values (531,'San Antonio');
insert into cities (id, name) values (532,'San Diego');
insert into cities (id, name) values (533,'Sandy Hook');
insert into cities (id, name) values (534,'San Juan');
insert into cities (id, name) values (535,'San Pablo');
insert into cities (id, name) values (536,'Santa Cruz');
insert into cities (id, name) values (537,'San Ysidro');
insert into cities (id, name) values (538,'Sardis');
insert into cities (id, name) values (539,'Saugus');
insert into cities (id, name) values (540,'Savanna');
insert into cities (id, name) values (541,'Scandia');
insert into cities (id, name) values (542,'Schofield');
insert into cities (id, name) values (543,'Scotrun');
insert into cities (id, name) values (544,'Scottsville');
insert into cities (id, name) values (545,'Seahurst');
insert into cities (id, name) values (546,'Sebastian');
insert into cities (id, name) values (547,'Seekonk');
insert into cities (id, name) values (548,'Seneca');
insert into cities (id, name) values (549,'Sevierville');
insert into cities (id, name) values (550,'Shamokin Dam');
insert into cities (id, name) values (551,'Shawnee');
insert into cities (id, name) values (552,'Shenandoah');
insert into cities (id, name) values (553,'Sherrills Ford');
insert into cities (id, name) values (554,'Shorewood');
insert into cities (id, name) values (555,'Sidney');
insert into cities (id, name) values (556,'Silvana');
insert into cities (id, name) values (557,'Simi Valley');
insert into cities (id, name) values (558,'Six Mile');
insert into cities (id, name) values (559,'Slatington');
insert into cities (id, name) values (560,'Smithland');
insert into cities (id, name) values (561,'Snellville');
insert into cities (id, name) values (562,'Soda Springs');
insert into cities (id, name) values (563,'Somerville');
insert into cities (id, name) values (564,'Southampton');
insert into cities (id, name) values (565,'South Bristol');
insert into cities (id, name) values (566,'South El Monte');
insert into cities (id, name) values (567,'South Harwich');
insert into cities (id, name) values (568,'South Lyon');
insert into cities (id, name) values (569,'South Plainfield');
insert into cities (id, name) values (570,'South Sanford');
insert into cities (id, name) values (571,'Spanaway');
insert into cities (id, name) values (572,'Sperryville');
insert into cities (id, name) values (573,'Spring Creek');
insert into cities (id, name) values (574,'Springtown');
insert into cities (id, name) values (575,'Stanford');
insert into cities (id, name) values (576,'Startex');
insert into cities (id, name) values (577,'Steamboat Springs');
insert into cities (id, name) values (578,'Sterling Heights');
insert into cities (id, name) values (579,'Stevinson');
insert into cities (id, name) values (580,'Stilwell');
insert into cities (id, name) values (581,'Stone Ridge');
insert into cities (id, name) values (582,'Stout');
insert into cities (id, name) values (583,'Streetsboro');
insert into cities (id, name) values (584,'Sturbridge');
insert into cities (id, name) values (585,'Succasunna');
insert into cities (id, name) values (586,'Suisun');
insert into cities (id, name) values (587,'Sumner');
insert into cities (id, name) values (588,'Sunland');
insert into cities (id, name) values (589,'Surry');
insert into cities (id, name) values (590,'Swampscott');
insert into cities (id, name) values (591,'Sycamore');
insert into cities (id, name) values (592,'Tacoma');
insert into cities (id, name) values (593,'Tallassee');
insert into cities (id, name) values (594,'Tarpon Springs');
insert into cities (id, name) values (595,'Taylors');
insert into cities (id, name) values (596,'Tekoa');
insert into cities (id, name) values (597,'Templeton');
insert into cities (id, name) values (598,'Teutopolis');
insert into cities (id, name) values (599,'Thibodaux');
insert into cities (id, name) values (600,'Thorn Hill');
insert into cities (id, name) values (601,'Tickfaw');
insert into cities (id, name) values (602,'Tionesta');
insert into cities (id, name) values (603,'Togiak');
insert into cities (id, name) values (604,'Toms River');
insert into cities (id, name) values (605,'Topsfield');
insert into cities (id, name) values (606,'Tower City');
insert into cities (id, name) values (607,'Travelers Rest');
insert into cities (id, name) values (608,'Trinity');
insert into cities (id, name) values (609,'Tuba City');
insert into cities (id, name) values (610,'Tulsa');
insert into cities (id, name) values (611,'Tuscaloosa');
insert into cities (id, name) values (612,'Twin Lake');
insert into cities (id, name) values (613,'Tyrone');
insert into cities (id, name) values (614,'Uniondale');
insert into cities (id, name) values (615,'University Place');
insert into cities (id, name) values (616,'Utica');
insert into cities (id, name) values (617,'Valdosta');
insert into cities (id, name) values (618,'Valley Green');
insert into cities (id, name) values (619,'Vancouver');
insert into cities (id, name) values (620,'Veedersburg');
insert into cities (id, name) values (621,'Vernon');
insert into cities (id, name) values (622,'Vian');
insert into cities (id, name) values (623,'Villa Park');
insert into cities (id, name) values (624,'Vinemont');
insert into cities (id, name) values (625,'Voluntown');
insert into cities (id, name) values (626,'Wading River');
insert into cities (id, name) values (627,'Wake');
insert into cities (id, name) values (628,'Walkertown');
insert into cities (id, name) values (629,'Wallkill');
insert into cities (id, name) values (630,'Walton');
insert into cities (id, name) values (631,'War');
insert into cities (id, name) values (632,'Warrendale');
insert into cities (id, name) values (633,'Wasco');
insert into cities (id, name) values (634,'Waterbury Center');
insert into cities (id, name) values (635,'Watervliet');
insert into cities (id, name) values (636,'Waukegan');
insert into cities (id, name) values (637,'Waverly Hall');
insert into cities (id, name) values (638,'Wayzata');
insert into cities (id, name) values (639,'Weimar');
insert into cities (id, name) values (640,'Wells');
insert into cities (id, name) values (641,'Wesley Chapel');
insert into cities (id, name) values (642,'West Bridgewater');
insert into cities (id, name) values (643,'West Des Moines');
insert into cities (id, name) values (644,'Westfield');
insert into cities (id, name) values (645,'West Haven');
insert into cities (id, name) values (646,'West Lafayette');
insert into cities (id, name) values (647,'West Mifflin');
insert into cities (id, name) values (648,'West Olive');
insert into cities (id, name) values (649,'West Richland');
insert into cities (id, name) values (650,'Westtown');
insert into cities (id, name) values (651,'Wetumpka');
insert into cities (id, name) values (652,'Wheat Ridge');
insert into cities (id, name) values (653,'Whitehall Township');
insert into cities (id, name) values (654,'Whitestone');
insert into cities (id, name) values (655,'Whitsett');
insert into cities (id, name) values (656,'Wilbraham');
insert into cities (id, name) values (657,'Willard');
insert into cities (id, name) values (658,'Williamsville');
insert into cities (id, name) values (659,'Willow Hill');
insert into cities (id, name) values (660,'Wilsonville');
insert into cities (id, name) values (661,'Windham');
insert into cities (id, name) values (662,'Winnfield');
insert into cities (id, name) values (663,'Winters');
insert into cities (id, name) values (664,'Wixom');
insert into cities (id, name) values (665,'Wood Dale');
insert into cities (id, name) values (666,'Woodridge');
insert into cities (id, name) values (667,'Woonsocket');
insert into cities (id, name) values (668,'Wrightsville');
insert into cities (id, name) values (669,'Wyncote');
insert into cities (id, name) values (670,'Yaphank');
insert into cities (id, name) values (671,'Yonkers');
insert into cities (id, name) values (672,'Youngsville');
insert into cities (id, name) values (673,'Yulee');
