insert into companies (id, company_name, main_country, annual_revenue) values (1, 'Wal-Mart Stores', 'Montenegro', 81427.0791);
insert into companies (id, company_name, main_country, annual_revenue) values (2, 'Chevron', 'Panama', 14418.4796);
insert into companies (id, company_name, main_country, annual_revenue) values (3, 'ConocoPhillips', 'Micronesia', 46229.5309);
insert into companies (id, company_name, main_country, annual_revenue) values (4, 'General Motors', 'Palau', 34972.2204);
insert into companies (id, company_name, main_country, annual_revenue) values (5, 'General Electric', 'Slovenia', 35444.3799);
insert into companies (id, company_name, main_country, annual_revenue) values (6, 'Berkshire Hathaway', 'Angola', 45732.463);
insert into companies (id, company_name, main_country, annual_revenue) values (7, 'Fannie Mae', 'Bulgaria', 13104.1764);
insert into companies (id, company_name, main_country, annual_revenue) values (8, 'Ford Motor', 'Lithuania', 41113.0267);
insert into companies (id, company_name, main_country, annual_revenue) values (9, 'Hewlett-Packard', 'Morocco', 17703.466);
insert into companies (id, company_name, main_country, annual_revenue) values (10, 'AT&T', 'Chile', 4926.3641);
insert into companies (id, company_name, main_country, annual_revenue) values (11, 'Valero Energy', 'Samoa', 75543.8703);
insert into companies (id, company_name, main_country, annual_revenue) values (12, 'Bank of America Corp.', 'Costa Rica', 84404.1308);
insert into companies (id, company_name, main_country, annual_revenue) values (13, 'McKesson', 'Sierra Leone', 79970.8877);
insert into companies (id, company_name, main_country, annual_revenue) values (14, 'Verizon Communications', 'Cuba', 44749.1161);
insert into companies (id, company_name, main_country, annual_revenue) values (15, 'J.P. Morgan Chase & Co.', 'Equatorial Guinea', 76293.8144);
insert into companies (id, company_name, main_country, annual_revenue) values (16, 'Apple', 'Trinidad & Tobago', 7552.4336);
insert into companies (id, company_name, main_country, annual_revenue) values (17, 'CVS Caremark', 'Eritrea', 18040.1176);
insert into companies (id, company_name, main_country, annual_revenue) values (18, 'International Business Machines', 'Andorra', 8640.359);
insert into companies (id, company_name, main_country, annual_revenue) values (19, 'Citigroup', 'Lesotho', 15764.3248);
insert into companies (id, company_name, main_country, annual_revenue) values (20, 'Cardinal Health', 'Peru', 1722.5777);
insert into companies (id, company_name, main_country, annual_revenue) values (21, 'UnitedHealth Group', 'Japan', 11345.161);
insert into companies (id, company_name, main_country, annual_revenue) values (22, 'Kroger', 'Algeria', 60800.2);
insert into companies (id, company_name, main_country, annual_revenue) values (23, 'Costco Wholesale', 'Kyrgyzstan', 99083.7159);
insert into companies (id, company_name, main_country, annual_revenue) values (24, 'Freddie Mac', 'Brunei', 84966.548);
insert into companies (id, company_name, main_country, annual_revenue) values (25, 'Wells Fargo', 'San Marino', 13814.6415);
insert into companies (id, company_name, main_country, annual_revenue) values (26, 'Procter & Gamble', 'Slovakia', 21128.6317);
insert into companies (id, company_name, main_country, annual_revenue) values (27, 'Archer Daniels Midland', 'Dominica', 56955.9912);
insert into companies (id, company_name, main_country, annual_revenue) values (28, 'AmerisourceBergen', 'Bahamas', 31685.9229);
insert into companies (id, company_name, main_country, annual_revenue) values (29, 'INTL FCStone', 'Sao Tome & Principe', 47387.1201);
insert into companies (id, company_name, main_country, annual_revenue) values (30, 'Marathon Petroleum', 'Singapore', 22531.2838);
insert into companies (id, company_name, main_country, annual_revenue) values (31, 'Walgreen', 'Niger', 1154.1193);
insert into companies (id, company_name, main_country, annual_revenue) values (32, 'American International Group', 'Sierra Leone', 29475.207);
insert into companies (id, company_name, main_country, annual_revenue) values (33, 'MetLife', 'Slovenia', 18449.9979);
insert into companies (id, company_name, main_country, annual_revenue) values (34, 'Home Depot', 'Saint Vincent & the Grenadines', 93817.6489);
insert into companies (id, company_name, main_country, annual_revenue) values (35, 'Medco Health Solutions', 'Egypt', 28314.3146);
insert into companies (id, company_name, main_country, annual_revenue) values (36, 'Microsoft', 'Philippines', 48642.9556);
insert into companies (id, company_name, main_country, annual_revenue) values (37, 'Target', 'Taiwan', 71870.1069);
insert into companies (id, company_name, main_country, annual_revenue) values (38, 'Boeing', 'Malawi', 97724.9087);
insert into companies (id, company_name, main_country, annual_revenue) values (39, 'Pfizer', 'Latvia', 7726.9039);
insert into companies (id, company_name, main_country, annual_revenue) values (40, 'PepsiCo', 'Georgia', 77744.9507);
insert into companies (id, company_name, main_country, annual_revenue) values (41, 'Johnson & Johnson', 'Vanuatu', 59548.6261);
insert into companies (id, company_name, main_country, annual_revenue) values (42, 'State Farm Insurance Cos.', 'Norway', 17124.5783);
insert into companies (id, company_name, main_country, annual_revenue) values (43, 'Dell', 'Czech Republic', 61112.1139);
insert into companies (id, company_name, main_country, annual_revenue) values (44, 'WellPoint', 'Fiji', 79026.9395);
insert into companies (id, company_name, main_country, annual_revenue) values (45, 'Caterpillar', 'Greece', 90262.3881);
insert into companies (id, company_name, main_country, annual_revenue) values (46, 'Dow Chemical', 'Swaziland', 49126.833);
insert into companies (id, company_name, main_country, annual_revenue) values (47, 'United Technologies', 'Myanmar, {Burma}', 10280.3209);
insert into companies (id, company_name, main_country, annual_revenue) values (48, 'Comcast', 'Mozambique', 74642.7668);
insert into companies (id, company_name, main_country, annual_revenue) values (49, 'Kraft Foods', 'Suriname', 75335.8297);
insert into companies (id, company_name, main_country, annual_revenue) values (50, 'Intel', 'Bahamas', 9288.296);
insert into companies (id, company_name, main_country, annual_revenue) values (51, 'United Parcel Service', 'Angola', 6635.9106);
insert into companies (id, company_name, main_country, annual_revenue) values (52, 'Best Buy', 'Myanmar, {Burma}', 76926.5151);
insert into companies (id, company_name, main_country, annual_revenue) values (53, 'Lowes', 'Cambodia', 98960.8386);
insert into companies (id, company_name, main_country, annual_revenue) values (54, 'Prudential Financial', 'Ecuador', 98958.5825);
insert into companies (id, company_name, main_country, annual_revenue) values (55, 'Amazon.com', 'Croatia', 62670.9208);
insert into companies (id, company_name, main_country, annual_revenue) values (56, 'Merck', 'Vietnam', 71025.6356);
insert into companies (id, company_name, main_country, annual_revenue) values (57, 'Lockheed Martin', 'Philippines', 13332.6338);
insert into companies (id, company_name, main_country, annual_revenue) values (58, 'Coca-Cola', 'Bulgaria', 85163.0915);
insert into companies (id, company_name, main_country, annual_revenue) values (59, 'Express Scripts Holding', 'East Timor', 4975.5827);
insert into companies (id, company_name, main_country, annual_revenue) values (60, 'Sunoco', 'Israel', 8093.6714);
insert into companies (id, company_name, main_country, annual_revenue) values (61, 'Enterprise Products Partners', 'Korea North', 77515.6813);
insert into companies (id, company_name, main_country, annual_revenue) values (62, 'Safeway', 'Costa Rica', 11660.2412);
insert into companies (id, company_name, main_country, annual_revenue) values (63, 'Cisco Systems', 'Serbia', 59113.6955);
insert into companies (id, company_name, main_country, annual_revenue) values (64, 'Sears Holdings', 'Myanmar, {Burma}', 48679.9247);
insert into companies (id, company_name, main_country, annual_revenue) values (65, 'Walt Disney', 'Equatorial Guinea', 57397.4236);
insert into companies (id, company_name, main_country, annual_revenue) values (66, 'Johnson Controls', 'Marshall Islands', 97131.8656);
insert into companies (id, company_name, main_country, annual_revenue) values (67, 'Morgan Stanley', 'Switzerland', 38918.0188);
insert into companies (id, company_name, main_country, annual_revenue) values (68, 'Sysco', 'Gabon', 13489.6971);
insert into companies (id, company_name, main_country, annual_revenue) values (69, 'FedEx', 'Austria', 61404.993);
insert into companies (id, company_name, main_country, annual_revenue) values (70, 'Abbott Laboratories', 'Bahrain', 12090.3676);
insert into companies (id, company_name, main_country, annual_revenue) values (71, 'DuPont', 'Benin', 56727.9272);
insert into companies (id, company_name, main_country, annual_revenue) values (72, 'Google', 'Afghanistan', 1760.9906);
insert into companies (id, company_name, main_country, annual_revenue) values (73, 'Hess', 'United Arab Emirates', 56376.1475);
insert into companies (id, company_name, main_country, annual_revenue) values (74, 'Supervalu', 'Bulgaria', 11987.8463);
insert into companies (id, company_name, main_country, annual_revenue) values (75, 'United Continental Holdings', 'South Sudan', 14666.2699);
insert into companies (id, company_name, main_country, annual_revenue) values (76, 'Honeywell International', 'Ivory Coast', 94427.2654);
insert into companies (id, company_name, main_country, annual_revenue) values (77, 'CHS', 'Colombia', 760.9752);
insert into companies (id, company_name, main_country, annual_revenue) values (78, 'Humana', 'Bolivia', 42869.2172);
insert into companies (id, company_name, main_country, annual_revenue) values (79, 'Goldman Sachs Group', 'Uruguay', 59230.5145);
insert into companies (id, company_name, main_country, annual_revenue) values (80, 'Ingram Micro', 'Ethiopia', 76450.4874);
insert into companies (id, company_name, main_country, annual_revenue) values (81, 'Oracle', 'Turkey', 2402.5546);
insert into companies (id, company_name, main_country, annual_revenue) values (82, 'Delta Air Lines', 'Cambodia', 48283.1764);
insert into companies (id, company_name, main_country, annual_revenue) values (83, 'Liberty Mutual Insurance Group', 'Ireland {Republic}', 70050.6883);
insert into companies (id, company_name, main_country, annual_revenue) values (84, 'World Fuel Services', 'Congo', 41249.8248);
insert into companies (id, company_name, main_country, annual_revenue) values (85, 'New York Life Insurance', 'Kiribati', 15304.9997);
insert into companies (id, company_name, main_country, annual_revenue) values (86, 'Plains All American Pipeline', 'Kazakhstan', 427.4023);
insert into companies (id, company_name, main_country, annual_revenue) values (87, 'TIAA-CREF', 'Morocco', 40793.5415);
insert into companies (id, company_name, main_country, annual_revenue) values (88, 'Aetna', 'Mauritania', 30267.8527);
insert into companies (id, company_name, main_country, annual_revenue) values (89, 'Sprint Nextel', 'New Zealand', 53852.6639);
insert into companies (id, company_name, main_country, annual_revenue) values (90, 'News Corp.', 'Eritrea', 45129.6338);
insert into companies (id, company_name, main_country, annual_revenue) values (91, 'General Dynamics', 'Moldova', 58562.4662);
insert into companies (id, company_name, main_country, annual_revenue) values (92, 'Allstate', 'Azerbaijan', 7397.46);
insert into companies (id, company_name, main_country, annual_revenue) values (93, 'HCA Holdings', 'Trinidad & Tobago', 94509.6757);
insert into companies (id, company_name, main_country, annual_revenue) values (94, 'American Express', 'Gambia', 94679.974);
insert into companies (id, company_name, main_country, annual_revenue) values (95, 'Tyson Foods', 'Ghana', 71420.0379);
insert into companies (id, company_name, main_country, annual_revenue) values (96, 'Deere', 'Senegal', 39562.5314);
insert into companies (id, company_name, main_country, annual_revenue) values (97, 'Murphy Oil', 'Liechtenstein', 68442.5619);
insert into companies (id, company_name, main_country, annual_revenue) values (98, 'Philip Morris International', 'Nicaragua', 5649.4634);
insert into companies (id, company_name, main_country, annual_revenue) values (99, 'Nationwide', 'Azerbaijan', 20378.5894);
insert into companies (id, company_name, main_country, annual_revenue) values (100, 'Tesoro', 'Israel', 93343.5209);
insert into companies (id, company_name, main_country, annual_revenue) values (101, '3M', 'Congo', 47630.8578);
insert into companies (id, company_name, main_country, annual_revenue) values (102, 'Time Warner', 'Estonia', 56691.6545);
insert into companies (id, company_name, main_country, annual_revenue) values (103, 'Northrop Grumman', 'Philippines', 9951.2904);
insert into companies (id, company_name, main_country, annual_revenue) values (104, 'DirecTV', 'Thailand', 55773.7018);
insert into companies (id, company_name, main_country, annual_revenue) values (105, 'Publix Super Markets', 'Iraq', 57794.1582);
insert into companies (id, company_name, main_country, annual_revenue) values (106, 'McDonalds', 'Portugal', 93240.6958);
insert into companies (id, company_name, main_country, annual_revenue) values (107, 'Avnet', 'Saint Vincent & the Grenadines', 84645.8518);
insert into companies (id, company_name, main_country, annual_revenue) values (108, 'Tech Data', 'Azerbaijan', 27043.5041);
insert into companies (id, company_name, main_country, annual_revenue) values (109, 'Macys', 'Montenegro', 14531.2437);
insert into companies (id, company_name, main_country, annual_revenue) values (110, 'International Paper', 'Sao Tome & Principe', 88736.237);
insert into companies (id, company_name, main_country, annual_revenue) values (111, 'Travelers Cos.', 'Panama', 68512.0416);
insert into companies (id, company_name, main_country, annual_revenue) values (112, 'Rite Aid', 'Tuvalu', 45179.2784);
insert into companies (id, company_name, main_country, annual_revenue) values (113, 'Staples', 'Mauritius', 32760.9317);
insert into companies (id, company_name, main_country, annual_revenue) values (114, 'Alcoa', 'Somalia', 47716.6823);
insert into companies (id, company_name, main_country, annual_revenue) values (115, 'Northwestern Mutual', 'Swaziland', 5090.8959);
insert into companies (id, company_name, main_country, annual_revenue) values (116, 'Raytheon', 'Uruguay', 76693.5837);
insert into companies (id, company_name, main_country, annual_revenue) values (117, 'Halliburton', 'Ecuador', 43283.0299);
insert into companies (id, company_name, main_country, annual_revenue) values (118, 'Eli Lilly', 'Cameroon', 61866.2278);
insert into companies (id, company_name, main_country, annual_revenue) values (119, 'Emerson Electric', 'Guinea', 36326.694);
insert into companies (id, company_name, main_country, annual_revenue) values (120, 'Massachusetts Mutual Life Insurance', 'Uganda', 33763.4982);
insert into companies (id, company_name, main_country, annual_revenue) values (121, 'Occidental Petroleum', 'Korea South', 27817.665);
insert into companies (id, company_name, main_country, annual_revenue) values (122, 'AMR', 'Qatar', 53574.5804);
insert into companies (id, company_name, main_country, annual_revenue) values (123, 'Fluor', 'Armenia', 27717.2032);
insert into companies (id, company_name, main_country, annual_revenue) values (124, 'TJX', 'Kazakhstan', 65758.605);
insert into companies (id, company_name, main_country, annual_revenue) values (125, 'Goodyear Tire & Rubber', 'Tuvalu', 87732.7833);
insert into companies (id, company_name, main_country, annual_revenue) values (126, 'Xerox', 'Senegal', 78247.6087);
insert into companies (id, company_name, main_country, annual_revenue) values (127, 'Aflac', 'Vatican City', 20130.3504);
insert into companies (id, company_name, main_country, annual_revenue) values (128, 'Manpower', 'Italy', 92432.3868);
insert into companies (id, company_name, main_country, annual_revenue) values (129, 'Cigna', 'Australia', 25316.4636);
insert into companies (id, company_name, main_country, annual_revenue) values (130, 'Hartford Financial Services Group', 'Israel', 67427.266);
insert into companies (id, company_name, main_country, annual_revenue) values (131, 'U.S. Bancorp', 'Brazil', 94340.5831);
insert into companies (id, company_name, main_country, annual_revenue) values (132, 'Arrow Electronics', 'Russian Federation', 26597.2529);
insert into companies (id, company_name, main_country, annual_revenue) values (133, 'Bristol-Myers Squibb', 'San Marino', 21690.5205);
insert into companies (id, company_name, main_country, annual_revenue) values (134, 'Freeport-McMoRan Copper & Gold', 'Ireland {Republic}', 91693.0942);
insert into companies (id, company_name, main_country, annual_revenue) values (135, 'Nike', 'Peru', 87053.9072);
insert into companies (id, company_name, main_country, annual_revenue) values (136, 'Kimberly-Clark', 'Singapore', 26032.4678);
insert into companies (id, company_name, main_country, annual_revenue) values (137, 'Nucor', 'Qatar', 99088.275);
insert into companies (id, company_name, main_country, annual_revenue) values (138, 'EMC', 'Somalia', 46949.8374);
insert into companies (id, company_name, main_country, annual_revenue) values (139, 'United States Steel', 'Bhutan', 55673.1956);
insert into companies (id, company_name, main_country, annual_revenue) values (140, 'Baker Hughes', 'Grenada', 61021.9597);
insert into companies (id, company_name, main_country, annual_revenue) values (141, 'Time Warner Cable', 'Czech Republic', 4205.1284);
insert into companies (id, company_name, main_country, annual_revenue) values (142, 'Union Pacific', 'Jamaica', 24061.0859);
insert into companies (id, company_name, main_country, annual_revenue) values (143, 'United Services Automobile Assn.', 'Bolivia', 59363.6108);
insert into companies (id, company_name, main_country, annual_revenue) values (144, 'Exelon', 'Tuvalu', 91573.8773);
insert into companies (id, company_name, main_country, annual_revenue) values (145, 'Kohls', 'Jamaica', 60218.2832);
insert into companies (id, company_name, main_country, annual_revenue) values (146, 'Whirlpool', 'Zambia', 62194.873);
insert into companies (id, company_name, main_country, annual_revenue) values (147, 'Capital One Financial', 'Korea South', 55611.5383);
insert into companies (id, company_name, main_country, annual_revenue) values (148, 'Illinois Tool Works', 'United Kingdom', 32108.2544);
insert into companies (id, company_name, main_country, annual_revenue) values (149, 'Cummins', 'Ireland {Republic}', 7481.2807);
insert into companies (id, company_name, main_country, annual_revenue) values (150, 'AES', 'Botswana', 73500.9128);
insert into companies (id, company_name, main_country, annual_revenue) values (151, 'Southern', 'Kiribati', 26351.1226);
insert into companies (id, company_name, main_country, annual_revenue) values (152, 'J.C. Penney', 'Burkina', 17075.7871);
insert into companies (id, company_name, main_country, annual_revenue) values (153, 'Apache', 'Ghana', 47456.9777);
insert into companies (id, company_name, main_country, annual_revenue) values (154, 'Colgate-Palmolive', 'Bosnia Herzegovina', 46715.8918);
insert into companies (id, company_name, main_country, annual_revenue) values (155, 'Altria Group', 'Australia', 29107.7095);
insert into companies (id, company_name, main_country, annual_revenue) values (156, 'Jabil Circuit', 'Latvia', 63702.3192);
insert into companies (id, company_name, main_country, annual_revenue) values (157, 'Danaher', 'El Salvador', 98010.3994);
insert into companies (id, company_name, main_country, annual_revenue) values (158, 'Paccar', 'Qatar', 53976.0039);
insert into companies (id, company_name, main_country, annual_revenue) values (159, 'FirstEnergy', 'China', 14376.0696);
insert into companies (id, company_name, main_country, annual_revenue) values (160, 'TRW Automotive Holdings', 'Tanzania', 83470.6083);
insert into companies (id, company_name, main_country, annual_revenue) values (161, 'Computer Sciences', 'Cameroon', 78535.1984);
insert into companies (id, company_name, main_country, annual_revenue) values (162, 'Eaton', 'Zambia', 67719.1776);
insert into companies (id, company_name, main_country, annual_revenue) values (163, 'Medtronic', 'Malawi', 94693.9373);
insert into companies (id, company_name, main_country, annual_revenue) values (164, 'PNC Financial Services Group', 'Taiwan', 5432.3535);
insert into companies (id, company_name, main_country, annual_revenue) values (165, 'Bank of New York Mellon Corp.', 'Thailand', 437.8031);
insert into companies (id, company_name, main_country, annual_revenue) values (166, 'Southwest Airlines', 'Samoa', 72306.5343);
insert into companies (id, company_name, main_country, annual_revenue) values (167, 'Amgen', 'Taiwan', 98433.8078);
insert into companies (id, company_name, main_country, annual_revenue) values (168, 'Progressive', 'Myanmar, {Burma}', 52133.0209);
insert into companies (id, company_name, main_country, annual_revenue) values (169, 'HollyFrontier', 'Mongolia', 77980.467);
insert into companies (id, company_name, main_country, annual_revenue) values (170, 'CenturyLink', 'Iran', 38218.2625);
insert into companies (id, company_name, main_country, annual_revenue) values (171, 'NextEra Energy', 'Saudi Arabia', 89671.4594);
insert into companies (id, company_name, main_country, annual_revenue) values (172, 'Marathon Oil', 'Laos', 23105.0412);
insert into companies (id, company_name, main_country, annual_revenue) values (173, 'L-3 Communications', 'Turkmenistan', 83109.8766);
insert into companies (id, company_name, main_country, annual_revenue) values (174, 'Oneok', 'Paraguay', 20237.4299);
insert into companies (id, company_name, main_country, annual_revenue) values (175, 'American Electric Power', 'Libya', 48534.5377);
insert into companies (id, company_name, main_country, annual_revenue) values (176, 'Viacom', 'Kazakhstan', 80016.726);
insert into companies (id, company_name, main_country, annual_revenue) values (177, 'Qualcomm', 'Uganda', 60855.1008);
insert into companies (id, company_name, main_country, annual_revenue) values (178, 'PG&E Corp.', 'Nigeria', 62393.6725);
insert into companies (id, company_name, main_country, annual_revenue) values (179, 'PPG Industries', 'Trinidad & Tobago', 41267.5976);
insert into companies (id, company_name, main_country, annual_revenue) values (180, 'General Mills', 'Kenya', 44477.4398);
insert into companies (id, company_name, main_country, annual_revenue) values (181, 'Global Partners', 'Mongolia', 88934.2124);
insert into companies (id, company_name, main_country, annual_revenue) values (182, 'Dollar General', 'Tuvalu', 18889.4591);
insert into companies (id, company_name, main_country, annual_revenue) values (183, 'National Oilwell Varco', 'Mauritius', 95168.9553);
insert into companies (id, company_name, main_country, annual_revenue) values (184, 'Gap', 'Cameroon', 16668.0601);
insert into companies (id, company_name, main_country, annual_revenue) values (185, 'Duke Energy', 'Australia', 68087.7025);
insert into companies (id, company_name, main_country, annual_revenue) values (186, 'Dominion Resources', 'Iraq', 89084.156);
insert into companies (id, company_name, main_country, annual_revenue) values (187, 'CBS', 'Grenada', 70082.4505);
insert into companies (id, company_name, main_country, annual_revenue) values (188, 'Lear', 'Iceland', 16831.4148);
insert into companies (id, company_name, main_country, annual_revenue) values (189, 'Loews', 'Grenada', 88117.034);
insert into companies (id, company_name, main_country, annual_revenue) values (190, 'DISH Network', 'Kosovo', 96556.7761);
insert into companies (id, company_name, main_country, annual_revenue) values (191, 'Anadarko Petroleum', 'Haiti', 6527.1045);
insert into companies (id, company_name, main_country, annual_revenue) values (192, 'Navistar International', 'Vanuatu', 80087.1253);
insert into companies (id, company_name, main_country, annual_revenue) values (193, 'Toys "R" Us', 'Albania', 66164.5102);
insert into companies (id, company_name, main_country, annual_revenue) values (194, 'Baxter International', 'Myanmar, {Burma}', 1081.0598);
insert into companies (id, company_name, main_country, annual_revenue) values (195, 'Omnicom Group', 'Gabon', 64663.393);
insert into companies (id, company_name, main_country, annual_revenue) values (196, 'AutoNation', 'Jamaica', 40853.4364);
insert into companies (id, company_name, main_country, annual_revenue) values (197, 'Community Health Systems', 'Uzbekistan', 92850.5937);
insert into companies (id, company_name, main_country, annual_revenue) values (198, 'Constellation Energy', 'Bangladesh', 51234.569);
insert into companies (id, company_name, main_country, annual_revenue) values (199, 'Texas Instruments', 'Thailand', 31153.9513);
insert into companies (id, company_name, main_country, annual_revenue) values (200, 'Ally Financial', 'Eritrea', 39199.0939);
insert into companies (id, company_name, main_country, annual_revenue) values (201, 'Chubb', 'Russian Federation', 63137.9931);
insert into companies (id, company_name, main_country, annual_revenue) values (202, 'Waste Management', 'New Zealand', 60694.7457);
insert into companies (id, company_name, main_country, annual_revenue) values (203, 'Aramark', 'Colombia', 52523.4041);
insert into companies (id, company_name, main_country, annual_revenue) values (204, 'Kellogg', 'Guatemala', 99534.4865);
insert into companies (id, company_name, main_country, annual_revenue) values (205, 'Motorola Mobility Holdings', 'Saint Vincent & the Grenadines', 83837.6141);
insert into companies (id, company_name, main_country, annual_revenue) values (206, 'Dean Foods', 'Iran', 91833.615);
insert into companies (id, company_name, main_country, annual_revenue) values (207, 'US Airways Group', 'Central African Rep', 3508.493);
insert into companies (id, company_name, main_country, annual_revenue) values (208, 'Consolidated Edison', 'Congo', 63340.5494);
insert into companies (id, company_name, main_country, annual_revenue) values (209, 'Land OLakes', 'Burundi', 68431.2342);
insert into companies (id, company_name, main_country, annual_revenue) values (210, 'Edison International', 'Guyana', 91292.8084);
insert into companies (id, company_name, main_country, annual_revenue) values (211, 'PPL', 'Congo {Democratic Rep}', 50154.1385);
insert into companies (id, company_name, main_country, annual_revenue) values (212, 'Yum Brands', 'Panama', 15025.2944);
insert into companies (id, company_name, main_country, annual_revenue) values (213, 'Genuine Parts', 'Bulgaria', 68688.8598);
insert into companies (id, company_name, main_country, annual_revenue) values (214, 'ConAgra Foods', 'Monaco', 31133.8104);
insert into companies (id, company_name, main_country, annual_revenue) values (215, 'Parker Hannifin', 'Colombia', 76365.6288);
insert into companies (id, company_name, main_country, annual_revenue) values (216, 'Marriott International', 'Mauritania', 23732.7315);
insert into companies (id, company_name, main_country, annual_revenue) values (217, 'Smithfield Foods', 'Zimbabwe', 57460.1397);
insert into companies (id, company_name, main_country, annual_revenue) values (218, 'Coventry Health Care', 'Kenya', 63898.7853);
insert into companies (id, company_name, main_country, annual_revenue) values (219, 'Sara Lee', 'Turkey', 42750.9618);
insert into companies (id, company_name, main_country, annual_revenue) values (220, 'Health Net', 'Suriname', 95374.142);
insert into companies (id, company_name, main_country, annual_revenue) values (221, 'Penske Automotive Group', 'Kyrgyzstan', 64688.473);
insert into companies (id, company_name, main_country, annual_revenue) values (222, 'Icahn Enterprises', 'Vanuatu', 56101.0904);
insert into companies (id, company_name, main_country, annual_revenue) values (223, 'Monsanto', 'Denmark', 36934.1129);
insert into companies (id, company_name, main_country, annual_revenue) values (224, 'Thermo Fisher Scientific', 'Ivory Coast', 32139.7554);
insert into companies (id, company_name, main_country, annual_revenue) values (225, 'CSX', 'Iran', 12889.3839);
insert into companies (id, company_name, main_country, annual_revenue) values (226, 'Starbucks', 'Turkey', 45980.7116);
insert into companies (id, company_name, main_country, annual_revenue) values (227, 'eBay', 'Egypt', 57876.9636);
insert into companies (id, company_name, main_country, annual_revenue) values (228, 'Chesapeake Energy', 'Italy', 26091.125);
insert into companies (id, company_name, main_country, annual_revenue) values (229, 'Liberty Interactive', 'Kuwait', 46029.7992);
insert into companies (id, company_name, main_country, annual_revenue) values (230, 'Marsh & McLennan', 'Morocco', 99897.953);
insert into companies (id, company_name, main_country, annual_revenue) values (231, 'Devon Energy', 'Georgia', 30293.116);
insert into companies (id, company_name, main_country, annual_revenue) values (232, 'Office Depot', 'Australia', 60741.6437);
insert into companies (id, company_name, main_country, annual_revenue) values (233, 'Avon Products', 'Thailand', 422.8703);
insert into companies (id, company_name, main_country, annual_revenue) values (234, 'Aon', 'Turkmenistan', 18639.7426);
insert into companies (id, company_name, main_country, annual_revenue) values (235, 'Textron', 'Lesotho', 1536.6951);
insert into companies (id, company_name, main_country, annual_revenue) values (236, 'Huntsman', 'St Lucia', 16822.2456);
insert into companies (id, company_name, main_country, annual_revenue) values (237, 'Praxair', 'Netherlands', 34062.0618);
insert into companies (id, company_name, main_country, annual_revenue) values (238, 'Entergy', 'Burkina', 37428.7311);
insert into companies (id, company_name, main_country, annual_revenue) values (239, 'Public Service Enterprise Group', 'Rwanda', 29620.3955);
insert into companies (id, company_name, main_country, annual_revenue) values (240, 'Norfolk Southern', 'Bulgaria', 94979.5147);
insert into companies (id, company_name, main_country, annual_revenue) values (241, 'Nordstrom', 'France', 10603.3791);
insert into companies (id, company_name, main_country, annual_revenue) values (242, 'First Data', 'Montenegro', 74259.2172);
insert into companies (id, company_name, main_country, annual_revenue) values (243, 'H.J. Heinz', 'Mexico', 23069.9076);
insert into companies (id, company_name, main_country, annual_revenue) values (244, 'SAIC', 'Liechtenstein', 88944.5605);
insert into companies (id, company_name, main_country, annual_revenue) values (245, 'Xcel Energy', 'Philippines', 97211.7489);
insert into companies (id, company_name, main_country, annual_revenue) values (246, 'Lincoln National', 'Bahamas', 44764.2111);
insert into companies (id, company_name, main_country, annual_revenue) values (247, 'Ameriprise Financial', 'Palau', 33458.3892);
insert into companies (id, company_name, main_country, annual_revenue) values (248, 'R.R. Donnelley & Sons', 'Myanmar, {Burma}', 31263.0997);
insert into companies (id, company_name, main_country, annual_revenue) values (249, 'Guardian Life Ins. Co. of America', 'Bolivia', 8224.2424);
insert into companies (id, company_name, main_country, annual_revenue) values (250, 'Applied Materials', 'Algeria', 81385.1026);
insert into companies (id, company_name, main_country, annual_revenue) values (251, 'Stanley Black & Decker', 'Libya', 18314.6507);
insert into companies (id, company_name, main_country, annual_revenue) values (252, 'Synnex', 'Oman', 72582.863);
insert into companies (id, company_name, main_country, annual_revenue) values (253, 'Jacobs Engineering Group', 'Armenia', 30708.8657);
insert into companies (id, company_name, main_country, annual_revenue) values (254, 'Peter Kiewit Sons', 'New Zealand', 99103.7904);
insert into companies (id, company_name, main_country, annual_revenue) values (255, 'Limited Brands', 'Swaziland', 92616.9016);
insert into companies (id, company_name, main_country, annual_revenue) values (256, 'Newmont Mining', 'Luxembourg', 65428.2899);
insert into companies (id, company_name, main_country, annual_revenue) values (257, 'Genworth Financial', 'Finland', 82538.0484);
insert into companies (id, company_name, main_country, annual_revenue) values (258, 'C.H. Robinson Worldwide', 'Kuwait', 3966.4243);
insert into companies (id, company_name, main_country, annual_revenue) values (259, 'Unum Group', 'Uzbekistan', 32225.5693);
insert into companies (id, company_name, main_country, annual_revenue) values (260, 'Liberty Global', 'France', 44921.3912);
insert into companies (id, company_name, main_country, annual_revenue) values (261, 'State Street Corp.', 'Peru', 99912.1658);
insert into companies (id, company_name, main_country, annual_revenue) values (262, 'EOG Resources', 'South Sudan', 90674.9827);
insert into companies (id, company_name, main_country, annual_revenue) values (263, 'Whole Foods Market', 'Maldives', 47808.9616);
insert into companies (id, company_name, main_country, annual_revenue) values (264, 'Air Products & Chemicals', 'Syria', 73426.6372);
insert into companies (id, company_name, main_country, annual_revenue) values (265, 'Sempra Energy', 'Uruguay', 71639.1519);
insert into companies (id, company_name, main_country, annual_revenue) values (266, 'BB&T Corp.', 'Liechtenstein', 77289.8912);
insert into companies (id, company_name, main_country, annual_revenue) values (267, 'Mosaic', 'Ethiopia', 15374.6396);
insert into companies (id, company_name, main_country, annual_revenue) values (268, 'Automatic Data Processing', 'Mozambique', 81614.3425);
insert into companies (id, company_name, main_country, annual_revenue) values (269, 'CDW', 'Jamaica', 43611.3754);
insert into companies (id, company_name, main_country, annual_revenue) values (270, 'SunTrust Banks', 'Switzerland', 61853.1327);
insert into companies (id, company_name, main_country, annual_revenue) values (271, 'Tenet Healthcare', 'Guinea', 84173.8639);
insert into companies (id, company_name, main_country, annual_revenue) values (272, 'GameStop', 'Serbia', 96227.0843);
insert into companies (id, company_name, main_country, annual_revenue) values (273, 'Motorola Solutions', 'Tanzania', 23298.4442);
insert into companies (id, company_name, main_country, annual_revenue) values (274, 'URS', 'Australia', 54903.3319);
insert into companies (id, company_name, main_country, annual_revenue) values (275, 'Western Digital', 'Morocco', 50427.7194);
insert into companies (id, company_name, main_country, annual_revenue) values (276, 'VF', 'Kyrgyzstan', 8599.9725);
insert into companies (id, company_name, main_country, annual_revenue) values (277, 'Las Vegas Sands', 'Georgia', 56645.9046);
insert into companies (id, company_name, main_country, annual_revenue) values (278, 'CarMax', 'Netherlands', 94329.8072);
insert into companies (id, company_name, main_country, annual_revenue) values (279, 'KBR', 'Macedonia', 7737.4693);
insert into companies (id, company_name, main_country, annual_revenue) values (280, 'Visa', 'Antigua & Deps', 38106.297);
insert into companies (id, company_name, main_country, annual_revenue) values (281, 'Enbridge Energy Partners', 'India', 17960.5878);
insert into companies (id, company_name, main_country, annual_revenue) values (282, 'BlackRock', 'Zambia', 11359.1422);
insert into companies (id, company_name, main_country, annual_revenue) values (283, 'NRG Energy', 'Pakistan', 31127.2658);
insert into companies (id, company_name, main_country, annual_revenue) values (284, 'Western Refining', 'Barbados', 21638.3269);
insert into companies (id, company_name, main_country, annual_revenue) values (285, 'Progress Energy', 'East Timor', 97176.6437);
insert into companies (id, company_name, main_country, annual_revenue) values (286, 'DTE Energy', 'Belarus', 92905.6006);
insert into companies (id, company_name, main_country, annual_revenue) values (287, 'Caesars Entertainment', 'Czech Republic', 4994.9251);
insert into companies (id, company_name, main_country, annual_revenue) values (288, 'Reinsurance Group of America', 'Morocco', 5306.3622);
insert into companies (id, company_name, main_country, annual_revenue) values (289, 'Estée Lauder', 'Suriname', 53638.0192);
insert into companies (id, company_name, main_country, annual_revenue) values (290, 'Micron Technology', 'Nauru', 60992.5965);
insert into companies (id, company_name, main_country, annual_revenue) values (291, 'AGCO', 'Macedonia', 1988.6654);
insert into companies (id, company_name, main_country, annual_revenue) values (292, 'Sherwin-Williams', 'Monaco', 91881.7726);
insert into companies (id, company_name, main_country, annual_revenue) values (293, 'Bed Bath & Beyond', 'Namibia', 62524.6318);
insert into companies (id, company_name, main_country, annual_revenue) values (294, 'Principal Financial', 'Uruguay', 78607.0074);
insert into companies (id, company_name, main_country, annual_revenue) values (295, 'Crown Holdings', 'Angola', 3771.3925);
insert into companies (id, company_name, main_country, annual_revenue) values (296, 'Ball', 'United States', 34818.5872);
insert into companies (id, company_name, main_country, annual_revenue) values (297, 'Owens & Minor', 'Dominican Republic', 82058.7092);
insert into companies (id, company_name, main_country, annual_revenue) values (298, 'Ross Stores', 'Mexico', 85198.6625);
insert into companies (id, company_name, main_country, annual_revenue) values (299, 'Discover Financial Services', 'Serbia', 25358.6872);
insert into companies (id, company_name, main_country, annual_revenue) values (300, 'Family Dollar Stores', 'France', 48451.231);
insert into companies (id, company_name, main_country, annual_revenue) values (301, 'Reynolds American', 'Tanzania', 5443.2383);
insert into companies (id, company_name, main_country, annual_revenue) values (302, 'Henry Schein', 'Tonga', 15597.8336);
insert into companies (id, company_name, main_country, annual_revenue) values (303, 'Dover', 'Guinea', 27397.2137);
insert into companies (id, company_name, main_country, annual_revenue) values (304, 'CenterPoint Energy', 'Tuvalu', 98942.0397);
insert into companies (id, company_name, main_country, annual_revenue) values (305, 'Gilead Sciences', 'Malaysia', 35459.5887);
insert into companies (id, company_name, main_country, annual_revenue) values (306, 'Ashland', 'Nepal', 34533.0677);
insert into companies (id, company_name, main_country, annual_revenue) values (307, 'Stryker', 'Lesotho', 71746.4267);
insert into companies (id, company_name, main_country, annual_revenue) values (308, 'Hertz Global Holdings', 'Lebanon', 7607.8604);
insert into companies (id, company_name, main_country, annual_revenue) values (309, 'Assurant', 'Zimbabwe', 53792.0913);
insert into companies (id, company_name, main_country, annual_revenue) values (310, 'Kinder Morgan', 'Kiribati', 68032.7603);
insert into companies (id, company_name, main_country, annual_revenue) values (311, 'Energy Transfer Equity', 'Sri Lanka', 36499.4423);
insert into companies (id, company_name, main_country, annual_revenue) values (312, 'Autoliv', 'Somalia', 43136.7512);
insert into companies (id, company_name, main_country, annual_revenue) values (313, 'Republic Services', 'Russian Federation', 69952.9242);
insert into companies (id, company_name, main_country, annual_revenue) values (314, 'Reliance Steel & Aluminum', 'Czech Republic', 59251.0104);
insert into companies (id, company_name, main_country, annual_revenue) values (315, 'Peabody Energy', 'Belarus', 8116.9661);
insert into companies (id, company_name, main_country, annual_revenue) values (316, 'Great Atlantic & Pacific Tea', 'Denmark', 97764.464);
insert into companies (id, company_name, main_country, annual_revenue) values (317, 'W.W. Grainger', 'Comoros', 66011.3904);
insert into companies (id, company_name, main_country, annual_revenue) values (318, 'Goodrich', 'Bhutan', 95332.0495);
insert into companies (id, company_name, main_country, annual_revenue) values (319, 'AutoZone', 'Jamaica', 23776.6695);
insert into companies (id, company_name, main_country, annual_revenue) values (320, 'Visteon', 'Afghanistan', 8766.5379);
insert into companies (id, company_name, main_country, annual_revenue) values (321, 'AECOM Technology', 'Korea South', 44237.5967);
insert into companies (id, company_name, main_country, annual_revenue) values (322, 'Steel Dynamics', 'Indonesia', 51355.2985);
insert into companies (id, company_name, main_country, annual_revenue) values (323, 'Coca-Cola Enterprises', 'Gabon', 12547.9681);
insert into companies (id, company_name, main_country, annual_revenue) values (324, 'Williams', 'Central African Rep', 15761.3777);
insert into companies (id, company_name, main_country, annual_revenue) values (325, 'Commercial Metals', 'Samoa', 97173.9537);
insert into companies (id, company_name, main_country, annual_revenue) values (326, 'Hormel Foods', 'Gabon', 44556.6115);
insert into companies (id, company_name, main_country, annual_revenue) values (327, 'Corning', 'Tanzania', 2981.8565);
insert into companies (id, company_name, main_country, annual_revenue) values (328, 'TravelCenters of America', 'Panama', 50198.6754);
insert into companies (id, company_name, main_country, annual_revenue) values (329, 'Sonic Automotive', 'Finland', 53744.8013);
insert into companies (id, company_name, main_country, annual_revenue) values (330, 'MGM Resorts International', 'St Lucia', 21974.5898);
insert into companies (id, company_name, main_country, annual_revenue) values (331, 'Thrivent Financial for Lutherans', 'Morocco', 28704.0022);
insert into companies (id, company_name, main_country, annual_revenue) values (332, 'Becton Dickinson', 'Guyana', 23417.0312);
insert into companies (id, company_name, main_country, annual_revenue) values (333, 'Campbell Soup', 'Barbados', 31600.4868);
insert into companies (id, company_name, main_country, annual_revenue) values (334, 'Boston Scientific', 'Australia', 16114.5943);
insert into companies (id, company_name, main_country, annual_revenue) values (335, 'Dana Holding', 'Korea North', 22495.9029);
insert into companies (id, company_name, main_country, annual_revenue) values (336, 'Oshkosh', 'Cambodia', 1328.9757);
insert into companies (id, company_name, main_country, annual_revenue) values (337, 'Masco', 'Ivory Coast', 82807.3471);
insert into companies (id, company_name, main_country, annual_revenue) values (338, 'Universal Health Services', 'Paraguay', 69161.1554);
insert into companies (id, company_name, main_country, annual_revenue) values (339, 'Ameren', 'Venezuela', 4886.0093);
insert into companies (id, company_name, main_country, annual_revenue) values (340, 'Quest Diagnostics', 'Mauritania', 87650.4028);
insert into companies (id, company_name, main_country, annual_revenue) values (341, 'Darden Restaurants', 'Vatican City', 91732.4437);
insert into companies (id, company_name, main_country, annual_revenue) values (342, 'Regions Financial', 'Afghanistan', 33410.2286);
insert into companies (id, company_name, main_country, annual_revenue) values (343, 'Broadcom', 'Micronesia', 25092.6326);
insert into companies (id, company_name, main_country, annual_revenue) values (344, 'Owens-Illinois', 'Laos', 98066.9616);
insert into companies (id, company_name, main_country, annual_revenue) values (345, 'Eastman Chemical', 'Cape Verde', 42804.1026);
insert into companies (id, company_name, main_country, annual_revenue) values (346, 'Pantry', 'Pakistan', 67359.3612);
insert into companies (id, company_name, main_country, annual_revenue) values (347, 'Cablevision Systems', 'Suriname', 73483.7927);
insert into companies (id, company_name, main_country, annual_revenue) values (348, 'Dole Food', 'Philippines', 80221.8377);
insert into companies (id, company_name, main_country, annual_revenue) values (349, 'Tenneco', 'Turkmenistan', 40781.7584);
insert into companies (id, company_name, main_country, annual_revenue) values (350, 'Charter Communications', 'Panama', 5798.518);
insert into companies (id, company_name, main_country, annual_revenue) values (351, 'Spectrum Group International', 'Cuba', 94725.3848);
insert into companies (id, company_name, main_country, annual_revenue) values (352, 'Franklin Resources', 'Kosovo', 88727.5407);
insert into companies (id, company_name, main_country, annual_revenue) values (353, 'OfficeMax', 'Bhutan', 58528.1276);
insert into companies (id, company_name, main_country, annual_revenue) values (354, 'BorgWarner', 'Zimbabwe', 87739.0769);
insert into companies (id, company_name, main_country, annual_revenue) values (355, 'Alpha Natural Resources', 'Afghanistan', 77617.2019);
insert into companies (id, company_name, main_country, annual_revenue) values (356, 'Energy Future Holdings', 'Djibouti', 14637.8393);
insert into companies (id, company_name, main_country, annual_revenue) values (357, 'Interpublic Group', 'Sao Tome & Principe', 2704.5385);
insert into companies (id, company_name, main_country, annual_revenue) values (358, 'DaVita', 'Mauritania', 92259.3429);
insert into companies (id, company_name, main_country, annual_revenue) values (359, 'Barnes & Noble', 'Brunei', 95114.7432);
insert into companies (id, company_name, main_country, annual_revenue) values (360, 'Targa Resources', 'Taiwan', 38380.6719);
insert into companies (id, company_name, main_country, annual_revenue) values (361, 'Cameron International', 'Bosnia Herzegovina', 23974.2602);
insert into companies (id, company_name, main_country, annual_revenue) values (362, 'Winn-Dixie Stores', 'Ecuador', 9685.9774);
insert into companies (id, company_name, main_country, annual_revenue) values (363, 'Calpine', 'Botswana', 55573.5236);
insert into companies (id, company_name, main_country, annual_revenue) values (364, 'Ecolab', 'Syria', 13854.7618);
insert into companies (id, company_name, main_country, annual_revenue) values (365, 'Cliffs Natural Resources', 'Tuvalu', 84813.6435);
insert into companies (id, company_name, main_country, annual_revenue) values (366, 'Avery Dennison', 'Botswana', 8819.6831);
insert into companies (id, company_name, main_country, annual_revenue) values (367, 'Celanese', 'Eritrea', 80212.5502);
insert into companies (id, company_name, main_country, annual_revenue) values (368, 'NII Holdings', 'Palau', 41599.1383);
insert into companies (id, company_name, main_country, annual_revenue) values (369, 'MasterCard', 'Cameroon', 69439.9575);
insert into companies (id, company_name, main_country, annual_revenue) values (370, 'Jarden', 'Fiji', 61921.0825);
insert into companies (id, company_name, main_country, annual_revenue) values (371, 'Fifth Third Bancorp', 'Seychelles', 78806.4069);
insert into companies (id, company_name, main_country, annual_revenue) values (372, 'Dollar Tree', 'Yemen', 78997.5213);
insert into companies (id, company_name, main_country, annual_revenue) values (373, 'Weyerhaeuser', 'Myanmar, {Burma}', 74139.5887);
insert into companies (id, company_name, main_country, annual_revenue) values (374, 'Agilent Technologies', 'Guinea', 73950.6576);
insert into companies (id, company_name, main_country, annual_revenue) values (375, 'Sanmina-SCI', 'Seychelles', 3076.852);
insert into companies (id, company_name, main_country, annual_revenue) values (376, 'NuStar Energy', 'Ecuador', 61841.2859);
insert into companies (id, company_name, main_country, annual_revenue) values (377, 'Advanced Micro Devices', 'Laos', 91744.0459);
insert into companies (id, company_name, main_country, annual_revenue) values (378, 'Terex', 'Panama', 9597.7189);
insert into companies (id, company_name, main_country, annual_revenue) values (379, 'CMS Energy', 'Bahrain', 98835.9984);
insert into companies (id, company_name, main_country, annual_revenue) values (380, 'AK Steel Holding', 'Korea North', 51056.0565);
insert into companies (id, company_name, main_country, annual_revenue) values (381, 'American Family Insurance Group', 'Malawi', 2123.5001);
insert into companies (id, company_name, main_country, annual_revenue) values (382, 'Dillards', 'Bahamas', 9809.799);
insert into companies (id, company_name, main_country, annual_revenue) values (383, 'McGraw-Hill', 'Uzbekistan', 10429.7674);
insert into companies (id, company_name, main_country, annual_revenue) values (384, 'Amerigroup', 'Marshall Islands', 34305.5834);
insert into companies (id, company_name, main_country, annual_revenue) values (385, 'Anixter International', 'Congo', 46019.2183);
insert into companies (id, company_name, main_country, annual_revenue) values (386, 'Precision Castparts', 'New Zealand', 36877.5471);
insert into companies (id, company_name, main_country, annual_revenue) values (387, 'Mattel', 'Panama', 44745.9379);
insert into companies (id, company_name, main_country, annual_revenue) values (388, 'Omnicare', 'San Marino', 47429.7085);
insert into companies (id, company_name, main_country, annual_revenue) values (389, 'Corn Products International', 'Congo', 45470.2256);
insert into companies (id, company_name, main_country, annual_revenue) values (390, 'Symantec', 'Namibia', 7657.0227);
insert into companies (id, company_name, main_country, annual_revenue) values (391, 'Advance Auto Parts', 'Cuba', 27502.8998);
insert into companies (id, company_name, main_country, annual_revenue) values (392, 'Core-Mark Holding', 'Japan', 18384.2396);
insert into companies (id, company_name, main_country, annual_revenue) values (393, 'CC Media Holdings', 'Libya', 791.8877);
insert into companies (id, company_name, main_country, annual_revenue) values (394, 'Expeditors International of Washington', 'Korea North', 88598.9882);
insert into companies (id, company_name, main_country, annual_revenue) values (395, 'Mylan', 'Ecuador', 45566.4823);
insert into companies (id, company_name, main_country, annual_revenue) values (396, 'Wesco International', 'Thailand', 99730.686);
insert into companies (id, company_name, main_country, annual_revenue) values (397, 'Cognizant Technology Solutions', 'Brazil', 35204.2451);
insert into companies (id, company_name, main_country, annual_revenue) values (398, 'Consol Energy', 'Vietnam', 68746.902);
insert into companies (id, company_name, main_country, annual_revenue) values (399, 'PetSmart', 'Mali', 36976.7236);
insert into companies (id, company_name, main_country, annual_revenue) values (400, 'WellCare Health Plans', 'Croatia', 55496.8823);
insert into companies (id, company_name, main_country, annual_revenue) values (401, 'CF Industries Holdings', 'Oman', 90147.6557);
insert into companies (id, company_name, main_country, annual_revenue) values (402, 'UGI', 'Cyprus', 91530.6253);
insert into companies (id, company_name, main_country, annual_revenue) values (403, 'Hershey', 'Jordan', 94168.961);
insert into companies (id, company_name, main_country, annual_revenue) values (404, 'Group 1 Automotive', 'Italy', 1180.5786);
insert into companies (id, company_name, main_country, annual_revenue) values (405, 'MeadWestvaco', 'United Arab Emirates', 7038.1133);
insert into companies (id, company_name, main_country, annual_revenue) values (406, 'Ryder System', 'El Salvador', 38416.272);
insert into companies (id, company_name, main_country, annual_revenue) values (407, 'Eastman Kodak', 'Afghanistan', 54278.2455);
insert into companies (id, company_name, main_country, annual_revenue) values (408, 'NiSource', 'Senegal', 82976.8603);
insert into companies (id, company_name, main_country, annual_revenue) values (409, 'Rockwell Automation', 'Iceland', 24303.7758);
insert into companies (id, company_name, main_country, annual_revenue) values (410, 'Mutual of Omaha Insurance', 'Egypt', 22376.1227);
insert into companies (id, company_name, main_country, annual_revenue) values (411, 'Shaw Group', 'Andorra', 69437.089);
insert into companies (id, company_name, main_country, annual_revenue) values (412, 'Harris', 'Belarus', 87603.9039);
insert into companies (id, company_name, main_country, annual_revenue) values (413, 'Newell Rubbermaid', 'Croatia', 28183.4215);
insert into companies (id, company_name, main_country, annual_revenue) values (414, 'Pepco Holdings', 'Mexico', 9199.5932);
insert into companies (id, company_name, main_country, annual_revenue) values (415, 'CBRE Group', 'Maldives', 3891.2482);
insert into companies (id, company_name, main_country, annual_revenue) values (416, 'Dr Pepper Snapple Group', 'Mauritania', 3070.0512);
insert into companies (id, company_name, main_country, annual_revenue) values (417, 'Avis Budget Group', 'Mongolia', 72111.9811);
insert into companies (id, company_name, main_country, annual_revenue) values (418, 'PVH', 'Kyrgyzstan', 95482.9341);
insert into companies (id, company_name, main_country, annual_revenue) values (419, 'Pacific Life', 'Malta', 36246.0662);
insert into companies (id, company_name, main_country, annual_revenue) values (420, 'General Cable', 'Belgium', 63972.8995);
insert into companies (id, company_name, main_country, annual_revenue) values (421, 'Exelis', 'Spain', 92370.1864);
insert into companies (id, company_name, main_country, annual_revenue) values (422, 'Health Management Associates', 'Azerbaijan', 85891.5246);
insert into companies (id, company_name, main_country, annual_revenue) values (423, 'OReilly Automotive', 'Myanmar, {Burma}', 55761.9811);
insert into companies (id, company_name, main_country, annual_revenue) values (424, 'Fidelity National Information Services', 'Liberia', 8293.4614);
insert into companies (id, company_name, main_country, annual_revenue) values (425, 'SLM', 'Somalia', 38482.5942);
insert into companies (id, company_name, main_country, annual_revenue) values (426, 'Seaboard', 'Belize', 3502.3519);
insert into companies (id, company_name, main_country, annual_revenue) values (427, 'Emcor Group', 'Iran', 35675.3591);
insert into companies (id, company_name, main_country, annual_revenue) values (428, 'Auto-Owners Insurance', 'Iceland', 36413.8173);
insert into companies (id, company_name, main_country, annual_revenue) values (429, 'SanDisk', 'Georgia', 41061.4584);
insert into companies (id, company_name, main_country, annual_revenue) values (430, 'Ralph Lauren', 'Maldives', 62570.5514);
insert into companies (id, company_name, main_country, annual_revenue) values (431, 'Mohawk Industries', 'Kyrgyzstan', 51756.3368);
insert into companies (id, company_name, main_country, annual_revenue) values (432, 'Sealed Air', 'Brunei', 25903.9729);
insert into companies (id, company_name, main_country, annual_revenue) values (433, 'Starwood Hotels & Resorts', 'Ghana', 83852.6828);
insert into companies (id, company_name, main_country, annual_revenue) values (434, 'Foot Locker', 'Suriname', 72977.6059);
insert into companies (id, company_name, main_country, annual_revenue) values (435, 'Domtar', 'Estonia', 37615.1031);
insert into companies (id, company_name, main_country, annual_revenue) values (436, 'St. Jude Medical', 'Samoa', 97440.1787);
insert into companies (id, company_name, main_country, annual_revenue) values (437, 'Spectra Energy', 'Antigua & Deps', 76447.0614);
insert into companies (id, company_name, main_country, annual_revenue) values (438, 'Booz Allen Hamilton Holding', 'Myanmar, {Burma}', 83365.7228);
insert into companies (id, company_name, main_country, annual_revenue) values (439, 'CH2M Hill', 'Tunisia', 5879.8693);
insert into companies (id, company_name, main_country, annual_revenue) values (440, 'Kelly Services', 'Finland', 20650.3769);
insert into companies (id, company_name, main_country, annual_revenue) values (441, 'Avaya', 'Central African Rep', 91915.8935);
insert into companies (id, company_name, main_country, annual_revenue) values (442, 'Laboratory Corp. of America', 'Libya', 71915.8772);
insert into companies (id, company_name, main_country, annual_revenue) values (443, 'Kindred Healthcare', 'Niger', 27573.2186);
insert into companies (id, company_name, main_country, annual_revenue) values (444, 'Western Union', 'Laos', 87501.7421);
insert into companies (id, company_name, main_country, annual_revenue) values (445, 'SPX', 'Iran', 16015.2357);
insert into companies (id, company_name, main_country, annual_revenue) values (446, 'NCR', 'Cuba', 73050.2612);
insert into companies (id, company_name, main_country, annual_revenue) values (447, 'Allergan', 'China', 83669.2458);
insert into companies (id, company_name, main_country, annual_revenue) values (448, 'Rock-Tenn', 'Kuwait', 93889.7187);
insert into companies (id, company_name, main_country, annual_revenue) values (449, 'Live Nation Entertainment', 'Marshall Islands', 55486.736);
insert into companies (id, company_name, main_country, annual_revenue) values (450, 'Graybar Electric', 'Belize', 56834.6826);
insert into companies (id, company_name, main_country, annual_revenue) values (451, 'Momentive Specialty Chemicals', 'Algeria', 24382.72);
insert into companies (id, company_name, main_country, annual_revenue) values (452, 'Centene', 'Bolivia', 13786.99);
insert into companies (id, company_name, main_country, annual_revenue) values (453, 'Owens Corning', 'Guinea-Bissau', 44729.6846);
insert into companies (id, company_name, main_country, annual_revenue) values (454, 'Catalyst Health Solutions', 'Montenegro', 35201.9192);
insert into companies (id, company_name, main_country, annual_revenue) values (455, 'Clorox', 'East Timor', 56782.2981);
insert into companies (id, company_name, main_country, annual_revenue) values (456, 'Bemis', 'Mozambique', 56883.655);
insert into companies (id, company_name, main_country, annual_revenue) values (457, 'Harley-Davidson', 'Solomon Islands', 96110.7114);
insert into companies (id, company_name, main_country, annual_revenue) values (458, 'Con-way', 'Venezuela', 35122.7166);
insert into companies (id, company_name, main_country, annual_revenue) values (459, 'Insight Enterprises', 'Congo', 13993.5139);
insert into companies (id, company_name, main_country, annual_revenue) values (460, 'Pitney Bowes', 'Nigeria', 74559.6311);
insert into companies (id, company_name, main_country, annual_revenue) values (461, 'Wynn Resorts', 'St Lucia', 87045.6762);
insert into companies (id, company_name, main_country, annual_revenue) values (462, 'BrightPoint', 'Haiti', 56842.175);
insert into companies (id, company_name, main_country, annual_revenue) values (463, 'Frontier Communications', 'Argentina', 36602.2294);
insert into companies (id, company_name, main_country, annual_revenue) values (464, 'Gannett', 'Central African Rep', 55924.1725);
insert into companies (id, company_name, main_country, annual_revenue) values (465, 'Dicks Sporting Goods', 'Antigua & Deps', 66037.9789);
insert into companies (id, company_name, main_country, annual_revenue) values (466, 'Big Lots', 'Brunei', 71261.8742);
insert into companies (id, company_name, main_country, annual_revenue) values (467, 'Allegheny Technologies', 'Solomon Islands', 55280.283);
insert into companies (id, company_name, main_country, annual_revenue) values (468, 'Telephone & Data Systems', 'Armenia', 64018.5134);
insert into companies (id, company_name, main_country, annual_revenue) values (469, 'Timken', 'Lesotho', 41326.0649);
insert into companies (id, company_name, main_country, annual_revenue) values (470, 'W.R. Berkley', 'Congo', 70945.0406);
insert into companies (id, company_name, main_country, annual_revenue) values (471, 'Fidelity National Financial', 'Nepal', 98584.0103);
insert into companies (id, company_name, main_country, annual_revenue) values (472, 'Caseys General Stores', 'Mauritius', 41860.679);
insert into companies (id, company_name, main_country, annual_revenue) values (473, 'NetApp', 'Azerbaijan', 27886.6213);
insert into companies (id, company_name, main_country, annual_revenue) values (474, 'FMC Technologies', 'Fiji', 27257.5697);
insert into companies (id, company_name, main_country, annual_revenue) values (475, 'Biogen Idec', 'Grenada', 47025.0596);
insert into companies (id, company_name, main_country, annual_revenue) values (476, 'CVR Energy', 'Kosovo', 8673.507);
insert into companies (id, company_name, main_country, annual_revenue) values (477, 'United Stationers', 'Denmark', 46777.9601);
insert into companies (id, company_name, main_country, annual_revenue) values (478, 'Host Hotels & Resorts', 'Myanmar, {Burma}', 57198.3526);
insert into companies (id, company_name, main_country, annual_revenue) values (479, 'SunGard Data Systems', 'Philippines', 36843.8145);
insert into companies (id, company_name, main_country, annual_revenue) values (480, 'Meritor', 'Zambia', 60532.3317);
insert into companies (id, company_name, main_country, annual_revenue) values (481, 'Western & Southern Financial Group', 'Netherlands', 3650.3755);
insert into companies (id, company_name, main_country, annual_revenue) values (482, 'Yahoo', 'Laos', 88480.6245);
insert into companies (id, company_name, main_country, annual_revenue) values (483, 'Vanguard Health Systems', 'Bosnia Herzegovina', 96687.4644);
insert into companies (id, company_name, main_country, annual_revenue) values (484, 'Charles Schwab', 'Andorra', 85259.8833);
insert into companies (id, company_name, main_country, annual_revenue) values (485, 'Susser Holdings', 'Botswana', 84571.5036);
insert into companies (id, company_name, main_country, annual_revenue) values (486, 'YRC Worldwide', 'Spain', 3182.3232);
insert into companies (id, company_name, main_country, annual_revenue) values (487, 'El Paso', 'Mali', 42884.2496);
insert into companies (id, company_name, main_country, annual_revenue) values (488, 'CIT Group', 'Chile', 35519.4873);
insert into companies (id, company_name, main_country, annual_revenue) values (489, 'MetroPCS Communications', 'Switzerland', 60548.0811);
insert into companies (id, company_name, main_country, annual_revenue) values (490, 'Alliant Techsystems', 'Sri Lanka', 78143.015);
insert into companies (id, company_name, main_country, annual_revenue) values (491, 'Celgene', 'Tonga', 57647.4469);
insert into companies (id, company_name, main_country, annual_revenue) values (492, 'MRC Global', 'Russian Federation', 18241.863);
insert into companies (id, company_name, main_country, annual_revenue) values (493, 'Aleris', 'Liberia', 70302.1452);
insert into companies (id, company_name, main_country, annual_revenue) values (494, 'J.M. Smucker', 'Afghanistan', 93188.1522);
insert into companies (id, company_name, main_country, annual_revenue) values (495, 'Rockwell Collins', 'Guyana', 48914.6528);
insert into companies (id, company_name, main_country, annual_revenue) values (496, 'Erie Insurance Group', 'Belize', 73632.2776);
insert into companies (id, company_name, main_country, annual_revenue) values (497, 'Nash-Finch', 'East Timor', 38506.4393);
insert into companies (id, company_name, main_country, annual_revenue) values (498, 'KeyCorp', 'Benin', 92258.4727);
insert into companies (id, company_name, main_country, annual_revenue) values (499, 'Molina Healthcare', 'Liechtenstein', 79972.12);
insert into companies (id, company_name, main_country, annual_revenue) values (500, 'Exxon Mobil', 'Canada', 32568.2364);