insert into universities (id, name, city) values (1, 'University of Buenos Aires', 'Abilene');
insert into universities (id, name, city) values (2, 'National University of La Plata', 'Akron');
insert into universities (id, name, city) values (3, 'Yerevan State University', 'Albuquerque');
insert into universities (id, name, city) values (4, 'University of Adelaide', 'Allentown');
insert into universities (id, name, city) values (5, 'Australian Catholic University', 'Amarillo');
insert into universities (id, name, city) values (6, 'Charles Darwin University', 'Anaheim');
insert into universities (id, name, city) values (7, 'Deakin University', 'Anchorage');
insert into universities (id, name, city) values (8, 'Flinders University', 'Ann Arbor');
insert into universities (id, name, city) values (9, 'James Cook University', 'Antioch');
insert into universities (id, name, city) values (10, 'Macquarie University', 'Apple Valley');
insert into universities (id, name, city) values (11, 'Monash University', 'Appleton');
insert into universities (id, name, city) values (12, 'The University of Newcastle', 'Arlington');
insert into universities (id, name, city) values (13, 'Queensland University of Technology', 'Arvada');
insert into universities (id, name, city) values (14, 'University of South Australia', 'Asheville');
insert into universities (id, name, city) values (15, 'Swinburne University of Technology', 'Athens');
insert into universities (id, name, city) values (16, 'University of Technology Sydney', 'Atlanta');
insert into universities (id, name, city) values (17, 'Western Sydney University', 'Atlantic City');
insert into universities (id, name, city) values (18, 'Carinthia University of Applied Sciences', 'Austin');
insert into universities (id, name, city) values (19, 'Medical University Graz', 'Bakersfield');
insert into universities (id, name, city) values (20, 'Management Center Innsbruck (MCI)', 'Baltimore');
insert into universities (id, name, city) values (21, 'Medical University Innsbruck', 'Barnstable');
insert into universities (id, name, city) values (22, 'IMC University of Applied Sciences Krems', 'Baton Rouge');
insert into universities (id, name, city) values (23, 'Johannes Kepler University Linz', 'Beaumont');
insert into universities (id, name, city) values (24, 'WU Vienna University of Economics and Business', 'Bel Air');
insert into universities (id, name, city) values (25, 'Vienna University of Technology', 'Bellevue');
insert into universities (id, name, city) values (26, 'University of Vienna', 'Berkeley');
insert into universities (id, name, city) values (27, 'University of Applied Sciences Wiener Neustadt for Business and Engineering', 'Bethlehem');
insert into universities (id, name, city) values (28, 'Azerbaijan University of Architecture and Construction', 'Birmingham');
insert into universities (id, name, city) values (29, 'United International University', 'Boise City');
insert into universities (id, name, city) values (30, 'Belarusian State University', 'Boston');
insert into universities (id, name, city) values (31, 'Minsk University of Management', 'Boulder');
insert into universities (id, name, city) values (32, 'Vitebsk State Technological University', 'Bradenton');
insert into universities (id, name, city) values (33, 'Université libre de Bruxelles', 'Brighton');
insert into universities (id, name, city) values (34, 'Ghent University', 'Brownsville');
insert into universities (id, name, city) values (35, 'Catholic University of Leuven', 'Bryan');
insert into universities (id, name, city) values (36, 'University of Mons', 'Burbank');
insert into universities (id, name, city) values (37, 'Saint-Louis University', 'Burlington');
insert into universities (id, name, city) values (38, 'University of Sarajevo', 'Canton');
insert into universities (id, name, city) values (39, 'University of Brasília - UNB', 'Carrollton');
insert into universities (id, name, city) values (40, 'Federal University of Ceará - UFC', 'Cary');
insert into universities (id, name, city) values (41, 'Federal University of Mato Grosso', 'Cathedral City');
insert into universities (id, name, city) values (42, 'Federal University of Paraná', 'Cedar Rapids');
insert into universities (id, name, city) values (43, 'Federal University of Pernambuco', 'Champaign');
insert into universities (id, name, city) values (44, 'Federal University of Rio de Janeiro', 'Chandler');
insert into universities (id, name, city) values (45, 'Universidade Federal de São Paulo', 'Charleston');
insert into universities (id, name, city) values (46, 'Federal University of São Carlos - UFSCAR', 'Charlotte');
insert into universities (id, name, city) values (47, 'American University in Bulgaria', 'Chesapeake');
insert into universities (id, name, city) values (48, 'New Bulgarian University', 'Chicago');
insert into universities (id, name, city) values (49, 'Medical University - Plovdiv', 'Chula Vista');
insert into universities (id, name, city) values (50, 'Angel Kanchev University of Ruse', 'Cincinnati');
insert into universities (id, name, city) values (51, 'Sofia University St. Kliment Ohridski', 'Clarke County');
insert into universities (id, name, city) values (52, 'University of Economics - Varna', 'Clarksville');
insert into universities (id, name, city) values (53, 'IIC University of Technology', 'Cleveland');
