insert into universities (id,name) values(1,'Harvard University');
insert into universities (id,name) values(2,'Stanford University');
insert into universities (id,name) values(3,'Massachusetts Institute of Technology (MIT)');
insert into universities (id,name) values(4,'University of California Berkeley (UCB)');
insert into universities (id,name) values(5,'University of California, Los Angeles (UCLA)');
insert into universities (id,name) values(6,'Yale University');
insert into universities (id,name) values(7,'Columbia University');
insert into universities (id,name) values(8,'Princeton University');
insert into universities (id,name) values(9,'New York University (NYU)');
insert into universities (id,name) values(10,'University of Pennsylvania');
insert into universities (id,name) values(11,'University of Chicago');
insert into universities (id,name) values(12,'Cornell University');
insert into universities (id,name) values(13,'Duke University');
insert into universities (id,name) values(14,'Johns Hopkins University');
insert into universities (id,name) values(15,'University of Southern California');
insert into universities (id,name) values(16,'Northwestern University');
insert into universities (id,name) values(17,'Carnegie Mellon University');
insert into universities (id,name) values(18,'University of Michigan ');
insert into universities (id,name) values(19,'Brown University');
insert into universities (id,name) values(20,'Boston University');
insert into universities (id,name) values(21,'California Institute of Technology (Caltech)');
insert into universities (id,name) values(22,'Emory University');
insert into universities (id,name) values(23,'Rice University');
insert into universities (id,name) values(24,'University of Washington, Seattle');
insert into universities (id,name) values(25,'Washington University in St. Louis');
insert into universities (id,name) values(26,'Georgetown University');
insert into universities (id,name) values(27,'University of California, San Diego (UCSD)');
insert into universities (id,name) values(28,'Vanderbilt University');
insert into universities (id,name) values(29,'University of Texas at Austin');
insert into universities (id,name) values(30,'University of Illinois at Urbana-Champaign');
insert into universities (id,name) values(31,'University of Rochester');
insert into universities (id,name) values(32,'Dartmouth College');
insert into universities (id,name) values(33,'University of North Carolina, Chapel Hill');
insert into universities (id,name) values(34,'University of California, Davis (UCD)');
insert into universities (id,name) values(35,'University of Florida');
insert into universities (id,name) values(36,'Tufts University');
insert into universities (id,name) values(37,'University of Illinois, Chicago (UIC)');
insert into universities (id,name) values(38,'Georgia Institute of Technology (Georgia Tech)');
insert into universities (id,name) values(39,'Stony Brook University');
insert into universities (id,name) values(40,'University of Virginia');
insert into universities (id,name) values(41,'Case Western Reserve University');
insert into universities (id,name) values(42,'Rutgers - The State University of New Jersey, New Brunswick');
insert into universities (id,name) values(43,'University of California, Santa Barbara (UCSB)');
insert into universities (id,name) values(44,'Pennsylvania State University, University Park');
insert into universities (id,name) values(45,'George Washington University');
insert into universities (id,name) values(46,'University of California, Irvine (UCI)');
insert into universities (id,name) values(47,'University of Notre Dame');
insert into universities (id,name) values(48,'University of Miami');
insert into universities (id,name) values(49,'Northeastern University');
insert into universities (id,name) values(50,'Ohio State University, Columbus');
insert into universities (id,name) values(51,'University at Buffalo SUNY');
insert into universities (id,name) values(52,'University of Maryland, College Park');
insert into universities (id,name) values(53,'Purdue University');
insert into universities (id,name) values(54,'University of Minnesota, Twin Cities');
insert into universities (id,name) values(55,'Boston College');
insert into universities (id,name) values(56,'Michigan State University');
insert into universities (id,name) values(57,'University of Massachusetts, Amherst');
insert into universities (id,name) values(58,'University of Wisconsin-Madison');
insert into universities (id,name) values(59,'Syracuse University');
insert into universities (id,name) values(60,'Lehigh University');
insert into universities (id,name) values(61,'University of Pittsburgh');
insert into universities (id,name) values(62,'Arizona State University, Tempe');
insert into universities (id,name) values(63,'Brandeis University');
insert into universities (id,name) values(64,'Temple University');
insert into universities (id,name) values(65,'Texas A&M University');
insert into universities (id,name) values(66,'University of Arizona');
insert into universities (id,name) values(67,'University of Houston');
insert into universities (id,name) values(68,'Binghamton University, SUNY');
insert into universities (id,name) values(69,'Drexel University');
insert into universities (id,name) values(70,'North Carolina State University');
insert into universities (id,name) values(71,'Rensselaer Polytechnic Institute');
insert into universities (id,name) values(72,'University of Connecticut');
insert into universities (id,name) values(73,'University of Georgia');
insert into universities (id,name) values(74,'Virginia Polytechnic Institute (Virginia Tech)');
insert into universities (id,name) values(75,'University of New Mexico');
insert into universities (id,name) values(76,'Indiana University Bloomington');
insert into universities (id,name) values(77,'Tulane University');
insert into universities (id,name) values(78,'University of Colorado at Boulder');
insert into universities (id,name) values(79,'Florida State University');
insert into universities (id,name) values(80,'University of South Florida');
insert into universities (id,name) values(81,'Illinois Institute of Technology');
insert into universities (id,name) values(82,'University of California, Riverside (UCR)');
insert into universities (id,name) values(83,'University of California, Santa Cruz (UCSC)');
insert into universities (id,name) values(84,'Howard University');
insert into universities (id,name) values(85,'University of Texas Dallas');
insert into universities (id,name) values(86,'Santa Clara University');
insert into universities (id,name) values(87,'Wake Forest University');
insert into universities (id,name) values(88,'University of Maryland, Baltimore County');
insert into universities (id,name) values(89,'University of Utah');
insert into universities (id,name) values(90,'George Mason University');
insert into universities (id,name) values(91,'New Jersey Institute of Technology (NJIT)');
insert into universities (id,name) values(92,'University of Massachusetts, Boston');
insert into universities (id,name) values(93,'University of Kansas');
insert into universities (id,name) values(94,'University at Albany SUNY');
insert into universities (id,name) values(95,'Oregon State University');
insert into universities (id,name) values(96,'University of Delaware');
insert into universities (id,name) values(97,'University of the Pacific');
insert into universities (id,name) values(98,'Rutgers - The State University of New Jersey, Newark');
insert into universities (id,name) values(99,'University of Hawai''i at Manoa');
insert into universities (id,name) values(100,'San Diego State University');
