drop table if exists cities cascade;
drop table if exists people cascade;
drop table if exists residences cascade;
drop table if exists historical_residences cascade;
drop table if exists companies cascade;
drop table if exists universities cascade;
drop table if exists fields_of_study cascade;
drop table if exists majors cascade;
drop table if exists educations cascade;
drop table if exists emails cascade;
drop table if exists positions cascade;
drop table if exists roles cascade;
drop table if exists work_places cascade;
drop table if exists historical_work_places cascade;
drop table if exists jobs cascade;
drop table if exists historical_salaries cascade;
drop table if exists recommendations cascade;
drop table if exists job_offers cascade;
drop table if exists open_close_hours cascade;

drop function if exists companyofrole(role integer);
drop function if exists companyofrole(role numeric);
drop function if exists companyofworkplace(place integer);
drop function if exists employedthen(time_of_rec date, recommender integer, role integer);
drop function if exists employedthen(time_of_rec date, recommender numeric, role numeric);
drop function if exists isinrange(salary integer, id integer);
drop function if exists isinrange(salary numeric, id integer);
drop function if exists isinrange(salary numeric, id numeric);
drop function if exists job_end(id integer);
drop function if exists job_start(id integer);
drop function if exists maxrangeforrole(role integer);
drop function if exists minrangeforrole(role integer);
drop function if exists notemployedthen(time_of_rec date, recommended integer, role integer);
drop function if exists notemployedthen(time_of_rec date, recommended numeric, role numeric);
drop function if exists onecompanyonejob(employee_new integer, company_id_new integer, start_of_new_job date, end_of_new_job date);
drop function if exists universityofmajor(major integer);

drop function if exists addcorporatemail();
drop function if exists adduniversitymail();
drop function if exists alter_place_of_job();
drop function if exists alterresidences();
drop function if exists altersalaries();
drop function if exists defaulteduend();
drop function if exists delfromcities();
drop function if exists delfromcompanies();
drop function if exists delfromfields();
drop function if exists delfromjobs();
drop function if exists delfrommajors();
drop function if exists delfrompeople();
drop function if exists delfromplaces();
drop function if exists delfrompositions();
drop function if exists delfromroles();
drop function if exists delfromuni();
drop function if exists jobchange();
drop function if exists onecompanyonejob();
drop function if exists updatesalary();

drop function if exists randomemployee(company integer, whenn date);
drop function if exists randomrole(company integer, whenn date);

drop function if exists ignorebadinsertsinreco();