insert into positions (id,name) values ( 1, 'Software Engineer Intern' );
insert into positions (id,name) values ( 2, 'Junior Software Engineer' );
insert into positions (id,name) values ( 3, 'Middle Software Engineer' );
insert into positions (id,name) values ( 4, 'Senior Software Engineer' );
insert into positions (id,name) values ( 5, 'Tech Lead' );
insert into positions (id,name) values ( 6, 'Team Lead' );
insert into positions (id,name) values ( 7, 'Product Manager' );
insert into positions (id,name) values ( 8, 'Analytic-Programmer' );
insert into positions (id,name) values ( 9, 'Research Intern' );
insert into positions (id,name) values ( 10, 'CEO' );
insert into positions (id,name) values ( 11, 'CFO' );
insert into positions (id,name) values ( 12, 'COO' );
insert into positions (id,name) values ( 13, 'Department Manager' );
insert into positions (id,name) values ( 14, 'Manager' );
insert into positions (id,name) values ( 15, 'Clerk' );
insert into positions (id,name) values ( 16, 'HR Manager' );
insert into positions (id,name) values ( 17, 'IT Recruiter' );
insert into positions (id,name) values ( 18, 'Working Student' );
insert into positions (id,name) values ( 19, 'Junior Algorithm Assistant' );
insert into positions (id,name) values ( 20, 'Algorithm Engineer' );
insert into positions (id,name) values ( 21, 'ML Engineer' );
insert into positions (id,name) values ( 22, 'Data Scientist' );
insert into positions (id,name) values ( 23, 'Mobile Engineer' );
insert into positions (id,name) values ( 24, 'Frontend Engineer' );
insert into positions (id,name) values ( 25, 'Backend Engineer' );
insert into positions (id,name) values ( 26, 'Janitor' );
insert into positions (id,name) values ( 27, 'Barista' );
insert into positions (id,name) values ( 28, 'Waiter' );
insert into positions (id,name) values ( 29, 'Cashier' );
insert into positions (id,name) values ( 30, 'Marketer' );
insert into positions (id,name) values ( 31, 'Analytic' );
insert into positions (id,name) values ( 32, 'Full-Stack web developer' );
insert into positions (id,name) values ( 33, 'DevOps Engineer' );
insert into positions (id,name) values ( 34, 'System Administrator' );
insert into positions (id,name) values ( 35, 'Delivery person' );
insert into positions (id,name) values ( 36, 'Personal Assistant' );
insert into positions (id,name) values ( 37, 'Software Engineer Intern in Test' );
insert into positions (id,name) values ( 38, 'Test Engineer' );
insert into positions (id,name) values ( 39, 'Group Lead' );
insert into positions (id,name) values ( 40, 'Department Lead' );
