insert into fields_of_study (id, name) values (1, 'Theoretical Computer Science');
insert into fields_of_study (id, name) values (2, 'Computer Information Systems');
insert into fields_of_study (id, name) values (3, 'Information Technology');
insert into fields_of_study (id, name) values (4, 'Information Science');
insert into fields_of_study (id, name) values (5, 'Computer Systems Networking');
insert into fields_of_study (id, name) values (6, 'Computer Software & Applications');
insert into fields_of_study (id, name) values (7, 'Computer Programming');
insert into fields_of_study (id, name) values (8, 'Computer Systems Analysis');
insert into fields_of_study (id, name) values (9, 'Data Processing');
insert into fields_of_study (id, name) values (10, 'Data Entry');
insert into fields_of_study (id, name) values (11, 'Other Computer & Information Sciences');
insert into fields_of_study (id, name) values (12,'Algorithms and complexity');
insert into fields_of_study (id, name) values (13,'Architecture and organization');
insert into fields_of_study (id, name) values (14,'Computational science');
insert into fields_of_study (id, name) values (15,'Graphics and visual computing');
insert into fields_of_study (id, name) values (16,'Human-computer interaction');
insert into fields_of_study (id, name) values (17,'Information management');
insert into fields_of_study (id, name) values (18,'Intelligent systems');
insert into fields_of_study (id, name) values (19,'Networking and communication');
insert into fields_of_study (id, name) values (20,'Operating systems');
insert into fields_of_study (id, name) values (21,'Parallel and distributed computing');
insert into fields_of_study (id, name) values (22,'Platform-based development');
insert into fields_of_study (id, name) values (23,'Programming languages');
insert into fields_of_study (id, name) values (24,'Security and information assurance');
insert into fields_of_study (id, name) values (25,'Software engineering');